In [1]:
import sys
import os
sys.path.insert(0, os.path.abspath(".."))

import requests
import pandas as pd
import re
import json
import time
from Bio import Entrez

from src.ena_fetcher import (
    search_ena_studies, 
    fetch_runs_for_study, 
    resolve_host_species,
    fetch_study_origin,
    fetch_abstract_from_pmid
)
from src.fetcher import configure_entrez

configure_entrez()
print("ready")

Entrez configured with email: akharya@ucsd.edu
ready

In [2]:
# load all MMC batch CSVs (ENA Accessions from PMIDs)
mmc_batch1 = pd.read_csv("../results/pmid-ena-results-2026-05-18-batch1.csv")
mmc_batch2 = pd.read_csv("../results/pmid-ena-results-2026-05-19-batch2.csv")
mmc_batch34 = pd.read_csv("../results/pmid-ena-results-2026-05-19-batch3.csv") 

print(f"Batch 1: {len(mmc_batch1)} papers, {(mmc_batch1['accession_count']>0).sum()} with accessions")
print(f"Batch 2: {len(mmc_batch2)} papers, {(mmc_batch2['accession_count']>0).sum()} with accessions")
print(f"Batch 3+4: {len(mmc_batch34)} papers, {(mmc_batch34['accession_count']>0).sum()} with accessions")

Batch 1: 500 papers, 202 with accessions
Batch 2: 500 papers, 223 with accessions
Batch 3+4: 846 papers, 310 with accessions

In [3]:
# extract all unique project accessions from all batches
all_mmc = pd.concat([mmc_batch1, mmc_batch2, mmc_batch34], ignore_index=True)

pubmed_accessions = []
for _, row in all_mmc[all_mmc["accessions"].notna()].iterrows():
    for acc in str(row["accessions"]).split(";"):
        acc = acc.strip()
        if re.match(r'PRJ[ENDB][A-Z]\d+', acc):
            pubmed_accessions.append(acc)

pubmed_accessions = list(set(pubmed_accessions))
print(f"Total unique project accessions from PubMed: {len(pubmed_accessions)}")

Total unique project accessions from PubMed: 891

In [4]:
# load ENA taxonomy search results (ENA route)
ena_queries = [
    'tax_tree(749906) AND library_strategy="WGS"',
    'tax_tree(1861841) AND library_strategy="WGS"',
    'tax_tree(506600) AND library_strategy="WGS"',
    'tax_tree(410661) AND library_strategy="WGS"',
    'tax_tree(1510822) AND library_strategy="WGS"',
    'tax_tree(1602388) AND library_strategy="WGS"',
    'tax_tree(408170) AND library_strategy="WGS"',
]

ena_accessions = set()
for query in ena_queries:
    accessions = search_ena_studies(query, max_results=500)
    ena_accessions.update(accessions)
    print(f"{query.split('tax_tree(')[1].split(')')[0]} → {len(accessions)} studies")
    time.sleep(1)

print(f"\nTotal ENA taxonomy accessions: {len(ena_accessions)}")

# combine both sources
all_accessions = set(pubmed_accessions) | ena_accessions
print(f"Total unique accessions combined: {len(all_accessions)}")

Found 5000 runs, 66 unique studies
749906 → 66 studies
Found 5000 runs, 204 unique studies
1861841 → 204 studies
Found 5000 runs, 89 unique studies
506600 → 89 studies
Found 5000 runs, 77 unique studies
410661 → 77 studies
Found 5000 runs, 112 unique studies
1510822 → 112 studies
Found 3160 runs, 63 unique studies
1602388 → 63 studies
Found 5000 runs, 70 unique studies
408170 → 70 studies

Total ENA taxonomy accessions: 674
Total unique accessions combined: 1502

In [5]:
import json

all_accessions_list = list(all_accessions)

with open("../results/all_accessions.json", "w") as f:
    json.dump(all_accessions_list, f)

print(f"Saved {len(all_accessions_list)} accessions to all_accessions.json")

Saved 1502 accessions to all_accessions.json

In [6]:
acc_to_pmid = {}
for _, row in all_mmc[all_mmc["accessions"].notna()].iterrows():
    pmid = str(row["pmid"])
    for acc in str(row["accessions"]).split(";"):
        acc = acc.strip()
        if re.match(r'PRJ[ENDB][A-Z]\d+', acc):
            acc_to_pmid[acc] = pmid

with open("../results/acc_to_pmid.json", "w") as f:
    json.dump(acc_to_pmid, f)

print(f"Accession to PMID mappings: {len(acc_to_pmid)}")
print(f"Studies with abstracts available: {len(acc_to_pmid)}")
print(f"Studies without abstracts (ENA only): {len(all_accessions) - len(acc_to_pmid)}")

Accession to PMID mappings: 891
Studies with abstracts available: 891
Studies without abstracts (ENA only): 611

In [7]:
# fetch metadata for all 1502 studies
results = []

for i, study in enumerate(all_accessions_list):
    if i % 50 == 0:
        print(f"Progress: {i}/{len(all_accessions_list)}")
    
    runs_df = fetch_runs_for_study(study)
    if runs_df is None or len(runs_df) == 0:
        continue
    
    results.append({
        "study_accession": study,
        "host_species": resolve_host_species(runs_df),
        "host_tax_id": runs_df["host_tax_id"].dropna().mode()[0] if len(runs_df["host_tax_id"].dropna()) > 0 else None,
        "body_site": runs_df["host_body_site"].dropna().mode()[0] if len(runs_df["host_body_site"].dropna()) > 0 else "",
        "country": runs_df["country"].dropna().mode()[0] if len(runs_df["country"].dropna()) > 0 else "",
        "n_samples": runs_df["sample_accession"].nunique(),
        "library_strategy": runs_df["library_strategy"].dropna().mode()[0] if len(runs_df["library_strategy"].dropna()) > 0 else None,
        "data_source": "pubmed" if study in acc_to_pmid else "ena_only",
        "pmid": acc_to_pmid.get(study)
    })
    time.sleep(0.3)

# save immediately
pd.DataFrame(results).to_csv("../results/catalog_raw.tsv", sep="\t", index=False)
print(f"\nFetched metadata for {len(results)} studies")
print(f"Saved to catalog_raw.tsv")

Progress: 0/1502
No runs found for PRJNA1310243
No runs found for PRJNA1416997
No runs found for PRJNA10203991

KeyboardInterrupt:

In [8]:
# check if acc_to_pmid has the same accessions as pubmed_accessions
pubmed_set = set(pubmed_accessions)
pmid_set = set(acc_to_pmid.keys())

print(f"pubmed_accessions: {len(pubmed_set)}")
print(f"acc_to_pmid keys: {len(pmid_set)}")
print(f"Are they identical? {pubmed_set == pmid_set}")
print(f"In pubmed but not pmid mapping: {len(pubmed_set - pmid_set)}")
print(f"In pmid mapping but not pubmed: {len(pmid_set - pubmed_set)}")

pubmed_accessions: 891
acc_to_pmid keys: 891
Are they identical? True
In pubmed but not pmid mapping: 0
In pmid mapping but not pubmed: 0

In [9]:
# fetch metadata for all 1502 studies
results = []

for i, study in enumerate(all_accessions_list):
    if i % 50 == 0:
        print(f"Progress: {i}/{len(all_accessions_list)}")
    
    runs_df = fetch_runs_for_study(study)
    if runs_df is None or len(runs_df) == 0:
        continue
    
    results.append({
        "study_accession": study,
        "host_species": resolve_host_species(runs_df),
        "host_tax_id": runs_df["host_tax_id"].dropna().mode()[0] if len(runs_df["host_tax_id"].dropna()) > 0 else None,
        "body_site": runs_df["host_body_site"].dropna().mode()[0] if len(runs_df["host_body_site"].dropna()) > 0 else "",
        "country": runs_df["country"].dropna().mode()[0] if len(runs_df["country"].dropna()) > 0 else "",
        "n_samples": runs_df["sample_accession"].nunique(),
        "library_strategy": runs_df["library_strategy"].dropna().mode()[0] if len(runs_df["library_strategy"].dropna()) > 0 else None,
        "data_source": "pubmed" if study in acc_to_pmid else "ena_only",
        "pmid": acc_to_pmid.get(study)
    })
    time.sleep(0.3)

# save immediately
pd.DataFrame(results).to_csv("../results/catalog_raw.tsv", sep="\t", index=False)
print(f"\nFetched metadata for {len(results)} studies")
print(f"Saved to catalog_raw.tsv")

Progress: 0/1502
No runs found for PRJNA1310243
No runs found for PRJNA1416997
No runs found for PRJNA10203991
Progress: 50/1502
No runs found for PRJEB35945
No runs found for PRJNA95448
Progress: 100/1502
No runs found for PRJNA1205488
No runs found for PRJNA765142
Progress: 150/1502
No runs found for PRJDB4392
No runs found for PRJNA1023627
No runs found for PRJEB43619
No runs found for PRJNA925792
No runs found for PRJNA836733
No runs found for PRJNA1211720
No runs found for PRJNA20689
No runs found for PRJNA888994
Progress: 200/1502
No runs found for PRJNA657473
No runs found for PRJNA288223
No runs found for PRJNA1193846
No runs found for PRJEB14698
Progress: 250/1502
No runs found for PRJEB20626
No runs found for PRJNA1217447
No runs found for PRJNA977461
Progress: 300/1502
No runs found for PRJNA1224300
No runs found for PRJNA755318
No runs found for PRJNA647163
No runs found for PRJEB1046
No runs found for PRJNA810349
No runs found for PRJEB801559
No runs found for PRJNA68445427
No runs found for PRJDB13917
Progress: 350/1502
No runs found for PRJNA894235
No runs found for PRJNA1144017
No runs found for PRJNA1077584
Progress: 400/1502
No runs found for PRJEB674
No runs found for PRJNA608666
No runs found for PRJNA669977
No runs found for PRJEB81441
No runs found for PRJNA1333881
No runs found for PRJNA1268717
No runs found for PRJNA1023628
Progress: 450/1502
No runs found for PRJNA1118910
No runs found for PRJNA790931
No runs found for PRJNA1431711
No runs found for PRJNA1225000
Progress: 500/1502
No runs found for PRJNA1344668
No runs found for PRJEB55374
No runs found for PRJNA1230565
Progress: 550/1502
No runs found for PRJNA1023577
No runs found for PRJEB35610
No runs found for PRJNA792464
No runs found for PRJNA773059
Progress: 600/1502
No runs found for PRJNA8631314
No runs found for PRJNA835612
No runs found for PRJNA1227685
Progress: 650/1502
No runs found for PRJNA1127260
No runs found for PRJNA1428989
No runs found for PRJNA1028308
Progress: 700/1502
No runs found for PRJNA682348
No runs found for PRJNA1049592
No runs found for PRJNA725502
Progress: 750/1502
No runs found for PRJNA948045
No runs found for PRJEB4309633
Progress: 800/1502
No runs found for PRJNA843204
No runs found for PRJNA910333
No runs found for PRJNA1393325
No runs found for PRJNA687329
Progress: 850/1502
No runs found for PRJNA1322061
Progress: 900/1502
No runs found for PRJNA1015412
No runs found for PRJNA1049387
No runs found for PRJNA826263
No runs found for PRJNA923757
No runs found for PRJNA863131
Progress: 950/1502
No runs found for PRJNA923754
Progress: 1000/1502
No runs found for PRJNA82536
No runs found for PRJNA61338131
No runs found for PRJEB55376
No runs found for PRJNA1357588
Progress: 1050/1502
No runs found for PRJNA1196159
Progress: 1100/1502
No runs found for PRJEB33885
No runs found for PRJNA1024674
Progress: 1150/1502
No runs found for PRJNA1170951
No runs found for PRJNA128711
Progress: 1200/1502
No runs found for PRJNA12624
No runs found for PRJNA1150362
No runs found for PRJNA1030165
No runs found for PRJDB9243
Progress: 1250/1502
No runs found for PRJNA290381
No runs found for PRJNA923293
No runs found for PRJNA331216
No runs found for PRJNA313047
Progress: 1300/1502
No runs found for PRJEB45252
No runs found for PRJNA923758
No runs found for PRJEB94130
Progress: 1350/1502
No runs found for PRJNA1065120
No runs found for PRJEB871798
No runs found for PRJNA925821
No runs found for PRJEB4309734
Error fetching PRJNA263829: HTTPSConnectionPool(host='www.ebi.ac.uk', port=443): Read timed out.
No runs found for PRJNA1381256
No runs found for PRJNA1289876
Progress: 1400/1502
No runs found for PRJNA761907
No runs found for PRJNA1418170
No runs found for PRJNA1264687
No runs found for PRJEB55375
No runs found for PRJNA1392796
No runs found for PRJNA240272
Progress: 1450/1502
No runs found for PRJNA1415316
No runs found for PRJNA669979
No runs found for PRJNA1290942
No runs found for PRJEB35751
No runs found for PRJNA1126667
No runs found for PRJNA115737
Progress: 1500/1502

Fetched metadata for 1390 studies
Saved to catalog_raw.tsv

In [10]:
# check what we have
catalog_raw = pd.read_csv("../results/catalog_raw.tsv", sep="\t")

print(f"Total studies: {len(catalog_raw)}")
print(f"PubMed studies: {(catalog_raw['data_source'] == 'pubmed').sum()}")
print(f"ENA-only studies: {(catalog_raw['data_source'] == 'ena_only').sum()}")
print(f"Total samples: {catalog_raw['n_samples'].sum()}")
print(f"\nTop library strategies:")
print(catalog_raw['library_strategy'].value_counts().head(10))
print(f"\nStudies with host resolved: {catalog_raw['host_species'].notna().sum()}")

Total studies: 1390
PubMed studies: 779
ENA-only studies: 611
Total samples: 172104

Top library strategies:
library_strategy
WGS                 899
AMPLICON            374
RNA-Seq              49
OTHER                40
WGA                  18
Targeted-Capture      2
RAD-Seq               2
CLONEEND              2
ChIP-Seq              2
Hi-C                  1
Name: count, dtype: int64

Studies with host resolved: 1218

In [11]:
# keep only WGS and METAGENOMIC studies
wgs_catalog = catalog_raw[catalog_raw["library_strategy"].isin(["WGS", "METAGENOMIC", "WGA"])]

print(f"WGS/Metagenomic studies: {len(wgs_catalog)}")
print(f"Total WGS samples: {wgs_catalog['n_samples'].sum()}")
print(f"Host resolved: {wgs_catalog['host_species'].notna().sum()}")

WGS/Metagenomic studies: 917
Total WGS samples: 105289
Host resolved: 775

In [12]:
wgs_catalog = catalog_raw[catalog_raw["library_strategy"].isin(["WGS", "METAGENOMIC", "WGA"])]

print(f"WGS studies: {len(wgs_catalog)}")
print(f"WGS samples: {wgs_catalog['n_samples'].sum()}")

# check host species to identify non-microbiome studies
print(f"\nTop host species in WGS studies:")
print(wgs_catalog['host_species'].value_counts().head(20))

WGS studies: 917
WGS samples: 105289

Top host species in WGS studies:
host_species
Homo sapiens                156
Mus musculus                 67
Gallus gallus                63
Sus scrofa                   62
feces metagenome             35
Sus scrofa domesticus        21
Bos taurus                   14
fish gut metagenome          13
missing                      13
pig gut metagenome           11
mouse                        10
chicken gut metagenome       10
Canis lupus familiaris        9
Salmo salar                   7
rat                           6
Felis catus                   6
Gallus gallus domesticus      6
Rattus norvegicus             5
Equus caballus                4
Escherichia coli              4
Name: count, dtype: int64

In [13]:
# identify likely metagenome studies
metagenome_terms = ["metagenome", "microbiome", "microbiota"]

def is_likely_metagenome(row):
    # if host_species contains metagenome terms - definitely microbiome
    host = str(row.get("host_species", "")).lower()
    if any(term in host for term in metagenome_terms):
        return True
    # if from pubmed and has a real animal host - likely microbiome
    if row.get("data_source") == "pubmed":
        return True
    return False

wgs_catalog["likely_metagenome"] = wgs_catalog.apply(is_likely_metagenome, axis=1)

print(f"Likely metagenome studies: {wgs_catalog['likely_metagenome'].sum()}")
print(f"Possibly non-metagenome: {(~wgs_catalog['likely_metagenome']).sum()}")
print(f"\nSamples in likely metagenome studies: {wgs_catalog[wgs_catalog['likely_metagenome']]['n_samples'].sum()}")

Likely metagenome studies: 440
Possibly non-metagenome: 477

Samples in likely metagenome studies: 51066

/var/folders/ws/dmbkn8cx75l33lp2zph5rpbw0000gn/T/ipykernel_45649/978602913.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wgs_catalog["likely_metagenome"] = wgs_catalog.apply(is_likely_metagenome, axis=1)

In [14]:
def verify_is_metagenome(study_accession, title, abstract, client):
    """
    Use Claude to verify if a study is a genuine gut microbiome study.
    Returns True/False and a confidence level.
    """
    text = f"Title: {title or 'Not available'}\n\nAbstract: {abstract or 'Not available'}"
    
    prompt = f"""Is this a shotgun metagenomics study of a microbial community 
associated with an animal host (gut, fecal, intestinal)?

{text}

Answer with exactly one of:
YES - this is an animal gut/intestinal shotgun metagenomics study
NO - this is not a gut metagenomics study (explain briefly why)
UNCLEAR - cannot determine from available information"""

    try:
        message = client.messages.create(
            model="claude-haiku-4-5",
            max_tokens=100,
            system="You are a bioinformatics expert classifying sequencing studies.",
            messages=[{"role": "user", "content": prompt}]
        )
        result = message.content[0].text.strip()
        return result
    except Exception as e:
        return f"ERROR: {e}"

In [15]:
# fetch abstracts for all WGS studies with PMIDs
wgs_abstracts = {}

wgs_with_pmid = wgs_catalog[wgs_catalog["pmid"].notna()]
print(f"WGS studies with PMID: {len(wgs_with_pmid)}")

for i, row in wgs_with_pmid.iterrows():
    pmid = str(row["pmid"])
    if i % 50 == 0:
        print(f"Progress: {len(wgs_abstracts)}/{len(wgs_with_pmid)}")
    
    abstract = fetch_abstract_from_pmid(pmid)
    wgs_abstracts[row["study_accession"]] = abstract
    time.sleep(0.3)

# save abstracts
with open("../results/wgs_abstracts.json", "w") as f:
    json.dump(wgs_abstracts, f)

found = sum(1 for a in wgs_abstracts.values() if a)
print(f"\nAbstracts found: {found}/{len(wgs_with_pmid)}")

WGS studies with PMID: 375
Progress: 0/375
Progress: 14/375
Progress: 77/375
Progress: 91/375
Progress: 162/375
Progress: 180/375
Progress: 191/375
Progress: 315/375
Progress: 332/375

Abstracts found: 375/375

In [17]:
# add abstracts to wgs_catalog using .loc
wgs_catalog.loc[:, "abstract"] = wgs_catalog["study_accession"].map(wgs_abstracts)

# save abstracts
with open("../results/wgs_abstracts.json", "w") as f:
    json.dump(wgs_abstracts, f)

print(f"Studies with abstracts: {wgs_catalog['abstract'].notna().sum()}")
print(f"Studies without abstracts: {wgs_catalog['abstract'].isna().sum()}")

Studies with abstracts: 375
Studies without abstracts: 542

In [18]:
# fetch titles for studies that don't have them yet
titles = {}
for i, row in wgs_catalog.iterrows():
    if i % 50 == 0:
        print(f"Progress: {len(titles)}/{len(wgs_catalog)}")
    
    provenance = fetch_study_origin(row["study_accession"])
    titles[row["study_accession"]] = provenance.get("title")
    time.sleep(0.3)

wgs_catalog["title"] = wgs_catalog["study_accession"].map(titles)

# save
with open("../results/wgs_titles.json", "w") as f:
    json.dump(titles, f)

print(f"Studies with titles: {wgs_catalog['title'].notna().sum()}")

Progress: 0/917
Progress: 34/917
Progress: 67/917
Progress: 132/917
Progress: 168/917
Progress: 196/917
Progress: 229/917
Progress: 413/917
Progress: 445/917
Progress: 478/917

KeyboardInterrupt:

In [19]:
from concurrent.futures import ThreadPoolExecutor
import threading

def fetch_title_safe(study_accession):
    try:
        provenance = fetch_study_origin(study_accession)
        time.sleep(0.1)
        return study_accession, provenance.get("title")
    except Exception as e:
        return study_accession, None

print(f"Fetching titles for {len(wgs_catalog)} studies...")

with ThreadPoolExecutor(max_workers=5) as executor:
    results = list(executor.map(
        fetch_title_safe,
        wgs_catalog["study_accession"].tolist()
    ))

titles = {acc: title for acc, title in results}
wgs_catalog.loc[:, "title"] = wgs_catalog["study_accession"].map(titles)

# save
with open("../results/wgs_titles.json", "w") as f:
    json.dump(titles, f)

print(f"Studies with titles: {wgs_catalog['title'].notna().sum()}")
print(f"Studies without titles: {wgs_catalog['title'].isna().sum()}")

Fetching titles for 917 studies...
Studies with titles: 915
Studies without titles: 2

/var/folders/ws/dmbkn8cx75l33lp2zph5rpbw0000gn/T/ipykernel_45649/4169092594.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wgs_catalog.loc[:, "title"] = wgs_catalog["study_accession"].map(titles)

In [20]:
wgs_catalog = catalog_raw[catalog_raw["library_strategy"].isin(["WGS", "METAGENOMIC", "WGA"])].copy()
wgs_catalog["abstract"] = wgs_catalog["study_accession"].map(wgs_abstracts)
wgs_catalog["title"] = wgs_catalog["study_accession"].map(titles)

In [21]:
wgs_catalog.to_csv("../results/wgs_catalog.tsv", sep="\t", index=False)
print(f"Saved {len(wgs_catalog)} WGS studies to wgs_catalog.tsv")
print(f"Columns: {list(wgs_catalog.columns)}")

Saved 917 WGS studies to wgs_catalog.tsv
Columns: ['study_accession', 'host_species', 'host_tax_id', 'body_site', 'country', 'n_samples', 'library_strategy', 'data_source', 'pmid', 'abstract', 'title']

In [24]:
import anthropic
from concurrent.futures import ThreadPoolExecutor

client = anthropic.Anthropic()

def verify_is_metagenome(row):
    study_accession = row["study_accession"]
    title = row.get("title") if isinstance(row.get("title"), str) else "Not available"
    abstract = row.get("abstract") if isinstance(row.get("abstract"), str) else "Not available"
    abstract_text = abstract if isinstance(abstract, str) else "Not available"
    
    prompt = f"""Is this a shotgun metagenomics study of a microbial community associated with an animal host (gut, fecal, intestinal)?

Title: {title}
Abstract: {abstract[:500] if abstract != "Not available" else "Not available"}

Answer with exactly one of:
YES - this is an animal gut/intestinal shotgun metagenomics study
NO - this is not a gut metagenomics study (explain briefly why)
UNCLEAR - cannot determine from available information"""

    try:
        message = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=10,
            system="You are a bioinformatics expert classifying sequencing studies.",
            messages=[{"role": "user", "content": prompt}]
        )
        return study_accession, message.content[0].text.strip()
    except Exception as e:
        return study_accession, f"ERROR: {e}"

print(f"Verifying {len(wgs_catalog)} studies...")

rows = wgs_catalog.to_dict("records")

with ThreadPoolExecutor(max_workers=20) as executor:
    results = list(executor.map(verify_is_metagenome, rows))

verification = {acc: verdict for acc, verdict in results}

# add to catalog
wgs_catalog = wgs_catalog.copy()
wgs_catalog["claude_verification"] = wgs_catalog["study_accession"].map(verification)

# save
wgs_catalog.to_csv("../results/wgs_catalog_verified.tsv", sep="\t", index=False)

# summary
yes = sum(1 for v in verification.values() if v.startswith("YES"))
no = sum(1 for v in verification.values() if v.startswith("NO"))
unclear = sum(1 for v in verification.values() if v.startswith("UNCLEAR"))
print(f"\nYES: {yes}")
print(f"NO: {no}")
print(f"UNCLEAR: {unclear}")

Verifying 917 studies...

KeyboardInterrupt:

In [25]:
import re

def classify_study(row):
    title = str(row.get("title") or "").lower()
    abstract = str(row.get("abstract") or "").lower()
    text = title + " " + abstract
    
    # definite NO terms
    no_terms = [
        "genome sequence", "whole genome sequencing", "draft genome",
        "chromosome", "transcriptome", "rna-seq", "gene expression",
        "genome assembly", "reference genome", "resequencing",
        "snp", "qtl", "gwas", "population genetics"
    ]
    
    # definite YES terms
    yes_terms = [
        "microbiome", "microbiota", "metagenome", "metagenomics",
        "gut bacteria", "gut flora", "intestinal bacteria", "fecal bacteria",
        "16s", "shotgun metagenomics", "whole metagenome"
    ]
    
    if any(term in text for term in no_terms):
        return "NO_regex"
    if any(term in text for term in yes_terms):
        return "YES_regex"
    return "UNCLEAR_needs_claude"

wgs_catalog["classification"] = wgs_catalog.apply(classify_study, axis=1)

print(wgs_catalog["classification"].value_counts())

classification
YES_regex               663
UNCLEAR_needs_claude    209
NO_regex                 45
Name: count, dtype: int64

In [26]:
# save confirmed studies
confirmed = wgs_catalog[wgs_catalog["classification"] == "YES_regex"].copy()
confirmed.to_csv("../results/confirmed_metagenome.tsv", sep="\t", index=False)
print(f"Confirmed metagenome studies: {len(confirmed)}")
print(f"Total samples: {confirmed['n_samples'].sum()}")

Confirmed metagenome studies: 663
Total samples: 74220

In [27]:
# add classification method
wgs_catalog["classification_method"] = wgs_catalog["classification"].map({
    "YES_regex": "regex",
    "NO_regex": "regex", 
    "UNCLEAR_needs_claude": "pending_claude"
})

In [28]:
unclear = wgs_catalog[wgs_catalog["classification"] == "UNCLEAR_needs_claude"].copy()
unclear_rows = unclear.to_dict("records")

counter = [0]
lock = threading.Lock()

def verify_unclear(row):
    with lock:
        counter[0] += 1
        if counter[0] % 20 == 0:
            print(f"Progress: {counter[0]}/209")
    
    study_accession = row["study_accession"]
    title = row.get("title") if isinstance(row.get("title"), str) else "Not available"
    abstract = row.get("abstract") if isinstance(row.get("abstract"), str) else "Not available"
    
    prompt = f"""Title: {title}
Abstract: {abstract[:300] if isinstance(abstract, str) else "Not available"}

Is this a shotgun metagenomics study of animal gut/intestinal microbiome?
Answer YES, NO, or UNCLEAR only."""

    try:
        message = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=10,
            system="Answer YES, NO, or UNCLEAR only.",
            messages=[{"role": "user", "content": prompt}]
        )
        return study_accession, message.content[0].text.strip()
    except Exception as e:
        return study_accession, "ERROR"

with ThreadPoolExecutor(max_workers=10) as executor:
    results = list(executor.map(verify_unclear, unclear_rows))

unclear_verification = {acc: verdict for acc, verdict in results}
print(f"\nDone. Results:")
print(pd.Series(list(unclear_verification.values())).value_counts())

KeyboardInterrupt:

In [29]:
import pandas as pd

# load postdoc's 652 studies
postdoc_df = pd.read_csv("../data/animal_gut_shotgun_studies - Studies.csv")
print(f"Postdoc studies: {len(postdoc_df)}")
print(f"Columns: {list(postdoc_df.columns)}")

# check how many have ENA accessions already
has_accessions = postdoc_df["Accessions (extracted)"].notna() & (postdoc_df["Accessions (extracted)"] != "")
print(f"Studies with accessions already: {has_accessions.sum()}")

Postdoc studies: 652
Columns: ['PMID', 'PubMed Link', 'PMCID', 'PMC Link', 'DOI', 'DOI Link', 'Year', 'Journal', 'Title', 'First Author', 'Last Author', 'Primary Class', 'Host (common, detected)', 'Host Class(es) detected', 'Binomials (heuristic)', 'Accessions (extracted)', 'PubTypes', 'Abstract', 'MeSH terms', 'Reviewed?', 'Include?', 'Notes (manual)']
Studies with accessions already: 18

In [30]:
# save PMIDs for Alan's tool
pmids = postdoc_df["PMID"].dropna().astype(int).astype(str).tolist()
print(f"Total PMIDs: {len(pmids)}")

with open("../results/postdoc_pmids.txt", "w") as f:
    for pmid in pmids:
        f.write(pmid + "\n")

print("Saved to postdoc_pmids.txt")

Total PMIDs: 652
Saved to postdoc_pmids.txt

In [31]:
# check overlap with your earlier PubMed search
your_pmids = set(all_mmc["pmid"].astype(str).tolist())
postdoc_pmids = set(postdoc_df["PMID"].dropna().astype(int).astype(str).tolist())

overlap = your_pmids & postdoc_pmids
print(f"Your PubMed search: {len(your_pmids)} papers")
print(f"Postdoc's search: {len(postdoc_pmids)} papers")
print(f"Overlap: {len(overlap)} papers in both")
print(f"New in postdoc's search: {len(postdoc_pmids - your_pmids)} papers")

Your PubMed search: 1843 papers
Postdoc's search: 652 papers
Overlap: 325 papers in both
New in postdoc's search: 327 papers

In [32]:
import re

# load Alan's results for postdoc's papers
mmc_postdoc = pd.read_csv("../results/pmid-ena-results-2026-05-26(sam's).csv")  

# extract all project accessions
postdoc_accessions = []
for _, row in mmc_postdoc[mmc_postdoc["accessions"].notna()].iterrows():
    for acc in str(row["accessions"]).split(";"):
        acc = acc.strip()
        if re.match(r'PRJ[ENDB][A-Z]\d+', acc):
            postdoc_accessions.append(acc)

postdoc_accessions = list(set(postdoc_accessions))
print(f"Total project accessions from postdoc search: {len(postdoc_accessions)}")

# find new ones not already in your catalog
existing = set(all_accessions_list)
new_from_postdoc = [a for a in postdoc_accessions if a not in existing]
print(f"Already in catalog: {len(postdoc_accessions) - len(new_from_postdoc)}")
print(f"New accessions to add: {len(new_from_postdoc)}")

Total project accessions from postdoc search: 399
Already in catalog: 230
New accessions to add: 169

In [33]:
new_results_postdoc = []

for i, study in enumerate(new_from_postdoc):
    if i % 20 == 0:
        print(f"Progress: {i}/{len(new_from_postdoc)}")
    
    runs_df = fetch_runs_for_study(study)
    if runs_df is None or len(runs_df) == 0:
        continue
    
    new_results_postdoc.append({
        "study_accession": study,
        "host_species": resolve_host_species(runs_df),
        "host_tax_id": runs_df["host_tax_id"].dropna().mode()[0] if len(runs_df["host_tax_id"].dropna()) > 0 else None,
        "body_site": runs_df["host_body_site"].dropna().mode()[0] if len(runs_df["host_body_site"].dropna()) > 0 else "",
        "country": runs_df["country"].dropna().mode()[0] if len(runs_df["country"].dropna()) > 0 else "",
        "n_samples": runs_df["sample_accession"].nunique(),
        "library_strategy": runs_df["library_strategy"].dropna().mode()[0] if len(runs_df["library_strategy"].dropna()) > 0 else None,
        "data_source": "pubmed_postdoc",
        "pmid": mmc_postdoc[mmc_postdoc["accessions"].str.contains(study, na=False)]["pmid"].iloc[0] if len(mmc_postdoc[mmc_postdoc["accessions"].str.contains(study, na=False)]) > 0 else None
    })
    time.sleep(0.3)

print(f"\nFetched {len(new_results_postdoc)} new studies")

Progress: 0/169
No runs found for PRJNA1358044
Progress: 20/169
No runs found for PRJNA864640
No runs found for PRJNA261082
Progress: 40/169
No runs found for PRJNA1277365
Progress: 60/169
No runs found for PRJNA648267
No runs found for PRJNA983434
No runs found for PRJNA546576
No runs found for PRJNA1250387
No runs found for PRJNA1010509
Progress: 80/169
No runs found for PRJNA1247262
No runs found for PRJNA1024450
No runs found for PRJNA556087
Progress: 100/169
No runs found for PRJNA1024074
No runs found for PRJNA1022859
No runs found for PRJNA1010808
No runs found for PRJNA1038784
Progress: 120/169
No runs found for PRJNA1185452
No runs found for PRJNA1185451
No runs found for PRJNA662678
No runs found for PRJDB7102
No runs found for PRJNA1085270
No runs found for PRJNA1024099
No runs found for PRJNA1052115
Progress: 140/169
Progress: 160/169
No runs found for PRJEB70999

Fetched 145 new studies

In [34]:
# load existing catalog
catalog_raw = pd.read_csv("../results/catalog_raw.tsv", sep="\t")

# add new studies from postdoc search
new_df = pd.DataFrame(new_results_postdoc)

# combine and deduplicate
final_catalog = pd.concat([catalog_raw, new_df], ignore_index=True)
final_catalog = final_catalog.drop_duplicates(subset=["study_accession"])

print(f"Previous catalog: {len(catalog_raw)}")
print(f"New studies added: {len(new_df)}")
print(f"Final catalog: {len(final_catalog)}")
print(f"Total samples: {final_catalog['n_samples'].sum()}")

Previous catalog: 1390
New studies added: 145
Final catalog: 1535
Total samples: 185322

In [35]:
# merge postdoc's rich metadata into your catalog
postdoc_clean = postdoc_df[[
    "PMID", "Title", "First Author", "Last Author", 
    "Primary Class", "Abstract", "Year", "Journal"
]].rename(columns={
    "PMID": "pmid_str",
    "Title": "paper_title",
    "First Author": "first_author",
    "Last Author": "last_author",
    "Primary Class": "host_class_postdoc",
    "Abstract": "abstract_postdoc",
    "Year": "pub_year",
    "Journal": "journal"
})

# convert pmid to string for matching
postdoc_clean["pmid_str"] = postdoc_clean["pmid_str"].astype(str)
final_catalog["pmid_str"] = final_catalog["pmid"].astype(str)

# merge
final_catalog = final_catalog.merge(postdoc_clean, on="pmid_str", how="left")

print(f"Studies with postdoc metadata: {final_catalog['host_class_postdoc'].notna().sum()}")
print(f"Studies with abstract: {final_catalog['abstract_postdoc'].notna().sum()}")

# save
final_catalog.to_csv("../results/final_catalog.tsv", sep="\t", index=False)
print(f"\nSaved {len(final_catalog)} studies to final_catalog.tsv")

Studies with postdoc metadata: 0
Studies with abstract: 0

Saved 1535 studies to final_catalog.tsv

In [36]:
# check what pmid looks like in both dataframes
print("Your catalog pmid sample:")
print(final_catalog["pmid"].dropna().head(5).tolist())
print(type(final_catalog["pmid"].dropna().iloc[0]))

print("\nPostdoc pmid sample:")
print(postdoc_df["PMID"].dropna().head(5).tolist())
print(type(postdoc_df["PMID"].dropna().iloc[0]))

Your catalog pmid sample:
[28951889.0, 31959971.0, 33824199.0, 32600361.0, 32723789.0]
<class 'numpy.float64'>

Postdoc pmid sample:
[42083207, 42066496, 42059394, 42039826, 41994282]
<class 'numpy.int64'>

In [37]:
# fix pmid format in both dataframes
final_catalog["pmid_str"] = final_catalog["pmid"].dropna().apply(lambda x: str(int(x))).reindex(final_catalog.index)
postdoc_clean["pmid_str"] = postdoc_df["PMID"].astype(str)

# merge again
final_catalog = final_catalog.drop(columns=["pmid_str"], errors="ignore")
final_catalog["pmid_str"] = final_catalog["pmid"].apply(lambda x: str(int(x)) if pd.notna(x) else None)

final_catalog = final_catalog.merge(postdoc_clean, on="pmid_str", how="left")

print(f"Studies with postdoc metadata: {final_catalog['host_class_postdoc'].notna().sum()}")
print(f"Studies with abstract: {final_catalog['abstract_postdoc'].notna().sum()}")

final_catalog.to_csv("../results/final_catalog.tsv", sep="\t", index=False)
print(f"Saved {len(final_catalog)} studies")

KeyError: 'host_class_postdoc'

In [38]:
print(final_catalog.columns.tolist())

['study_accession', 'host_species', 'host_tax_id', 'body_site', 'country', 'n_samples', 'library_strategy', 'data_source', 'pmid', 'paper_title_x', 'first_author_x', 'last_author_x', 'host_class_postdoc_x', 'abstract_postdoc_x', 'pub_year_x', 'journal_x', 'pmid_str', 'paper_title_y', 'first_author_y', 'last_author_y', 'host_class_postdoc_y', 'abstract_postdoc_y', 'pub_year_y', 'journal_y']

In [39]:
# drop duplicate columns and keep the good ones
final_catalog = final_catalog.drop(columns=[
    "paper_title_x", "first_author_x", "last_author_x",
    "host_class_postdoc_x", "abstract_postdoc_x", "pub_year_x", "journal_x"
])

# rename _y columns to clean names
final_catalog = final_catalog.rename(columns={
    "paper_title_y": "paper_title",
    "first_author_y": "first_author",
    "last_author_y": "last_author",
    "host_class_postdoc_y": "host_class",
    "abstract_postdoc_y": "abstract",
    "pub_year_y": "pub_year",
    "journal_y": "journal"
})

print(f"Studies with host class: {final_catalog['host_class'].notna().sum()}")
print(f"Studies with abstract: {final_catalog['abstract'].notna().sum()}")
print(f"Studies with title: {final_catalog['paper_title'].notna().sum()}")

final_catalog.to_csv("../results/final_catalog.tsv", sep="\t", index=False)
print(f"\nSaved {len(final_catalog)} studies")

Studies with host class: 310
Studies with abstract: 321
Studies with title: 321

Saved 1535 studies

In [40]:
# final summary
print(f"Total studies: {len(final_catalog)}")
print(f"Total samples: {final_catalog['n_samples'].sum()}")
print(f"With abstract: {final_catalog['abstract'].notna().sum()}")
print(f"With host class: {final_catalog['host_class'].notna().sum()}")
print(f"With host species: {final_catalog['host_species'].notna().sum()}")
print(f"\nData sources:")
print(final_catalog['data_source'].value_counts())

Total studies: 1535
Total samples: 185322
With abstract: 321
With host class: 310
With host species: 1352

Data sources:
data_source
pubmed            779
ena_only          611
pubmed_postdoc    145
Name: count, dtype: int64

In [41]:
def classify_study(row):
    title = str(row.get("paper_title") or row.get("title") or "").lower()
    abstract = str(row.get("abstract") or "").lower()
    text = title + " " + abstract
    
    no_terms = [
        "genome sequence", "whole genome sequencing", "draft genome",
        "chromosome", "transcriptome", "rna-seq", "gene expression",
        "genome assembly", "reference genome", "resequencing",
        "snp", "qtl", "gwas", "population genetics"
    ]
    
    yes_terms = [
        "microbiome", "microbiota", "metagenome", "metagenomics",
        "gut bacteria", "gut flora", "intestinal bacteria", "fecal bacteria",
        "16s", "shotgun metagenomics", "whole metagenome"
    ]
    
    if any(term in text for term in no_terms):
        return "NO"
    if any(term in text for term in yes_terms):
        return "YES"
    return "UNCLEAR"

final_catalog["classification"] = final_catalog.apply(classify_study, axis=1)

print(final_catalog["classification"].value_counts())
print(f"\nYES samples: {final_catalog[final_catalog['classification']=='YES']['n_samples'].sum()}")
print(f"Total samples if keep YES+UNCLEAR: {final_catalog[final_catalog['classification']!='NO']['n_samples'].sum()}")

classification
UNCLEAR    1215
YES         266
NO           54
Name: count, dtype: int64

YES samples: 26364
Total samples if keep YES+UNCLEAR: 179287

In [42]:
unclear = final_catalog[final_catalog["classification"] == "UNCLEAR"]

print(f"UNCLEAR studies: {len(unclear)}")
print(f"\nData sources of UNCLEAR:")
print(unclear["data_source"].value_counts())

print(f"\nSample titles of UNCLEAR:")
print(unclear["paper_title"].dropna().head(10).tolist())

print(f"\nHost species in UNCLEAR:")
print(unclear["host_species"].value_counts().head(15))

UNCLEAR studies: 1215

Data sources of UNCLEAR:
data_source
ena_only          611
pubmed            603
pubmed_postdoc      1
Name: count, dtype: int64

Sample titles of UNCLEAR:
['Characterization and Preliminary Application of a Novel Lytic Vibrio parahaemolyticus Bacteriophage vB_VpaP_SJSY21.']

Host species in UNCLEAR:
host_species
Homo sapiens              193
Mus musculus              133
Sus scrofa                 78
Gallus gallus              75
feces metagenome           37
Sus scrofa domesticus      28
mouse                      24
Bos taurus                 23
Canis lupus familiaris     17
fish gut metagenome        15
pig gut metagenome         14
missing                    14
chicken gut metagenome     13
Rattus norvegicus          12
Ovis aries                  7
Name: count, dtype: int64

In [43]:
unclear_pubmed = unclear[unclear["data_source"].isin(["pubmed", "pubmed_postdoc"])]

# show studies that have abstracts but are still UNCLEAR
has_abstract = unclear_pubmed[unclear_pubmed["abstract"].notna()]
print(f"UNCLEAR pubmed studies WITH abstracts: {len(has_abstract)}")
print(f"UNCLEAR pubmed studies WITHOUT abstracts: {len(unclear_pubmed) - len(has_abstract)}")

# show a few abstracts to understand why they're unclear
for i, row in has_abstract.head(3).iterrows():
    print(f"\n--- {row['study_accession']} ---")
    print(f"Title: {row.get('paper_title', 'None')}")
    print(f"Abstract snippet: {str(row['abstract'])[:300]}")

UNCLEAR pubmed studies WITH abstracts: 1
UNCLEAR pubmed studies WITHOUT abstracts: 603

--- PRJNA1025901 ---
Title: Characterization and Preliminary Application of a Novel Lytic Vibrio parahaemolyticus Bacteriophage vB_VpaP_SJSY21.
Abstract snippet: Litopenaeus vannamei is one of the most economically significant aquatic species globally. However, the emergence of acute hepatopancreatic necrosis disease (AHPND) in recent years has resulted in substantial losses within the L. vannamei farming industry. Phage therapy holds promise as an effective

In [44]:
# get pmids for unclear pubmed studies without abstracts
unclear_no_abstract = unclear_pubmed[unclear_pubmed["abstract"].isna()]
pmids_to_fetch = unclear_no_abstract["pmid"].dropna().apply(
    lambda x: str(int(x)) if pd.notna(x) else None
).dropna().tolist()

print(f"PMIDs to fetch abstracts for: {len(pmids_to_fetch)}")

PMIDs to fetch abstracts for: 603

In [45]:
from concurrent.futures import ThreadPoolExecutor

def fetch_abstract_safe(pmid):
    try:
        abstract = fetch_abstract_from_pmid(pmid)
        time.sleep(0.1)
        return pmid, abstract
    except Exception as e:
        return pmid, None

print("Fetching abstracts for 603 UNCLEAR PubMed studies...")

with ThreadPoolExecutor(max_workers=10) as executor:
    results = list(executor.map(fetch_abstract_safe, pmids_to_fetch))

new_abstracts = {pmid: abstract for pmid, abstract in results}
found = sum(1 for a in new_abstracts.values() if a)
print(f"Abstracts found: {found}/603")

Fetching abstracts for 603 UNCLEAR PubMed studies...
No abstract found for PubMed ID 29511208: HTTP Error 429: Too Many Requests
No abstract found for PubMed ID 42019469: HTTP Error 429: Too Many Requests
No abstract found for PubMed ID 33912174: HTTP Error 429: Too Many Requests
No abstract found for PubMed ID 36389176: HTTP Error 429: Too Many Requests
No abstract found for PubMed ID 36759753: HTTP Error 429: Too Many Requests
No abstract found for PubMed ID 35440042: HTTP Error 429: Too Many Requests
No abstract found for PubMed ID 41928361: HTTP Error 429: Too Many Requests
No abstract found for PubMed ID 38882494: HTTP Error 429: Too Many Requests
No abstract found for PubMed ID 38349151: HTTP Error 429: Too Many Requests
No abstract found for PubMed ID 35002754: HTTP Error 429: Too Many Requests
No abstract found for PubMed ID 39269772: HTTP Error 429: Too Many Requests
No abstract found for PubMed ID 40671160: HTTP Error 429: Too Many Requests
No abstract found for PubMed ID 38441977: HTTP Error 429: Too Many Requests
No abstract found for PubMed ID 38229330: HTTP Error 429: Too Many Requests
No abstract found for PubMed ID 30698687: HTTP Error 429: Too Many Requests
No abstract found for PubMed ID 39947133: HTTP Error 429: Too Many Requests

KeyboardInterrupt:

In [3]:
import sys
import os
sys.path.insert(0, os.path.abspath(".."))

import json
import pandas as pd
import requests
import time
import re
from concurrent.futures import ThreadPoolExecutor

from src.ena_fetcher import (
    search_ena_studies,
    fetch_runs_for_study,
    resolve_host_species,
    fetch_study_origin,
    fetch_abstract_from_pmid
)
from src.fetcher import configure_entrez

configure_entrez()

# reload catalog
final_catalog = pd.read_csv("../results/final_catalog.tsv", sep="\t")

# reload accessions
with open("../results/all_accessions.json") as f:
    all_accessions = json.load(f)

# reload pmid mapping
with open("../results/acc_to_pmid.json") as f:
    acc_to_pmid = json.load(f)

# reload MMC batch files
mmc_batch1 = pd.read_csv("../results/pmid-ena-results-2026-05-18-batch1.csv")
mmc_batch2 = pd.read_csv("../results/pmid-ena-results-2026-05-19-batch2.csv")
mmc_batch34 = pd.read_csv("../results/pmid-ena-results-2026-05-19-batch3.csv")
mmc_postdoc = pd.read_csv("../results/pmid-ena-results-2026-05-26(sam's).csv")
all_mmc = pd.concat([mmc_batch1, mmc_batch2, mmc_batch34, mmc_postdoc], ignore_index=True)

print(f"Catalog: {len(final_catalog)} studies")
print(f"Total samples: {final_catalog['n_samples'].sum()}")
print(f"All accessions: {len(all_accessions)}")
print(f"PMID mappings: {len(acc_to_pmid)}")

Entrez configured with email: akharya@ucsd.edu
Catalog: 1535 studies
Total samples: 185322
All accessions: 1502
PMID mappings: 891

In [4]:
# get pmids for unclear pubmed studies without abstracts
def classify_study(row):
    title = str(row.get("paper_title") or "").lower()
    abstract = str(row.get("abstract") or "").lower()
    text = title + " " + abstract
    
    no_terms = [
        "genome sequence", "whole genome sequencing", "draft genome",
        "chromosome", "transcriptome", "rna-seq", "gene expression",
        "genome assembly", "reference genome", "resequencing",
        "snp", "qtl", "gwas", "population genetics"
    ]
    
    yes_terms = [
        "microbiome", "microbiota", "metagenome", "metagenomics",
        "gut bacteria", "gut flora", "intestinal bacteria", "fecal bacteria",
        "16s", "shotgun metagenomics", "whole metagenome"
    ]
    
    if any(term in text for term in no_terms):
        return "NO"
    if any(term in text for term in yes_terms):
        return "YES"
    return "UNCLEAR"

final_catalog["classification"] = final_catalog.apply(classify_study, axis=1)

# get unclear pubmed studies without abstracts
unclear = final_catalog[final_catalog["classification"] == "UNCLEAR"]
unclear_pubmed = unclear[unclear["data_source"].isin(["pubmed", "pubmed_postdoc"])]
unclear_no_abstract = unclear_pubmed[unclear_pubmed["abstract"].isna()]

pmids_to_fetch = unclear_no_abstract["pmid"].dropna().apply(
    lambda x: str(int(x)) if pd.notna(x) else None
).dropna().tolist()

print(f"PMIDs to fetch: {len(pmids_to_fetch)}")

PMIDs to fetch: 603

In [5]:
def fetch_abstract_safe(pmid):
    try:
        abstract = fetch_abstract_from_pmid(pmid)
        time.sleep(0.15)
        return pmid, abstract
    except Exception as e:
        return pmid, None

print("Fetching abstracts for 603 studies...")

with ThreadPoolExecutor(max_workers=3) as executor:
    results = list(executor.map(fetch_abstract_safe, pmids_to_fetch))

new_abstracts = {pmid: abstract for pmid, abstract in results}
found = sum(1 for a in new_abstracts.values() if a)
print(f"Abstracts found: {found}/603")

# save immediately
import json
with open("../results/new_abstracts.json", "w") as f:
    json.dump(new_abstracts, f)
print("Saved new_abstracts.json")

Fetching abstracts for 603 studies...
Abstracts found: 430/603
Saved new_abstracts.json

In [6]:
# add new abstracts to catalog
final_catalog.loc[:, "abstract"] = final_catalog.apply(
    lambda row: new_abstracts.get(str(int(row["pmid"])) if pd.notna(row["pmid"]) else None, row.get("abstract")),
    axis=1
)

# rerun classification with updated abstracts
final_catalog["classification"] = final_catalog.apply(classify_study, axis=1)

print(final_catalog["classification"].value_counts())
print(f"\nYES samples: {final_catalog[final_catalog['classification']=='YES']['n_samples'].sum()}")
print(f"NO samples: {final_catalog[final_catalog['classification']=='NO']['n_samples'].sum()}")
print(f"UNCLEAR samples: {final_catalog[final_catalog['classification']=='UNCLEAR']['n_samples'].sum()}")

classification
YES        802
UNCLEAR    614
NO         119
Name: count, dtype: int64

YES samples: 94498
NO samples: 10994
UNCLEAR samples: 79830

In [7]:
print("=== CATALOG SUMMARY ===")
print(f"\nTotal studies: {len(final_catalog)}")
print(f"Total samples: {final_catalog['n_samples'].sum():,}")

print(f"\n--- Abstracts ---")
print(f"Studies with abstract: {final_catalog['abstract'].notna().sum()}")
print(f"Studies without abstract: {final_catalog['abstract'].isna().sum()}")

print(f"\n--- Data sources ---")
print(final_catalog['data_source'].value_counts())

print(f"\n--- Classification (regex) ---")
print(final_catalog['classification'].value_counts())
print(f"\nYES studies: {(final_catalog['classification']=='YES').sum()}")
print(f"YES samples: {final_catalog[final_catalog['classification']=='YES']['n_samples'].sum():,}")
print(f"\nNO studies: {(final_catalog['classification']=='NO').sum()}")
print(f"NO samples: {final_catalog[final_catalog['classification']=='NO']['n_samples'].sum():,}")
print(f"\nUNCLEAR studies: {(final_catalog['classification']=='UNCLEAR').sum()}")
print(f"UNCLEAR samples: {final_catalog[final_catalog['classification']=='UNCLEAR']['n_samples'].sum():,}")

print(f"\n--- Host resolution ---")
print(f"Host species resolved: {final_catalog['host_species'].notna().sum()}")
print(f"Host class available: {final_catalog['host_class'].notna().sum()}")

=== CATALOG SUMMARY ===

Total studies: 1535
Total samples: 185,322

--- Abstracts ---
Studies with abstract: 924
Studies without abstract: 611

--- Data sources ---
data_source
pubmed            779
ena_only          611
pubmed_postdoc    145
Name: count, dtype: int64

--- Classification (regex) ---
classification
YES        802
UNCLEAR    614
NO         119
Name: count, dtype: int64

YES studies: 802
YES samples: 94,498

NO studies: 119
NO samples: 10,994

UNCLEAR studies: 614
UNCLEAR samples: 79,830

--- Host resolution ---
Host species resolved: 1352
Host class available: 310

In [8]:
# flag as NO but keep in catalog
final_catalog.loc[final_catalog["classification"] == "NO", "needs_review"] = True

In [10]:
print(final_catalog.columns.tolist())

['study_accession', 'host_species', 'host_tax_id', 'body_site', 'country', 'n_samples', 'library_strategy', 'data_source', 'pmid', 'pmid_str', 'paper_title', 'first_author', 'last_author', 'host_class', 'abstract', 'pub_year', 'journal', 'classification', 'needs_review']

In [11]:
runs_df = fetch_runs_for_study("PRJNA836960")
print(runs_df.columns.tolist())

['run_accession', 'study_accession', 'sample_accession', 'scientific_name', 'host', 'library_strategy', 'fastq_ftp', 'host_scientific_name', 'host_tax_id', 'host_body_site', 'disease', 'country', 'lat', 'lon', 'collection_date']

In [12]:
import importlib
import src.ena_fetcher
importlib.reload(src.ena_fetcher)
from src.ena_fetcher import fetch_runs_for_study

runs_df = fetch_runs_for_study("PRJNA836960")
print(runs_df["library_source"].value_counts())

library_source
METAGENOMIC    130
Name: count, dtype: int64

In [13]:
from concurrent.futures import ThreadPoolExecutor

def fetch_library_source(study_accession):
    try:
        runs_df = fetch_runs_for_study(study_accession)
        if runs_df is None or len(runs_df) == 0:
            return study_accession, None
        if "library_source" in runs_df.columns:
            source = runs_df["library_source"].dropna().mode()
            return study_accession, source[0] if len(source) > 0 else None
        return study_accession, None
    except Exception as e:
        return study_accession, None

print(f"Fetching library_source for {len(final_catalog)} studies...")

with ThreadPoolExecutor(max_workers=5) as executor:
    results = list(executor.map(
        fetch_library_source,
        final_catalog["study_accession"].tolist()
    ))

library_sources = {acc: src for acc, src in results}
final_catalog["library_source"] = final_catalog["study_accession"].map(library_sources)

print(final_catalog["library_source"].value_counts())

Fetching library_source for 1535 studies...
library_source
METAGENOMIC                   1272
GENOMIC                        202
TRANSCRIPTOMIC                  36
OTHER                           16
METATRANSCRIPTOMIC               4
VIRAL RNA                        2
TRANSCRIPTOMIC SINGLE CELL       1
SYNTHETIC                        1
GENOMIC SINGLE CELL              1
Name: count, dtype: int64

In [15]:
def classify_final(row):
    lib_source = str(row.get("library_source") or "")
    lib_strategy = str(row.get("library_strategy") or "")
    regex_class = str(row.get("classification") or "")
    
    # definite NO by library_source
    if lib_source in ["GENOMIC", "TRANSCRIPTOMIC", "VIRAL RNA",
                      "TRANSCRIPTOMIC SINGLE CELL", "GENOMIC SINGLE CELL", "SYNTHETIC"]:
        return "NO"
    
    # definite NO by library_strategy regardless of source
    if lib_strategy in ["AMPLICON", "RNA-Seq", "ChIP-Seq",
                        "Hi-C", "RAD-Seq", "Targeted-Capture", "CLONEEND"]:
        return "NO"
    
    # strong YES - both source AND strategy confirm metagenomics
    if lib_source == "METAGENOMIC" and lib_strategy in ["WGS", "METAGENOMIC"]:
        return "YES"
    
    # weaker signal - source says metagenomics but strategy is ambiguous
    if lib_source == "METAGENOMIC" and lib_strategy == "OTHER":
        return "MAYBE"
    
    # METATRANSCRIPTOMIC
    if lib_source == "METATRANSCRIPTOMIC":
        return "MAYBE"
    
    # fall back to regex for everything else
    return regex_class

final_catalog["classification_final"] = final_catalog.apply(classify_final, axis=1)

print(final_catalog["classification_final"].value_counts())
print(f"\nYES studies: {(final_catalog['classification_final']=='YES').sum()}")
print(f"YES samples: {final_catalog[final_catalog['classification_final']=='YES']['n_samples'].sum():,}")
print(f"NO studies: {(final_catalog['classification_final']=='NO').sum()}")
print(f"MAYBE studies: {(final_catalog['classification_final']=='MAYBE').sum()}")
print(f"UNCLEAR studies: {(final_catalog['classification_final']=='UNCLEAR').sum()}")

classification_final
YES        864
NO         631
MAYBE       37
UNCLEAR      3
Name: count, dtype: int64

YES studies: 864
YES samples: 95,765
NO studies: 631
MAYBE studies: 37
UNCLEAR studies: 3

In [16]:
no_studies = final_catalog[final_catalog["classification_final"] == "NO"]

print("NO studies breakdown:")
print(f"\nBy library_source:")
print(no_studies["library_source"].value_counts())
print(f"\nBy library_strategy:")
print(no_studies["library_strategy"].value_counts())
print(f"\nSample titles of NO studies:")
for title in no_studies["paper_title"].dropna().head(5).tolist():
    print(f"  - {title}")

NO studies breakdown:

By library_source:
library_source
METAGENOMIC                   374
GENOMIC                       202
TRANSCRIPTOMIC                 36
OTHER                          12
METATRANSCRIPTOMIC              2
VIRAL RNA                       2
TRANSCRIPTOMIC SINGLE CELL      1
SYNTHETIC                       1
GENOMIC SINGLE CELL             1
Name: count, dtype: int64

By library_strategy:
library_strategy
AMPLICON            420
WGS                 140
RNA-Seq              56
OTHER                 4
Targeted-Capture      2
RAD-Seq               2
CLONEEND              2
ChIP-Seq              2
Hi-C                  1
WGA                   1
FINISHING             1
Name: count, dtype: int64

Sample titles of NO studies:
  - Genomes of Gut Bacteria from Nasonia Wasps Shed Light on Phylosymbiosis and Microbe-Assisted Hybrid Breakdown.
  - Detection and characterization of Campylobacter in air samples from poultry houses using shot-gun metagenomics - a pilot study.
  - Metagenomic analysis reveals the microbiome and resistome in migratory birds.
  - Genetic insights into the dark matter of the mammalian gut microbiota through targeted genome reconstruction.
  - Effects of dietary zinc on the gut microbiome and resistome of the gestating cow and neonatal calf.

In [17]:
def classify_final(row):
    lib_source = str(row.get("library_source") or "")
    lib_strategy = str(row.get("library_strategy") or "")
    regex_class = str(row.get("classification") or "")
    
    # library_source is the STRONGER signal - check it first
    
    # definite NO by library_source
    if lib_source in ["GENOMIC", "TRANSCRIPTOMIC", "VIRAL RNA",
                      "TRANSCRIPTOMIC SINGLE CELL", "GENOMIC SINGLE CELL", "SYNTHETIC"]:
        return "NO"
    
    # strong YES - source confirms metagenomics + strategy confirms WGS
    if lib_source == "METAGENOMIC" and lib_strategy in ["WGS", "METAGENOMIC"]:
        return "YES"
    
    # source confirms metagenomics but strategy is ambiguous
    if lib_source == "METAGENOMIC" and lib_strategy in ["OTHER", "AMPLICON"]:
        return "MAYBE"
    
    # source is METAGENOMIC with any other strategy - still likely YES
    if lib_source == "METAGENOMIC":
        return "YES"
    
    # METATRANSCRIPTOMIC
    if lib_source == "METATRANSCRIPTOMIC":
        return "MAYBE"
    
    # now check library_strategy for remaining studies
    if lib_strategy in ["RNA-Seq", "ChIP-Seq", "Hi-C", 
                        "RAD-Seq", "Targeted-Capture", "CLONEEND"]:
        return "NO"
    
    # fall back to regex
    return regex_class

final_catalog["classification_final"] = final_catalog.apply(classify_final, axis=1)

print(final_catalog["classification_final"].value_counts())
print(f"\nYES studies: {(final_catalog['classification_final']=='YES').sum()}")
print(f"YES samples: {final_catalog[final_catalog['classification_final']=='YES']['n_samples'].sum():,}")
print(f"NO studies: {(final_catalog['classification_final']=='NO').sum()}")
print(f"MAYBE studies: {(final_catalog['classification_final']=='MAYBE').sum()}")
print(f"UNCLEAR studies: {(final_catalog['classification_final']=='UNCLEAR').sum()}")

classification_final
YES        900
MAYBE      389
NO         245
UNCLEAR      1
Name: count, dtype: int64

YES studies: 900
YES samples: 98,657
NO studies: 245
MAYBE studies: 389
UNCLEAR studies: 1

In [18]:
maybe_studies = final_catalog[final_catalog["classification_final"] == "MAYBE"]

print("MAYBE studies breakdown:")
print(f"\nBy library_source:")
print(maybe_studies["library_source"].value_counts())
print(f"\nBy library_strategy:")
print(maybe_studies["library_strategy"].value_counts())
print(f"\nSample titles:")
for title in maybe_studies["paper_title"].dropna().head(5).tolist():
    print(f"  - {title}")

MAYBE studies breakdown:

By library_source:
library_source
METAGENOMIC           385
METATRANSCRIPTOMIC      4
Name: count, dtype: int64

By library_strategy:
library_strategy
AMPLICON    352
OTHER        35
WGS           2
Name: count, dtype: int64

Sample titles:
  - The gut microbiome stability is altered by probiotic ingestion and improved by the continuous supplementation of galactooligosaccharide.
  - Genotypic characterization of gut isolates from Atlantic salmon fry reveals beneficial microbes with biotechnological potential.
  - The role of the gut microbiota in the dietary niche expansion of fishing bats.
  - Microbial Dysregulation of the Gut-Lung Axis in Bronchiectasis.
  - Methanogenic patterns in the gut microbiome are associated with survival in a population of feral horses.

In [19]:
def classify_final(row):
    lib_source = str(row.get("library_source") or "")
    lib_strategy = str(row.get("library_strategy") or "")
    regex_class = str(row.get("classification") or "")
    
    # definite NO by library_source
    if lib_source in ["GENOMIC", "TRANSCRIPTOMIC", "VIRAL RNA",
                      "TRANSCRIPTOMIC SINGLE CELL", "GENOMIC SINGLE CELL", "SYNTHETIC"]:
        return "NO"
    
    # AMPLICON = 16S = not WGS shotgun → NO for your purposes
    if lib_strategy == "AMPLICON":
        return "NO_16S"
    
    # definite NO by library_strategy
    if lib_strategy in ["RNA-Seq", "ChIP-Seq", "Hi-C",
                        "RAD-Seq", "Targeted-Capture", "CLONEEND"]:
        return "NO"
    
    # strong YES - source METAGENOMIC + strategy WGS or METAGENOMIC
    if lib_source == "METAGENOMIC" and lib_strategy in ["WGS", "METAGENOMIC"]:
        return "YES"
    
    # source METAGENOMIC but strategy OTHER - ambiguous
    if lib_source == "METAGENOMIC" and lib_strategy == "OTHER":
        return "MAYBE"
    
    # source METAGENOMIC with no strategy info
    if lib_source == "METAGENOMIC":
        return "YES"
    
    # METATRANSCRIPTOMIC
    if lib_source == "METATRANSCRIPTOMIC":
        return "MAYBE"
    
    # fall back to regex
    return regex_class

final_catalog["classification_final"] = final_catalog.apply(classify_final, axis=1)

print(final_catalog["classification_final"].value_counts())
print(f"\nYES studies: {(final_catalog['classification_final']=='YES').sum()}")
print(f"YES samples: {final_catalog[final_catalog['classification_final']=='YES']['n_samples'].sum():,}")

classification_final
YES       867
NO_16S    363
NO        268
MAYBE      37
Name: count, dtype: int64

YES studies: 867
YES samples: 96,872

In [20]:
# save final classified catalog
final_catalog.to_csv("../results/final_catalog.tsv", sep="\t", index=False)

# save clean YES-only catalog
yes_catalog = final_catalog[final_catalog["classification_final"] == "YES"].copy()
yes_catalog.to_csv("../results/yes_catalog.tsv", sep="\t", index=False)

print(f"Full catalog saved: {len(final_catalog)} studies")
print(f"YES catalog saved: {len(yes_catalog)} studies, {yes_catalog['n_samples'].sum():,} samples")

Full catalog saved: 1535 studies
YES catalog saved: 867 studies, 96,872 samples

In [22]:
import importlib
import src.ena_fetcher
importlib.reload(src.ena_fetcher)

from src.ena_fetcher import get_taxonomy
tax = get_taxonomy("8404")
print(tax)

Error fetching taxonomy for tax_id 8404: 0
{'kingdom': None, 'phylum': None, 'class': None, 'order': None, 'family': None, 'genus': None, 'species': None}

In [23]:
# test directly without the function
from Bio import Entrez

handle = Entrez.efetch(
    db="taxonomy",
    id="8404",
    retmode="xml"
)
records = Entrez.read(handle)
handle.close()

print(f"Records found: {len(records)}")
print(f"Scientific name: {records[0].get('ScientificName')}")
print(f"Lineage keys: {list(records[0].keys())}")

Records found: 1
Scientific name: Lithobates pipiens
Lineage keys: ['TaxId', 'ScientificName', 'OtherNames', 'ParentTaxId', 'Rank', 'Division', 'GeneticCode', 'MitoGeneticCode', 'Lineage', 'LineageEx', 'CreateDate', 'UpdateDate', 'PubDate']

In [24]:
# debug the function
tax_id = "8404"
print(f"Input: {tax_id}, type: {type(tax_id)}")
print(f"Converted: {str(int(float(tax_id)))}")

Input: 8404, type: <class 'str'>
Converted: 8404

In [25]:
def get_taxonomy(tax_id):
    if tax_id is None or str(tax_id) == "nan":
        return {"kingdom": None, "phylum": None, "class": None, 
                "order": None, "family": None, "genus": None, "species": None}
    
    try:
        converted_id = str(int(float(tax_id)))
        print(f"Fetching taxonomy for converted id: {converted_id}")
        
        handle = Entrez.efetch(
            db="taxonomy",
            id=converted_id,
            retmode="xml"
        )
        records = Entrez.read(handle)
        handle.close()
        time.sleep(0.3)
        
        taxonomy = {"kingdom": None, "phylum": None, "class": None,
                   "order": None, "family": None, "genus": None, "species": None}
        
        if records:
            taxonomy["species"] = records[0].get("ScientificName")
            lineage = records[0].get("LineageEx", [])
            for node in lineage:
                rank = node.get("Rank")
                name = node.get("ScientificName")
                if rank in taxonomy:
                    taxonomy[rank] = name
        
        return taxonomy
        
    except Exception as e:
        print(f"Error fetching taxonomy for {tax_id}: {e}")
        print(f"Error type: {type(e)}")
        return {"kingdom": None, "phylum": None, "class": None,
                "order": None, "family": None, "genus": None, "species": None}

In [26]:
get_taxonomy(8404)

Fetching taxonomy for converted id: 8404

{'kingdom': 'Metazoa',
 'phylum': 'Chordata',
 'class': 'Amphibia',
 'order': 'Anura',
 'family': 'Ranidae',
 'genus': 'Lithobates',
 'species': 'Lithobates pipiens'}

In [28]:
import importlib
import src.ena_fetcher
importlib.reload(src.ena_fetcher)

from src.ena_fetcher import get_taxonomy
tax = get_taxonomy("8404")
print(tax)

Error fetching taxonomy for tax_id 8404: 0
{'kingdom': None, 'phylum': None, 'class': None, 'order': None, 'family': None, 'genus': None, 'species': None}

In [29]:
import importlib
import src.ena_fetcher
importlib.reload(src.ena_fetcher)

# check if function exists in module
print(dir(src.ena_fetcher))
print("\nget_taxonomy in module:", hasattr(src.ena_fetcher, 'get_taxonomy'))

['ENA_PORTAL_URL', 'Entrez', 'GENERIC_SCIENTIFIC_NAMES', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'fetch_abstract_from_pmid', 'fetch_pubmed_abstract', 'fetch_pubmed_abstract_by_title', 'fetch_pubmed_id', 'fetch_runs_for_study', 'fetch_study_origin', 'get_taxonomy', 'pd', 'requests', 'resolve_host_species', 'search_ena_studies', 'time']

get_taxonomy in module: True

In [30]:
result = src.ena_fetcher.get_taxonomy("8404")
print(result)

Error fetching taxonomy for tax_id 8404: 0
{'kingdom': None, 'phylum': None, 'class': None, 'order': None, 'family': None, 'genus': None, 'species': None}

In [32]:
from src.fetcher import configure_entrez
configure_entrez()

result = src.ena_fetcher.get_taxonomy("8404")
print(result)

Entrez configured with email: akharya@ucsd.edu
Error fetching taxonomy for tax_id 8404: 0
{'kingdom': None, 'phylum': None, 'class': None, 'order': None, 'family': None, 'genus': None, 'species': None}

In [33]:
import importlib
import src.ena_fetcher
importlib.reload(src.ena_fetcher)

from src.ena_fetcher import get_taxonomy
tax = get_taxonomy("8404")
print(tax)

{'kingdom': 'Metazoa', 'phylum': 'Chordata', 'class': 'Amphibia', 'order': 'Anura', 'family': 'Ranidae', 'genus': 'Lithobates', 'species': 'Lithobates pipiens'}

In [ ]:
from concurrent.futures import ThreadPoolExecutor

def get_taxonomy_safe(row):
    tax_id = row.get("host_tax_id")
    if pd.isna(tax_id) if pd.notna(tax_id) else True:
        return row["study_accession"], {"kingdom": None, "phylum": None, "class": None,
                                        "order": None, "family": None, "genus": None, "species": None}
    try:
        taxonomy = get_taxonomy(str(tax_id))
        return row["study_accession"], taxonomy
    except Exception as e:
        return row["study_accession"], {"kingdom": None, "phylum": None, "class": None,
                                        "order": None, "family": None, "genus": None, "species": None}

yes_catalog = final_catalog[final_catalog["classification_final"] == "YES"].copy()
rows = yes_catalog.to_dict("records")

print(f"Fetching taxonomy for {len(yes_catalog)} studies...")

with ThreadPoolExecutor(max_workers=3) as executor:
    results = list(executor.map(get_taxonomy_safe, rows))

taxonomy_data = {acc: tax for acc, tax in results}

yes_catalog["host_kingdom"] = yes_catalog["study_accession"].map(lambda x: taxonomy_data.get(x, {}).get("kingdom"))
yes_catalog["host_phylum"] = yes_catalog["study_accession"].map(lambda x: taxonomy_data.get(x, {}).get("phylum"))
yes_catalog["host_class"] = yes_catalog["study_accession"].map(lambda x: taxonomy_data.get(x, {}).get("class"))
yes_catalog["host_order"] = yes_catalog["study_accession"].map(lambda x: taxonomy_data.get(x, {}).get("order"))
yes_catalog["host_family"] = yes_catalog["study_accession"].map(lambda x: taxonomy_data.get(x, {}).get("family"))
yes_catalog["host_genus"] = yes_catalog["study_accession"].map(lambda x: taxonomy_data.get(x, {}).get("genus"))
yes_catalog["host_species_taxonomy"] = yes_catalog["study_accession"].map(lambda x: taxonomy_data.get(x, {}).get("species"))

print(f"\nHost class populated: {yes_catalog['host_class'].notna().sum()}/{len(yes_catalog)}")
print(f"\nTop host classes:")
print(yes_catalog["host_class"].value_counts().head(10))

Fetching taxonomy for 867 studies...

Host class populated: 464/867

Top host classes:
host_class
Mammalia          346
Aves               57
Actinopteri        32
Insecta            19
Chondrichthyes      3
Magnoliopsida       2
Malacostraca        1
Amphibia            1
Lepidosauria        1
Arachnida           1
Name: count, dtype: int64

In [35]:
yes_catalog.to_csv("../results/yes_catalog.tsv", sep="\t", index=False)
print(f"Saved {len(yes_catalog)} studies")
print(f"Columns: {list(yes_catalog.columns)}")

Saved 867 studies
Columns: ['study_accession', 'host_species', 'host_tax_id', 'body_site', 'country', 'n_samples', 'library_strategy', 'data_source', 'pmid', 'pmid_str', 'paper_title', 'first_author', 'last_author', 'host_class', 'abstract', 'pub_year', 'journal', 'classification', 'needs_review', 'library_source', 'classification_final', 'host_kingdom', 'host_phylum', 'host_order', 'host_family', 'host_genus', 'host_species_taxonomy']

In [36]:
missing_class = yes_catalog[
    yes_catalog["host_class"].isna() & 
    yes_catalog["abstract"].notna()
]

print(f"Missing host class but have abstract: {len(missing_class)}")
print(f"Missing host class AND no abstract: {yes_catalog[yes_catalog['host_class'].isna() & yes_catalog['abstract'].isna()].shape[0]}")

Missing host class but have abstract: 171
Missing host class AND no abstract: 232

In [38]:
def enrich_taxonomy_from_abstract(row):
    study_accession = row["study_accession"]
    title = str(row.get("paper_title") or "")
    abstract = str(row.get("abstract") or "")
    host_species = str(row.get("host_species") or "")
    
    prompt = f"""Given this study information, identify the host animal's taxonomy.

Title: {title}
Abstract: {abstract[:500]}
Known host species from metadata: {host_species}

Return ONLY a JSON object with these exact keys:
{{"kingdom": "...", "phylum": "...", "class": "...", "order": "...", "family": "...", "genus": "...", "species": "..."}}

If you cannot determine a field, use null. If this is not an animal study return null for all fields."""

    try:
        message = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=150,
            system="You are a taxonomist. Return only valid JSON, no explanation.",
            messages=[{"role": "user", "content": prompt}]
        )
        # strip markdown code blocks if present
        text = message.content[0].text.strip()
        text = text.replace("```json", "").replace("```", "").strip()
        result = json.loads(text)
        return study_accession, result
    except Exception as e:
        print(f"Error for {study_accession}: {e}")
        return study_accession, None

In [39]:
test_row = missing_class.iloc[0].to_dict()
acc, tax = enrich_taxonomy_from_abstract(test_row)
print(f"Accession: {acc}")
print(f"Taxonomy: {tax}")

Error for PRJNA1211805: name 'client' is not defined
Accession: PRJNA1211805
Taxonomy: None

In [40]:
import anthropic
client = anthropic.Anthropic()

In [41]:
test_row = missing_class.iloc[0].to_dict()
acc, tax = enrich_taxonomy_from_abstract(test_row)
print(f"Accession: {acc}")
print(f"Taxonomy: {tax}")

Accession: PRJNA1211805
Taxonomy: {'kingdom': 'Animalia', 'phylum': 'Chordata', 'class': 'Mammalia', 'order': 'Artiodactyla', 'family': 'Suidae', 'genus': 'Sus', 'species': 'Sus scrofa domesticus'}

In [42]:
rows = missing_class.to_dict("records")
print(f"Enriching {len(rows)} studies with Claude...")

with ThreadPoolExecutor(max_workers=5) as executor:
    results = list(executor.map(enrich_taxonomy_from_abstract, rows))

enriched = {acc: tax for acc, tax in results if tax is not None}
print(f"Successfully enriched: {len(enriched)}/{len(rows)}")

for acc, tax in enriched.items():
    for rank in ["kingdom", "phylum", "class", "order", "family", "genus", "species"]:
        col = f"host_{rank}" if rank != "class" else "host_class"
        if rank == "species":
            col = "host_species_taxonomy"
        yes_catalog.loc[yes_catalog["study_accession"] == acc, col] = tax.get(rank)

print(f"\nHost class after enrichment: {yes_catalog['host_class'].notna().sum()}/{len(yes_catalog)}")
print(yes_catalog["host_class"].value_counts().head(10))

Enriching 171 studies with Claude...
Error for PRJEB7774: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3XX3TYB2f7kXosAgxw'}
Error for PRJEB55711: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3XXdBB5hHBG1nubvDq'}
Error for PRJEB79635: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3XXKaB9EkG5947KrJ9'}
Error for PRJEB5224: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3YYFuosYuFEHGKKtEu'}
Error for PRJNA721002: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3ZM9T6wMk8W6nVgj3K'}
Error for PRJEB14215: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3ZNVZfTRn9NTyQyEMn'}
Error for PRJNA599288: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3aFf5RNqrrMxVmjK8r'}
Error for PRJNA542998: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3aHLHXj43mJQuS6qYW'}
Error for PRJEB33338: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3b66srghgbcf4TfR8K'}
Error for PRJNA726842: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3c18WoQ1eJ7HS8jFtd'}
Error for PRJNA847753: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3c6oKnaQvcGHZVyJU4'}
Error for PRJEB79352: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3cs8ppB7Qmkh6w8n8E'}
Error for PRJNA902000: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3dmcU8sJrSoFswQkjF'}
Error for PRJEB66719: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3dmuLV2FzZF4jxVZ5U'}
Error for PRJNA294605: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3eeD1Uuf1dLDjT9muQ'}
Error for PRJNA763692: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3fXJoR9qUa1jxDpC1Y'}
Error for PRJEB6070: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3fY1iUdh5uv442K8o9'}
Error for PRJNA1030990: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3gUGmSabyrovrhwnXo'}
Error for PRJEB27928: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3gUD3gMLoB7TuPxMDL'}
Error for PRJNA1273701: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3hKSyZ1eRydu6Noi3E'}
Error for PRJNA942468: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3i9agJoVdjwLWdPxcg'}
Error for PRJNA63661: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3iB7TF4SuqJWmMwW9a'}
Error for PRJNA1245445: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3j4VcU4s2rkBJAdZV7'}
Error for PRJNA1428229: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3jztbcVMRD5QCBoC58'}
Error for PRJNA853153: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3k28GGUXUUYjvZNWkb'}
Error for PRJEB47976: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3ksNgcYFm3DdfPjXFT'}
Error for PRJNA356809: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3mm1UioU1Utw3MpSDQ'}
Error for PRJNA1222153: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3mmeRrNDQwWCwshqGP'}
Error for PRJNA1119043: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3ndVZzWTHQr5nBv8pP'}
Error for PRJNA844237: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3oYZvtcNWt1g3AcR1f'}
Error for PRJEB51353: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': "This request would exceed your organization's rate limit of 5 requests per minute (org: 845703c4-24c5-42a8-9051-30efbac2d0b1, model: claude-haiku-4-5-20251001). For details, refer to: https://docs.claude.com/en/api/rate-limits. You can see the response headers for current usage. Try again later. View your current limits at https://console.anthropic.com/settings/limits. You may also contact sales at https://claude.com/contact-sales to discuss your options for a rate limit increase."}, 'request_id': 'req_011Cba3oagBDCY2Z9fJ5uYA9'}

KeyboardInterrupt:

In [43]:
import time

results = []
for i, row in enumerate(rows):
    if i % 5 == 0:
        print(f"Progress: {i}/{len(rows)}")
    acc, tax = enrich_taxonomy_from_abstract(row)
    results.append((acc, tax))
    time.sleep(13)  # 5 requests per minute = 1 per 12 seconds

enriched = {acc: tax for acc, tax in results if tax is not None}
print(f"Successfully enriched: {len(enriched)}/{len(rows)}")

Progress: 0/171
Progress: 5/171
Progress: 10/171
Progress: 15/171
Progress: 20/171
Progress: 25/171
Progress: 30/171
Progress: 35/171
Progress: 40/171
Progress: 45/171
Progress: 50/171
Progress: 55/171
Progress: 60/171
Progress: 65/171
Progress: 70/171
Progress: 75/171
Progress: 80/171
Progress: 85/171
Progress: 90/171
Progress: 95/171
Progress: 100/171
Progress: 105/171
Progress: 110/171
Progress: 115/171
Progress: 120/171
Progress: 125/171
Progress: 130/171
Progress: 135/171
Progress: 140/171
Progress: 145/171
Progress: 150/171
Progress: 155/171
Progress: 160/171
Progress: 165/171
Progress: 170/171
Successfully enriched: 171/171

In [44]:
for acc, tax in enriched.items():
    if tax is None:
        continue
    for rank in ["kingdom", "phylum", "order", "family", "genus"]:
        col = f"host_{rank}"
        if yes_catalog.loc[yes_catalog["study_accession"] == acc, col].isna().all():
            yes_catalog.loc[yes_catalog["study_accession"] == acc, col] = tax.get(rank)
    # class separately
    if yes_catalog.loc[yes_catalog["study_accession"] == acc, "host_class"].isna().all():
        yes_catalog.loc[yes_catalog["study_accession"] == acc, "host_class"] = tax.get("class")
    # species
    if yes_catalog.loc[yes_catalog["study_accession"] == acc, "host_species_taxonomy"].isna().all():
        yes_catalog.loc[yes_catalog["study_accession"] == acc, "host_species_taxonomy"] = tax.get("species")

print(f"Host class after enrichment: {yes_catalog['host_class'].notna().sum()}/{len(yes_catalog)}")
print(yes_catalog["host_class"].value_counts().head(10))

Host class after enrichment: 626/867
host_class
Mammalia          478
Aves               77
Actinopteri        32
Insecta            24
Actinopterygii      4
Chondrichthyes      3
Magnoliopsida       2
Malacostraca        1
Amphibia            1
Lepidosauria        1
Name: count, dtype: int64

In [45]:
yes_catalog.to_csv("../results/yes_catalog.tsv", sep="\t", index=False)
print(f"Saved {len(yes_catalog)} studies")
print(f"Host class: {yes_catalog['host_class'].notna().sum()}/{len(yes_catalog)}")
print(f"Total samples: {yes_catalog['n_samples'].sum():,}")

Saved 867 studies
Host class: 626/867
Total samples: 96,872

In [47]:
print("=" * 60)
print("ANIMAL GUT WGS METAGENOMICS CATALOG — FULL SUMMARY")
print("=" * 60)

print(f"\n📊 STUDY COUNTS")
print(f"Total studies in pipeline: {len(final_catalog)}")
print(f"Confirmed WGS metagenomics (YES): {len(yes_catalog)}")
print(f"16S studies (NO_16S): {(final_catalog['classification_final']=='NO_16S').sum()}")
print(f"Non-metagenomics (NO): {(final_catalog['classification_final']=='NO').sum()}")
print(f"Ambiguous (MAYBE): {(final_catalog['classification_final']=='MAYBE').sum()}")

print(f"\n🧬 SAMPLES")
print(f"Total samples in YES catalog: {yes_catalog['n_samples'].sum():,}")

print(f"\n📰 DATA SOURCES")
print(yes_catalog['data_source'].value_counts())

print(f"\n📄 ABSTRACTS")
print(f"Studies with abstract: {yes_catalog['abstract'].notna().sum()}")
print(f"Studies without abstract: {yes_catalog['abstract'].isna().sum()}")

print(f"\n🦎 HOST TAXONOMY")
print(f"Host class populated: {yes_catalog['host_class'].notna().sum()}/{len(yes_catalog)}")
print(f"Host species populated: {yes_catalog['host_species'].notna().sum()}/{len(yes_catalog)}")
print(f"\nHost class breakdown:")
print(yes_catalog['host_class'].value_counts().to_string())

print(f"\n🌍 GEOGRAPHY")
print(f"Studies with country: {yes_catalog['country'].notna().sum()}")
print(f"\nTop countries:")
print(yes_catalog['country'].value_counts().head(10))

print(f"\n🔬 SEQUENCING")
print(f"\nLibrary strategy:")
print(yes_catalog['library_strategy'].value_counts())
print(f"\nLibrary source:")
print(yes_catalog['library_source'].value_counts())

print(f"\n📈 VS AnimalMetagenome DB (2022)")
print(f"Their studies: 1,044")
print(f"Your studies: {len(yes_catalog)}")
print(f"Their WGS samples: 10,672")
print(f"Your samples: {yes_catalog['n_samples'].sum():,}")
print(f"Improvement: {yes_catalog}")

============================================================
ANIMAL GUT WGS METAGENOMICS CATALOG — FULL SUMMARY
============================================================

📊 STUDY COUNTS
Total studies in pipeline: 1535
Confirmed WGS metagenomics (YES): 867
16S studies (NO_16S): 363
Non-metagenomics (NO): 268
Ambiguous (MAYBE): 37

🧬 SAMPLES
Total samples in YES catalog: 96,872

📰 DATA SOURCES
data_source
ena_only          483
pubmed            313
pubmed_postdoc     71
Name: count, dtype: int64

📄 ABSTRACTS
Studies with abstract: 384
Studies without abstract: 483

🦎 HOST TAXONOMY
Host class populated: 626/867
Host species populated: 729/867

Host class breakdown:
host_class
Mammalia          478
Aves               77
Actinopteri        32
Insecta            24
Actinopterygii      4
Chondrichthyes      3
Magnoliopsida       2
Malacostraca        1
Amphibia            1
Lepidosauria        1
Arachnida           1
Gastropoda          1
Holothuroidea       1

🌍 GEOGRAPHY
Studies with country: 759

Top countries:
country
China                                           43
USA                                             37
missing: data agreement established pre-2023    25
missing                                         20
Spain                                           19
Japan                                           19
Denmark                                         18
Germany                                         18
United Kingdom                                  17
Italy                                           12
Name: count, dtype: int64

🔬 SEQUENCING

Library strategy:
library_strategy
WGS          844
WGA           19
OTHER          3
POOLCLONE      1
Name: count, dtype: int64

Library source:
library_source
METAGENOMIC    863
OTHER            4
Name: count, dtype: int64

📈 VS AnimalMetagenome DB (2022)
Their studies: 1,044
Your studies: 867
Their WGS samples: 10,672
Your samples: 96,872
Improvement:      study_accession         host_species  host_tax_id body_site  \
0        PRJNA379709         Mus musculus      10090.0       NaN
2        PRJNA806482                  RAT          NaN       NaN
6        PRJNA873123        Gallus gallus       9031.0       NaN
7          PRJDB9383         Mus musculus      10090.0       NaN
8        PRJNA947387             C57BL/6J          NaN       NaN
...              ...                  ...          ...       ...
1526     PRJNA977416       Apis mellifera       7460.0       NaN
1527    PRJNA1243555     Escherichia coli          NaN       NaN
1532     PRJNA655594             C57BL/6J          NaN       NaN
1533    PRJNA1157353          Apis cerana       7461.0       NaN
1534    PRJNA1145617  Meleagris gallopavo       9103.0       NaN

                            country  n_samples library_strategy  \
0                      USA: Arizona          8              WGS
2                       South Korea         18              WGS
6             China: Hebei,Zhuozhou         32              WGS
7                       Japan:Tokyo          8              WGS
8                           missing         27              WGS
...                             ...        ...              ...
1526               France: Beaumont         21              WGS
1527                        Ecuador         20            OTHER
1532                    Japan:Tokyo         10              WGS
1533  Malaysia: Peninsular Malaysia        200              WGS
1534                         Norway        104              WGS

         data_source        pmid    pmid_str  ... classification needs_review  \
0             pubmed  28951889.0  28951889.0  ...            YES          NaN
2           ena_only         NaN         NaN  ...        UNCLEAR          NaN
6           ena_only         NaN         NaN  ...        UNCLEAR          NaN
7           ena_only         NaN         NaN  ...        UNCLEAR          NaN
8           ena_only         NaN         NaN  ...        UNCLEAR          NaN
...              ...         ...         ...  ...            ...          ...
1526  pubmed_postdoc  38258019.0  38258019.0  ...            YES          NaN
1527  pubmed_postdoc  40576355.0  40576355.0  ...            YES          NaN
1532  pubmed_postdoc  35468931.0  35468931.0  ...             NO         True
1533  pubmed_postdoc  41083440.0  41083440.0  ...            YES          NaN
1534  pubmed_postdoc  40833800.0  40833800.0  ...            YES          NaN

     library_source classification_final host_kingdom  host_phylum  \
0       METAGENOMIC                  YES      Metazoa     Chordata
2       METAGENOMIC                  YES         None         None
6       METAGENOMIC                  YES      Metazoa     Chordata
7       METAGENOMIC                  YES      Metazoa     Chordata
8       METAGENOMIC                  YES         None         None
...             ...                  ...          ...          ...
1526    METAGENOMIC                  YES      Metazoa   Arthropoda
1527          OTHER                  YES     Animalia     Chordata
1532    METAGENOMIC                  YES     Animalia     Chordata
1533    METAGENOMIC                  YES      Metazoa   Arthropoda
1534    METAGENOMIC                  YES      Metazoa     Chordata

       host_order  host_family host_genus host_species_taxonomy
0        Rodentia      Muridae        Mus          Mus musculus
2            None         None       None                  None
6     Galliformes  Phasianidae     Gallus         Gallus gallus
7        Rodentia      Muridae        Mus          Mus musculus
8            None         None       None                  None
...           ...          ...        ...                   ...
1526  Hymenoptera       Apidae       Apis        Apis mellifera
1527  Galliformes  Phasianidae     Gallus         Gallus gallus
1532     Rodentia      Muridae        Mus              musculus
1533  Hymenoptera       Apidae       Apis           Apis cerana
1534  Galliformes  Phasianidae  Meleagris   Meleagris gallopavo

[867 rows x 27 columns]

In [2]:
import json
import pandas as pd

yes_catalog = pd.read_csv("../results/yes_catalog.tsv", sep='\t')

class_counts = yes_catalog['host_class'].value_counts().to_dict()
order_counts = yes_catalog["host_order"].value_counts().to_dict()
family_counts = yes_catalog["host_family"].value_counts().to_dict()
species_list = sorted(yes_catalog["host_species_taxonomy"].dropna().unique().tolist())

print(f"Classes represented: {len(class_counts)}")
print(f"Orders represented: {len(order_counts)}")
print(f"Families represented: {len(family_counts)}")
print(f"Distinct species: {len(species_list)}")
print(f"\nClass breakdown:\n{class_counts}")
print(f"\nOrders:\n{order_counts}")

Classes represented: 13
Orders represented: 43
Families represented: 74
Distinct species: 140

Class breakdown:
{'Mammalia': 478, 'Aves': 77, 'Actinopteri': 32, 'Insecta': 24, 'Actinopterygii': 4, 'Chondrichthyes': 3, 'Magnoliopsida': 2, 'Malacostraca': 1, 'Amphibia': 1, 'Lepidosauria': 1, 'Arachnida': 1, 'Gastropoda': 1, 'Holothuroidea': 1}

Orders:
{'Primates': 175, 'Artiodactyla': 138, 'Rodentia': 107, 'Galliformes': 61, 'Carnivora': 35, 'Hymenoptera': 13, 'Cypriniformes': 12, 'Perissodactyla': 10, 'Salmoniformes': 7, 'Lagomorpha': 6, 'Passeriformes': 6, 'Centrarchiformes': 5, 'Charadriiformes': 5, 'Orthoptera': 4, 'Blattodea': 3, 'Anseriformes': 3, 'Perciformes': 2, 'Rhinopristiformes': 2, 'Gadiformes': 2, 'Coleoptera': 2, 'Eulipotyphla': 2, 'Characiformes': 2, 'Chiroptera': 1, 'Hemiptera': 1, 'Stylommatophora': 1, 'Araneae': 1, 'Lepidoptera': 1, 'Cathartiformes': 1, 'Accipitriformes': 1, 'Diprotodontia': 1, 'Chimaeriformes': 1, 'Brassicales': 1, 'Osmeriformes': 1, 'Siluriformes': 1, 'Proboscidea': 1, 'Pholidota': 1, 'Squamata': 1, 'Anguilliformes': 1, 'Malpighiales': 1, 'Anura': 1, 'Scandentia': 1, 'Decapoda': 1, 'Aspidochirotida': 1}

In [3]:
import json
import pandas as pd

with open("../results/search_vocabulary.json") as f:
    vocab = json.load(f)
clades = vocab["clades"]

yes_catalog = pd.read_csv("../results/yes_catalog.tsv", sep="\t")

# build one lowercase searchable string per study from all host + text fields
def study_text(row):
    parts = [
        row.get("host_species"), row.get("host_species_taxonomy"),
        row.get("host_class"), row.get("host_order"),
        row.get("host_family"), row.get("host_genus"),
        row.get("paper_title"),
    ]
    return " ".join(str(p) for p in parts if pd.notna(p)).lower()

yes_catalog["_searchtext"] = yes_catalog.apply(study_text, axis=1)

def count_in_catalog(terms):
    terms_l = [t.lower() for t in terms]
    mask = yes_catalog["_searchtext"].apply(lambda txt: any(t in txt for t in terms_l))
    return int(mask.sum())

for c in clades:
    c["in_catalog"] = count_in_catalog(c["search_terms"])

# quick look
report = pd.DataFrame([{
    "clade": c["clade"], "gap_type": c["gap_type"], "in_catalog": c["in_catalog"]
} for c in clades]).sort_values("in_catalog")
print(report.to_string(index=False))

                       clade   gap_type  in_catalog
              Reptiles (all) biological           0
                  Mosquitoes     search           0
      Fruit fly (Drosophila)     search           0
                     Ratites      mixed           0
                     Parrots      mixed           0
                    Penguins      mixed           0
                  Monotremes biological           0
                   Sirenians biological           0
                 Xenarthrans biological           0
                   Nematodes     search           0
                  Cnidarians      mixed           0
                 Cephalopods biological           0
                    Bivalves      mixed           0
            Molluscs (broad) biological           0
                Jawless fish biological           0
                    Annelids biological           0
                    Flatfish biological           0
                      Snakes biological           0
       Turtles and tortoises biological           0
                  Pufferfish      mixed           0
       Salamanders and newts      mixed           0
                Crocodilians biological           0
                     Catfish      mixed           1
 Gastropods (beyond current)      mixed           1
                 Echinoderms biological           1
                        Eels      mixed           1
                  Marsupials biological           1
            Amphibians (all) biological           1
                     Beetles biological           2
                   Cetaceans biological           2
    Termites and cockroaches      mixed           3
                     Raptors biological           3
          Cartilaginous fish biological           3
          Cods and relatives      mixed           3
                        Bats      mixed           4
Crustaceans (beyond current)     search           4
       Butterflies and moths      mixed           4
                     Lizards biological           7
             Frogs and toads      mixed           7
                   Songbirds     search           9
     Ray-finned fish (broad)     search          10

In [4]:
# audit a suspicious clade: show what actually matched
def show_matches(clade_name, n=15):
    c = next(c for c in clades if c["clade"] == clade_name)
    terms_l = [t.lower() for t in c["search_terms"]]
    hits = yes_catalog[yes_catalog["_searchtext"].apply(lambda txt: any(t in txt for t in terms_l))]
    for _, r in hits.head(n).iterrows():
        matched = [t for t in terms_l if t in r["_searchtext"]]
        print(f"  {r['host_species_taxonomy'] or r['host_species']:35s} <- matched {matched}")

print("Ray-finned fish matches:")
show_matches("Ray-finned fish (broad)")
print("\nCods and relatives matches:")
show_matches("Cods and relatives")

Ray-finned fish matches:
  Cyprinus carpio                     <- matched ['carp', 'cyprinus']
  Danio rerio                         <- matched ['danio rerio']
  putitora                            <- matched ['actinopterygii']
  Danio rerio                         <- matched ['danio rerio']
  rhombeus                            <- matched ['actinopterygii']
  salar                               <- matched ['actinopterygii']
  Sus scrofa                          <- matched ['carp', 'cyprinus']
  Danio rerio                         <- matched ['danio rerio']
  Danio rerio                         <- matched ['danio rerio']
  morhua                              <- matched ['actinopterygii']

Cods and relatives matches:
  Gadus morhua                        <- matched ['cod', 'gadus', 'gadiformes']
  Homo sapiens                        <- matched ['cod']
  morhua                              <- matched ['cod', 'gadus', 'gadiformes']

In [6]:
import sys, os
sys.path.insert(0, os.path.abspath(".."))

from src.fetcher import configure_entrez
configure_entrez()

Entrez configured with email: akharya@ucsd.edu

In [ ]:
import importlib
import src.automated_query
importlib.reload(src.automated_query)
from src.automated_query import run_sweep

hits, new_df = run_sweep()

Resolving 41 target names to taxids...
  resolving 0/41
  resolving 20/41
  resolving 40/41
Resolved 41/41 names to taxids

Querying ENA for 41 unique host taxids...
  ENA query 0/41
  ENA query 10/41
  ENA query 20/41
  ENA query 30/41
  ENA query 40/41

Total unique studies found by sweep: 39

==================================================
SWEEP RESULTS vs CATALOG
==================================================
Studies found by sweep:  39
Already in catalog:      0
NEW (missed by pipeline): 39

Saved 39 new studies to sweep_new_studies.tsv

NEW studies by host organism:
host_scientific_name
Chiroptera                                 10
Culicidae                                   5
Lepidoptera                                 4
Annelida                                    3
Nematoda                                    2
Actinopterygii                              2
Amphibia                                    2
Testudines                                  2
Cnidaria                                    1
Gastropoda                                  1
Coleoptera                                  1
Anura                                       1
Homo sapiens;Cetacea                        1
Lycaenidae sp.;Papilionoidea;Lycaenidae     1

In [11]:
import importlib
import src.sweep_underrepresented2
importlib.reload(src.sweep_underrepresented2)
from src.sweep_underrepresented2 import run_sweep_v2

hits, new_df = run_sweep_v2()

TIER 1 — resolving anchors and querying ENA...
  Reptiles (all)                   anchor=Sauropsida         hits=0
  Snakes                           anchor=Serpentes          hits=0
  Lizards                          anchor=Lacertilia         hits=1
  Turtles and tortoises            anchor=Testudines         hits=2
  Crocodilians                     anchor=Crocodylia         hits=0
  Amphibians (all)                 anchor=Amphibia           hits=2
  Frogs and toads                  anchor=Anura              hits=1
  Salamanders and newts            anchor=Caudata            hits=0
  Cartilaginous fish               anchor=Chondrichthyes     hits=0
  Ray-finned fish (broad)          anchor=Actinopterygii     hits=2
  Eels                             anchor=Anguilliformes     hits=0
  Catfish                          anchor=Siluriformes       hits=0
  Cods and relatives               anchor=Gadiformes         hits=0
  Flatfish                         anchor=Pleuronectiformes  hits=0
  Pufferfish                       anchor=Tetraodontidae     hits=1
  Jawless fish                     anchor=Cyclostomata       hits=0
  Molluscs (broad)                 anchor=Mollusca           hits=1
  Bivalves                         anchor=Bivalvia           hits=0
  Cephalopods                      anchor=Cephalopoda        hits=0
  Gastropods (beyond current)      anchor=Gastropoda         hits=2
  Annelids                         anchor=Annelida           hits=4
  Echinoderms                      anchor=Echinodermata      hits=1
  Cnidarians                       anchor=Cnidaria           hits=1
  Crustaceans (beyond current)     anchor=Crustacea          hits=0
  Nematodes                        anchor=Nematoda           hits=3
  Cetaceans                        anchor=Cetacea            hits=1
  Bats                             anchor=Chiroptera         hits=10
  Marsupials                       anchor=Marsupialia        hits=0
  Xenarthrans                      anchor=Xenarthra          hits=0
  Sirenians                        anchor=Sirenia            hits=1
  Monotremes                       anchor=Monotremata        hits=0
  Penguins                         anchor=Sphenisciformes    hits=0
  Parrots                          anchor=Psittaciformes     hits=0
  Ratites                          anchor=Palaeognathae      hits=0
  Raptors                          anchor=Accipitriformes    hits=0
  Songbirds                        anchor=Passeriformes      hits=0
  Fruit fly (Drosophila)           anchor=Drosophila         hits=1
  Mosquitoes                       anchor=Culicidae          hits=5
  Termites and cockroaches         anchor=Blattodea          hits=0
  Beetles                          anchor=Coleoptera         hits=3
  Butterflies and moths            anchor=Lepidoptera        hits=5

TIER 2 — expanding 30 high-potential clades to species level...
  Lizards                          -> 30 species
  Turtles and tortoises            -> 30 species
  Amphibians (all)                 -> 30 species
  Frogs and toads                  -> 30 species
  Salamanders and newts            -> 30 species
  Ray-finned fish (broad)          -> 30 species
  Eels                             -> 30 species
  Catfish                          -> 30 species
  Cods and relatives               -> 30 species
  Pufferfish                       -> 30 species
  Molluscs (broad)                 -> 30 species
  Bivalves                         -> 30 species
  Gastropods (beyond current)      -> 30 species
  Annelids                         -> 30 species
  Echinoderms                      -> 30 species
  Cnidarians                       -> 30 species
  Crustaceans (beyond current)     -> 30 species
  Nematodes                        -> 30 species
  ENA query failed host_tax_id=3725125: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
  Cetaceans                        -> 30 species
  Bats                             -> 30 species
  Sirenians                        -> 6 species
  Penguins                         -> 26 species
  Parrots                          -> 30 species
  Ratites                          -> 30 species
  Songbirds                        -> 30 species
  Fruit fly (Drosophila)           -> 30 species
  Mosquitoes                       -> 30 species
  ENA query failed host_tax_id=3715730: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
  Termites and cockroaches         -> 30 species
  Beetles                          -> 30 species
  Butterflies and moths            -> 30 species

====================================================
TWO-TIER SWEEP RESULTS vs CATALOG
====================================================
Studies found:            66
Already in catalog:       2
NEW (missed by pipeline): 64
Saved 64 new studies to sweep_new_studies_v2.tsv

NEW studies by clade:
_clade
Penguins                       18
Bats                           11
Mosquitoes                      5
Sirenians                       4
Butterflies and moths           4
Annelids                        3
Cetaceans                       2
Beetles                         2
Amphibians (all)                2
Ray-finned fish (broad)         2
Gastropods (beyond current)     2
Nematodes                       2
Turtles and tortoises           2
Lizards                         1
Fruit fly (Drosophila)          1
Molluscs (broad)                1
Frogs and toads                 1
Termites and cockroaches        1

NEW studies by tier:
_tier
anchor     39
species    25

Top hosts among NEW:
host_scientific_name
Chiroptera                                 10
Culicidae                                   5
Lepidoptera                                 4
Pygoscelis adeliae                          3
Pygoscelis antarcticus                      3
Spheniscus magellanicus                     3
Annelida                                    3
Trichechus manatus                          3
Spheniscus demersus                         2
Testudines                                  2
Nematoda                                    2
Eudyptula minor                             2
Pygoscelis papua                            2
Actinopterygii                              2
Amphibia                                    2
Eudyptes chrysolophus                       1
Spheniscus mendiculus                       1
Lycaenidae sp.;Papilionoidea;Lycaenidae     1
Dugong dugon                                1
Murina sp.                                  1

In [12]:
import pandas as pd

new_df = pd.read_csv("../results/sweep_new_studies_v2.tsv", sep="\t")

# re-fetch with body site + sample description to judge gut vs not
import io, requests, time

def enrich_bodysite(study_acc):
    q = f'study_accession="{study_acc}"'
    params = {
        "result": "read_run",
        "query": q,
        "fields": "study_accession,host_scientific_name,host_body_site,scientific_name,sample_title,library_strategy",
        "format": "tsv", "limit": 5,
    }
    try:
        r = requests.get("https://www.ebi.ac.uk/ena/portal/api/search", params=params, timeout=60)
        if r.status_code == 200 and r.text.strip():
            return pd.read_csv(io.StringIO(r.text), sep="\t")
    except Exception as e:
        print(f"  {study_acc}: {e}")
    return pd.DataFrame()

rows = []
for acc in new_df["study_accession"].unique():
    rows.append(enrich_bodysite(acc))
    time.sleep(0.3)

detail = pd.concat([r for r in rows if len(r)], ignore_index=True)

print("host_body_site values:")
print(detail["host_body_site"].value_counts(dropna=False).to_string())
print("\nmetagenome scientific_name values:")
print(detail["scientific_name"].value_counts(dropna=False).head(20).to_string())

host_body_site values:
host_body_site
NaN                    268
feces                    5
Not applicable           4
UBERON:mouth             4
UBERON:skin of foot      2
UBERON:nostril           1
UBERON:tongue            1
UBERON:anus              1
UBERON:feces             1

metagenome scientific_name values:
scientific_name
gut metagenome             54
feces metagenome           42
metagenome                 25
insect metagenome          19
bird metagenome            15
insect gut metagenome      10
NaN                        10
skin metagenome            10
bat metagenome             10
soil metagenome             8
mosquito metagenome         6
Spheniscus magellanicus     5
Eudyptula minor             5
viral metagenome            5
bat gut metagenome          5
Nematoda                    5
invertebrate metagenome     5
human oral metagenome       5
amphibian metagenome        5
Phasivirus phasiense        4

In [13]:
import pandas as pd
new_df = pd.read_csv("../results/sweep_new_studies_v2.tsv", sep="\t")
print(f"Studies in file: {new_df['study_accession'].nunique()}")
print(f"Rows in file: {len(new_df)}")
print(f"\nBy clade:")
print(new_df["_clade"].value_counts().to_string())

Studies in file: 64
Rows in file: 64

By clade:
_clade
Penguins                       18
Bats                           11
Mosquitoes                      5
Sirenians                       4
Butterflies and moths           4
Annelids                        3
Cetaceans                       2
Beetles                         2
Amphibians (all)                2
Ray-finned fish (broad)         2
Gastropods (beyond current)     2
Nematodes                       2
Turtles and tortoises           2
Lizards                         1
Fruit fly (Drosophila)          1
Molluscs (broad)                1
Frogs and toads                 1
Termites and cockroaches        1

In [14]:
import importlib
import src.classify_sweep_gut
importlib.reload(src.classify_sweep_gut)
from src.classify_sweep_gut import run

classified = run()

Classifying 64 studies...
  0/64
  10/64
  20/64
  30/64
  40/64
  50/64
  60/64

==================================================
GUT CLASSIFICATION OF 64 SWEEP STUDIES
==================================================
gut_verdict
KEEP              32
NEEDS_ABSTRACT    25
DROP               7

CONFIRMED GUT: 32 studies

Confirmed-gut by clade:
clade
Penguins                       10
Bats                            8
Sirenians                       3
Turtles and tortoises           2
Lizards                         1
Amphibians (all)                1
Ray-finned fish (broad)         1
Gastropods (beyond current)     1
Nematodes                       1
Cetaceans                       1
Mosquitoes                      1
Butterflies and moths           1
Termites and cockroaches        1

NEEDS_ABSTRACT (decide from literature):
study_accession                       clade                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            host                                                                                                                                                                                                                                                                                                                                                                                                                                                                 biome_labels
    PRJNA999620             Frogs and toads                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Anura; Scinax                                                                                                                                                                                                                                                                                                                                                                                                                                                         amphibian metagenome
   PRJNA1156918     Ray-finned fish (broad)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Actinopterygii                                                                                                                                                                                                                                                                                                                                                                                                                                                              fish metagenome
    PRJNA746569            Molluscs (broad)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Annelida; Arthropoda; Bryozoa; Chaetognatha; Chordata; Cnidaria; Ctenophora; Echinodermata; Gastrotricha; Gnathostomulida; Hemichordata; Kinorhyncha; Mollusca; Nematoda; Nemertea; Platyhelminthes; Priapulida; Rotifera; Sipuncula; Tardigrada; Xenacoelomorpha                                                                                                                                                                                                                                                                                                                                                                                     invertebrate metagenome; macroalgae metagenome; seawater metagenome; sediment metagenome
    PRJNA244498 Gastropods (beyond current)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Caenorhabditis elegans; Crenosoma vulpis; Heligmonoides; Mastophorus; Mastophorus muris; Nematoda; Nippostrongylus; Parascaris equorum; Strongyloidea; Syphacia; Toxocara cati; Trichinella nativa; Trichinella pseudospiralis; Trichuris
   PRJNA1248212                   Nematodes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Nematoda                                                                                                                                                                                                                                                                                                                                                                                                                                                              soil metagenome

In [15]:
import importlib
import src.enrich_sweep_literature
importlib.reload(src.enrich_sweep_literature)
from src.enrich_sweep_literature import run

enriched = run()

Enriching 60 studies (skipping 4 DROP)...
  0/60
  10/60
  20/60
  30/60
  40/60
  50/60

==================================================
AFTER LITERATURE ENRICHMENT
==================================================
gut_verdict_final
KEEP             37
DROP             15
MANUAL_REVIEW    12

CONFIRMED GUT (final): 37 studies
  single-host: 36
  multi-host surveys (handle at sample level): 1

Confirmed-gut by clade:
clade
Penguins                       12
Bats                            9
Sirenians                       3
Turtles and tortoises           2
Gastropods (beyond current)     2
Lizards                         1
Amphibians (all)                1
Ray-finned fish (broad)         1
Nematodes                       1
Cetaceans                       1
Mosquitoes                      1
Butterflies and moths           1
Termites and cockroaches        1

STILL NEEDS MANUAL REVIEW (12) — no paper or unclear text:
study_accession                   clade                                                                                                                          paper_title
   PRJNA1156918 Ray-finned fish (broad)                                                           Pac bio metabarcoding for monitoring genetic diversity in fish populations
    PRJNA685292  Fruit fly (Drosophila) Testing markers (ITS1, ITS2, LSU D1D2 and RPB2) to characterize microbial communities in food ecosystems using metagenomics approach
   PRJNA1187880              Mosquitoes                                                                                                          16S rRNA Raw sequence reads
   PRJNA1248132              Mosquitoes                                                Environmental DNA Dataset from Mosquito Habitat Water Containers in Jakarta Indonesia
   PRJNA1036017                 Beetles                                      Contribution of the Oulema spp. microbiome to insect survival rates after insecticide treatment
   PRJNA1169755                 Beetles                                                                Cell shape affects bacterial colony growth under physical confinement
    PRJNA849724   Butterflies and moths                                               High-throughput data of Cordyceps militaris in Liaoning province in year 2020 and 2021
   PRJNA1077668   Butterflies and moths                                                High-throughput fungal data of Cordyceps militaris in Liaoning province in 2019-2023.
    PRJNA965898   Butterflies and moths                                                             High-throughput data of Cordyceps militaris in Liaoning province in 2022
     PRJEB91453               Sirenians                Host traits impact the outcome of metagenomic library preparation from dental calculus samples across diverse mammals
    PRJNA437674                Penguins                                                                                                         Universal Parasite Detection
    PRJNA972831                Penguins                                                                                       Magellan and King penguin body site microbiota

Abstract coverage on enriched: 4/60
(Low coverage is expected — most ENA studies are data-only deposits.)

Saved -> ../results/sweep_enriched.tsv

In [16]:
import pandas as pd

yes_catalog = pd.read_csv("../results/yes_catalog.tsv", sep="\t")
enriched = pd.read_csv("../results/sweep_enriched.tsv", sep="\t")

confirmed = enriched[enriched["gut_verdict_final"] == "KEEP"].copy()

print("yes_catalog columns:")
print(yes_catalog.columns.tolist())
print(f"\nsweep confirmed columns:")
print(confirmed.columns.tolist())
print(f"\nConfirmed to merge: {len(confirmed)}")
print(f"\nDo they have host_tax_id? {'host_tax_id' in confirmed.columns}")
print(f"Sample host_tax_id values:")
print(confirmed["host_tax_id"].head() if "host_tax_id" in confirmed.columns else "MISSING")

yes_catalog columns:
['study_accession', 'host_species', 'host_tax_id', 'body_site', 'country', 'n_samples', 'library_strategy', 'data_source', 'pmid', 'pmid_str', 'paper_title', 'first_author', 'last_author', 'host_class', 'abstract', 'pub_year', 'journal', 'classification', 'needs_review', 'library_source', 'classification_final', 'host_kingdom', 'host_phylum', 'host_order', 'host_family', 'host_genus', 'host_species_taxonomy']

sweep confirmed columns:
['study_accession', 'gut_verdict', 'clade', 'host', 'n_runs', 'n_gut_samples', 'n_notgut_samples', 'n_ambiguous_samples', 'biome_labels', 'body_sites', 'is_multihost_survey', 'paper_title', 'abstract', 'pmid', 'gut_verdict_final']

Confirmed to merge: 37

Do they have host_tax_id? False
Sample host_tax_id values:
MISSING

In [17]:
import pandas as pd
import time
from src.ena_fetcher import fetch_runs_for_study, resolve_host_species, get_taxonomy

yes_catalog = pd.read_csv("../results/yes_catalog.tsv", sep="\t")
enriched = pd.read_csv("../results/sweep_enriched.tsv", sep="\t")
confirmed = enriched[enriched["gut_verdict_final"] == "KEEP"].copy()

rows = []
for i, r in confirmed.iterrows():
    acc = r["study_accession"]
    print(f"{len(rows)+1}/{len(confirmed)}: {acc}")
    runs = fetch_runs_for_study(acc)
    if runs is None or len(runs) == 0:
        continue
    tax_id = runs["host_tax_id"].dropna().mode()
    tax_id = tax_id[0] if len(tax_id) else None
    tax = get_taxonomy(str(tax_id)) if tax_id else {}
    rows.append({
        "study_accession": acc,
        "host_species": resolve_host_species(runs),
        "host_tax_id": tax_id,
        "body_site": runs["host_body_site"].dropna().mode()[0] if runs["host_body_site"].dropna().any() else "",
        "country": runs["country"].dropna().mode()[0] if runs["country"].dropna().any() else "",
        "n_samples": runs["sample_accession"].nunique(),
        "library_strategy": runs["library_strategy"].dropna().mode()[0] if runs["library_strategy"].dropna().any() else None,
        "library_source": runs["library_source"].dropna().mode()[0] if runs["library_source"].dropna().any() else None,
        "data_source": "sweep_host_search",
        "pmid": r.get("pmid"),
        "paper_title": r.get("paper_title"),
        "abstract": r.get("abstract"),
        "classification_final": "YES",
        "host_kingdom": tax.get("kingdom"),
        "host_phylum": tax.get("phylum"),
        "host_class": tax.get("class"),
        "host_order": tax.get("order"),
        "host_family": tax.get("family"),
        "host_genus": tax.get("genus"),
        "host_species_taxonomy": tax.get("species"),
        "sweep_clade": r.get("clade"),
        "gut_verdict_final": r.get("gut_verdict_final"),
    })
    time.sleep(0.3)

sweep_rows = pd.DataFrame(rows)
print(f"\nBuilt {len(sweep_rows)} catalog-ready sweep rows")
print(f"With host_class: {sweep_rows['host_class'].notna().sum()}/{len(sweep_rows)}")

1/37: PRJEB17686
2/37: PRJEB25617
3/37: PRJEB11419
4/37: PRJNA889361
5/37: PRJNA835803
6/37: PRJNA244498
7/37: PRJNA312520
8/37: PRJNA1252374
9/37: PRJEB36857
10/37: PRJEB14489
11/37: PRJNA565775
12/37: PRJNA1269778
13/37: PRJNA325503
14/37: PRJNA84289
15/37: PRJNA525109
16/37: PRJNA464362
17/37: PRJNA464356
18/37: PRJNA218570
19/37: PRJNA768434
20/37: PRJNA750668
ENA fetch failed for PRJNA750668: 500
20/37: PRJNA810306
21/37: PRJNA303105
22/37: PRJNA887424
23/37: PRJNA794207
24/37: PRJNA1200941
25/37: PRJNA704214
26/37: PRJNA956456
27/37: PRJNA555609
28/37: PRJEB3384
29/37: PRJEB40660
30/37: PRJNA544469
31/37: PRJNA689088
32/37: PRJNA1359116
33/37: PRJDB17206
34/37: PRJNA566128
35/37: PRJNA481090
36/37: PRJNA422502

Built 36 catalog-ready sweep rows
With host_class: 24/36

In [18]:
missing = sweep_rows[sweep_rows["host_class"].isna()]
print(f"Missing host_class: {len(missing)}")
print(missing[["study_accession", "sweep_clade", "host_species", "host_tax_id"]].to_string(index=False))

Missing host_class: 12
study_accession              sweep_clade       host_species host_tax_id
     PRJEB25617    Turtles and tortoises       Homo sapiens
     PRJEB11419    Turtles and tortoises       Homo sapiens
    PRJNA889361         Amphibians (all)           Amphibia        8292
    PRJNA835803  Ray-finned fish (broad)     Actinopterygii        7898
   PRJNA1252374                Nematodes           Nematoda        6231
     PRJEB14489                     Bats         metagenome      256318
    PRJNA565775                     Bats         Chiroptera
    PRJNA464362                     Bats       Homo sapiens
    PRJNA464356                     Bats Anas platyrhynchos
    PRJNA956456                 Penguins   Pygoscelis papua
    PRJNA481090                 Penguins Pygoscelis adeliae
    PRJNA422502 Termites and cockroaches    Inquilinitermes

In [19]:
existing = set(yes_catalog["study_accession"])
already = sweep_rows[sweep_rows["study_accession"].isin(existing)]
print(f"\nAlready in catalog (should be 0): {len(already)}")
if len(already):
    print(already["study_accession"].tolist())

Already in catalog (should be 0): 0

In [20]:
# search your notebooks/scripts for the query string
import subprocess
result = subprocess.run(
    ["grep", "-rn", "-i", "-E", "mesh|animals\\[|pubmed.*query|esearch", "../notebooks", "../src"],
    capture_output=True, text=True
)
print(result.stdout[:3000])

../notebooks/03_ena_exploration.ipynb:1067:      "(4)Bioinformatics Research Laboratory, Baylor College of Medicine, Houston, TX, \n",
../notebooks/03_ena_exploration.ipynb:1074:      "(8)Children's Nutrition Research Center, Houston, TX, USA.\n",
../notebooks/03_ena_exploration.ipynb:1081:      "(12)Alkek Center for Metagenomics and Microbiome Research, Baylor College of \n",
../notebooks/01_sra_exploration.ipynb:115:    "    handle = Entrez.esearch(db=\"sra\", term=term, retmax=0)\n",
../notebooks/05_pubmed_search.ipynb:67:    "pubmed_query = \"\"\" \n",
../notebooks/05_pubmed_search.ipynb:78:    "handle = Entrez.esearch(\n",
../notebooks/05_pubmed_search.ipynb:80:    "    term = pubmed_query, \n",
../notebooks/05_pubmed_search.ipynb:174:      "Food Technology, Spanish National Research Council (IATA-CSIC), Avda. Agustin \n",
../notebooks/05_pubmed_search.ipynb:182:      "Food Technology, Spanish National Research Council (IATA-CSIC), Avda. Agustin \n",
../notebooks/05_pubmed_search.ipynb:478:    "handle = Entrez.esearch(\n",
../notebooks/05_pubmed_search.ipynb:516:    "handle = Entrez.esearch(\n",
../notebooks/05_pubmed_search.ipynb:529:    "handle2 = Entrez.esearch(\n",
../notebooks/05_pubmed_search.ipynb:565:    "pubmed_query = \"\"\"\n",
../notebooks/05_pubmed_search.ipynb:576:    "handle = Entrez.esearch(\n",
../notebooks/05_pubmed_search.ipynb:578:    "    term=pubmed_query,\n",
../notebooks/05_pubmed_search.ipynb:673:    "pubmed_query = \"\"\"\n",
../notebooks/05_pubmed_search.ipynb:685:    "handle = Entrez.esearch(\n",
../notebooks/05_pubmed_search.ipynb:687:    "    term=pubmed_query,\n",
../notebooks/06_build_catalog.ipynb:1206:      "Columns: ['PMID', 'PubMed Link', 'PMCID', 'PMC Link', 'DOI', 'DOI Link', 'Year', 'Journal', 'Title', 'First Author', 'Last Author', 'Primary Class', 'Host (common, detected)', 'Host Class(es) detected', 'Binomials (heuristic)', 'Accessions (extracted)', 'PubTypes', 'Abstract', 'MeSH terms', 'Reviewed?', 'Include?', 'Notes (manual)']\n",
../notebooks/06_build_catalog.ipynb:4475:    "    [\"grep\", \"-rn\", \"-i\", \"-E\", \"mesh|animals\\\\[|pubmed.*query|esearch\", \"../notebooks\", \"../src\"],\n",
../notebooks/04_wgs_animalstudies.ipynb:358:      "PRJDB3415: Genome resequencing for research investigation of STAP cells\n",
../notebooks/04_wgs_animalstudies.ipynb:751:      "PRJDB19274: Marine animal genome information analysis and utilization-based research (KAP220208)\n",
../notebooks/04_wgs_animalstudies.ipynb:783:      "PRJDB19323: Research on the analysis and application of genetic information on marine animals (KAP220264)\n",
../notebooks/02_agent_prototype.ipynb:140:      "**High value.** Amphibians are significantly underrepresented in gut microbiome research compared to mammals, making this study valuable for GMToL's goal of phylogenetic diversity. The substantial WGS component (112 runs) is particularly useful since shotgun data enables strain-level resolution and functional profiling. The compa

In [24]:
from src.fetcher import configure_entrez
configure_entrez()

import importlib
import src.pubmed_search
importlib.reload(src.pubmed_search)
from src.pubmed_search import run

new_pmids = run()

Entrez configured with email: akharya@ucsd.edu
PubMed reports 2868 total matches; retrieved 2868 PMIDs
Existing PMIDs already in pipeline: 2170

==================================================
PUBMED QUERY (metagenom* expanded)
==================================================
Query matches:        2868
Already processed:    1357
NEW papers to fetch:  1511

Saved 1511 new PMIDs -> pubmed_new_pmids.txt

In [26]:
import pandas as pd

# ---- load what exists ----
yes_catalog = pd.read_csv("../results/yes_catalog.tsv", sep="\t")

print("="*60)
print("ANIMAL GUT WGS METAGENOMICS CATALOG — SUMMARY")
print("="*60)

# ---- headline counts ----
print(f"\n📊 STUDIES & SAMPLES")
print(f"Confirmed WGS gut studies (YES): {len(yes_catalog):,}")
print(f"Total samples:                   {yes_catalog['n_samples'].sum():,}")
print(f"Median samples/study:            {yes_catalog['n_samples'].median():.0f}")

# ---- provenance ----
print(f"\n📰 DATA SOURCE (how each study was found)")
print(yes_catalog['data_source'].value_counts().to_string())

# ---- literature coverage ----
print(f"\n📄 LITERATURE METADATA")
print(f"With abstract:  {yes_catalog['abstract'].notna().sum():,}")
print(f"With PMID:      {yes_catalog['pmid'].notna().sum():,}")
print(f"With title:     {yes_catalog['paper_title'].notna().sum():,}")

# ---- taxonomy coverage ----
print(f"\n🧬 HOST TAXONOMY COVERAGE")
for rank in ["host_kingdom","host_phylum","host_class","host_order","host_family","host_genus"]:
    if rank in yes_catalog.columns:
        n = yes_catalog[rank].notna().sum()
        print(f"  {rank:15s}: {n:>4}/{len(yes_catalog)} ({100*n/len(yes_catalog):.0f}%)")

# ---- diversity: class breakdown ----
print(f"\n🦎 HOST CLASS BREAKDOWN")
print(yes_catalog['host_class'].value_counts().to_string())

# ---- diversity: how many distinct taxa ----
print(f"\n🌐 TAXONOMIC BREADTH")
for rank in ["host_class","host_order","host_family","host_genus","host_species_taxonomy"]:
    if rank in yes_catalog.columns:
        print(f"  Distinct {rank.replace('host_',''):20s}: {yes_catalog[rank].nunique()}")


# ---- benchmark comparison ----
print(f"\n📈 vs AnimalMetagenome DB (2022 benchmark)")
print(f"  Their WGS samples: 10,672   |  Yours: {yes_catalog['n_samples'].sum():,}")
print(f"  Fold difference:   {yes_catalog['n_samples'].sum()/10672:.1f}x")

============================================================
ANIMAL GUT WGS METAGENOMICS CATALOG — SUMMARY
============================================================

📊 STUDIES & SAMPLES
Confirmed WGS gut studies (YES): 867
Total samples:                   96,872
Median samples/study:            40

📰 DATA SOURCE (how each study was found)
data_source
ena_only          483
pubmed            313
pubmed_postdoc     71

📄 LITERATURE METADATA
With abstract:  384
With PMID:      384
With title:     139

🧬 HOST TAXONOMY COVERAGE
  host_kingdom   :  626/867 (72%)
  host_phylum    :  626/867 (72%)
  host_class     :  626/867 (72%)
  host_order     :  623/867 (72%)
  host_family    :  623/867 (72%)
  host_genus     :  612/867 (71%)

🦎 HOST CLASS BREAKDOWN
host_class
Mammalia          478
Aves               77
Actinopteri        32
Insecta            24
Actinopterygii      4
Chondrichthyes      3
Magnoliopsida       2
Malacostraca        1
Amphibia            1
Lepidosauria        1
Arachnida           1
Gastropoda          1
Holothuroidea       1

🌐 TAXONOMIC BREADTH
  Distinct class               : 13
  Distinct order               : 43
  Distinct family              : 74
  Distinct genus               : 100
  Distinct species_taxonomy    : 140

📈 vs AnimalMetagenome DB (2022 benchmark)
  Their WGS samples: 10,672   |  Yours: 96,872
  Fold difference:   9.1x

In [ ]:
import src.pubmed_search as ps

# get the full result set
all_pmids = ps.run_esearch()
print(f"Total PMIDs: {len(all_pmids)}")

# save the complete list for tool
with open("../results/pubmed_all_pmids.txt", "w") as f:
    f.write("\n".join(str(p) for p in all_pmids))
print(f"Saved {len(all_pmids)} PMIDs -> pubmed_all_pmids.txt")

chunk_size = 500
chunks = [all_pmids[i:i+chunk_size] for i in range(0, len(all_pmids), chunk_size)]
for i, chunk in enumerate(chunks):
    with open(f"../results/pubmed_batch_{i+1}.txt", "w") as f:
        f.write("\n".join(str(p) for p in chunk))
print(f"Split into {len(chunks)} batches of ~{chunk_size} for tool")

PubMed reports 2868 total matches; retrieved 2868 PMIDs
Total PMIDs: 2868
Saved 2868 PMIDs -> pubmed_all_pmids.txt
Split into 6 batches of ~500 for Alan's tool

In [28]:
import pandas as pd
import glob

# load whatever batch results you have back
files = sorted(glob.glob("../results/batch*.csv"))
print(f"Result files found: {files}")

mmc = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)
print(f"\nTotal rows: {len(mmc)}")
print(f"Columns: {mmc.columns.tolist()}")
print(f"\nSample row with accessions:")
print(mmc[mmc['accessions'].notna()].head(1).to_dict() if 'accessions' in mmc.columns else "no 'accessions' column — check name")

Result files found: ['../results/batch1.csv', '../results/batch2.csv', '../results/batch3.csv']

Total rows: 1500
Columns: ['input_raw', 'pubmed_url', 'pmid', 'pmcid', 'is_pmc_article', 'accessions', 'accession_count', 'title', 'journal', 'pub_year', 'doi', 'authors', 'error_message']

Sample row with accessions:
{'input_raw': {0: 40874053}, 'pubmed_url': {0: 'https://pubmed.ncbi.nlm.nih.gov/40874053/'}, 'pmid': {0: 40874053}, 'pmcid': {0: 'PMC12378139'}, 'is_pmc_article': {0: True}, 'accessions': {0: 'PRJNA613441'}, 'accession_count': {0: 1}, 'title': {0: 'Identification of an Aeromonas hydrophila strain as a new mosquito pathogen.'}, 'journal': {0: 'Frontiers in cellular and infection microbiology'}, 'pub_year': {0: 2025.0}, 'doi': {0: '10.3389/fcimb.2025.1649545'}, 'authors': {0: 'Wehbe R; Karaki A; Kambris Z'}, 'error_message': {0: nan}}

In [ ]:
import pandas as pd
import re
import time
import glob
from concurrent.futures import ThreadPoolExecutor
from src.ena_fetcher import fetch_runs_for_study, resolve_host_species, get_taxonomy


files = sorted(glob.glob("../results/batch[1-3].csv"))
mmc = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)
print(f"Papers processed: {len(mmc)}")
print(f"Papers with accessions: {mmc['accessions'].notna().sum()}")

# ---- extract project accessions (semicolon-separated) ----
def extract_accessions(cell):
    if pd.isna(cell):
        return []
    return [a.strip() for a in str(cell).split(";")
            if re.match(r'PRJ[ENDB][A-Z]\d+', a.strip())]

# build accession -> paper-metadata map (keep title/doi/authors for the catalog)
acc_rows = []
for _, r in mmc[mmc["accessions"].notna()].iterrows():
    for acc in extract_accessions(r["accessions"]):
        acc_rows.append({
            "study_accession": acc,
            "pmid": r["pmid"],
            "paper_title": r["title"],
            "journal": r["journal"],
            "pub_year": r["pub_year"],
            "doi": r["doi"],
            "authors": r["authors"],
        })
acc_df = pd.DataFrame(acc_rows).drop_duplicates("study_accession")
print(f"Unique project accessions: {len(acc_df)}")

# ---- dedupe against catalog (the clean accession-based dedupe) ----
yes_catalog = pd.read_csv("../results/yes_catalog.tsv", sep="\t")
existing = set(yes_catalog["study_accession"])

# also check against the full catalog if you have it, to skip already-classified NO/16S
try:
    final_catalog = pd.read_csv("../results/final_catalog.tsv", sep="\t")
    existing |= set(final_catalog["study_accession"])
except Exception:
    pass

new_acc = acc_df[~acc_df["study_accession"].isin(existing)].copy()
print(f"\nAlready in catalog: {len(acc_df) - len(new_acc)}")
print(f"NEW accessions to classify: {len(new_acc)}")

Papers processed: 1500
Papers with accessions: 655
Unique project accessions: 794

Already in catalog: 405
NEW accessions to classify: 389

In [30]:
import time, json, os
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
import src.ena_fetcher
import importlib
importlib.reload(src.ena_fetcher)
from src.ena_fetcher import fetch_runs_for_study, resolve_host_species, get_taxonomy

CHECKPOINT = "../results/pubmed_new_classified.json"

# resume if interrupted
done = {}
if os.path.exists(CHECKPOINT):
    with open(CHECKPOINT) as f:
        done = json.load(f)
    print(f"Resuming — {len(done)} already fetched")

to_do = [a for a in new_acc["study_accession"] if a not in done]
print(f"Fetching {len(to_do)} studies...")

for i, acc in enumerate(to_do):
    if i % 25 == 0:
        print(f"  {i}/{len(to_do)}")
        with open(CHECKPOINT, "w") as f:
            json.dump(done, f)
    try:
        runs = fetch_runs_for_study(acc)
        if runs is None or len(runs) == 0:
            done[acc] = {"status": "no_runs"}
            continue
        lib_source = runs["library_source"].dropna().mode()
        lib_strategy = runs["library_strategy"].dropna().mode()
        done[acc] = {
            "status": "ok",
            "host_species": resolve_host_species(runs),
            "host_tax_id": str(runs["host_tax_id"].dropna().mode()[0]) if runs["host_tax_id"].dropna().any() else None,
            "n_samples": int(runs["sample_accession"].nunique()),
            "library_source": lib_source[0] if len(lib_source) else None,
            "library_strategy": lib_strategy[0] if len(lib_strategy) else None,
            "body_site": runs["host_body_site"].dropna().mode()[0] if runs["host_body_site"].dropna().any() else "",
            "country": runs["country"].dropna().mode()[0] if runs["country"].dropna().any() else "",
        }
    except Exception as e:
        done[acc] = {"status": f"error: {e}"}
    time.sleep(0.25)

with open(CHECKPOINT, "w") as f:
    json.dump(done, f)
print(f"\nDone. Fetched {len(done)} total.")

# quick classification summary using the same library_source/strategy logic
ok = {k: v for k, v in done.items() if v.get("status") == "ok"}
print(f"Studies with runs: {len(ok)}")
src_counts = {}
for v in ok.values():
    src_counts[v["library_source"]] = src_counts.get(v["library_source"], 0) + 1
print(f"\nLibrary source breakdown:")
for s, c in sorted(src_counts.items(), key=lambda x: -x[1]):
    print(f"  {s}: {c}")

Fetching 389 studies...
  0/389
No runs found for PRJNA1038784
No runs found for PRJEB55376
No runs found for PRJNA1165328
No runs found for PRJNA1165775
No runs found for PRJNA1268717
No runs found for PRJNA1271077
No runs found for PRJNA1217447
No runs found for PRJNA977461
  25/389
No runs found for PRJNA1196159
No runs found for PRJEB801559
No runs found for PRJNA1247262
No runs found for PRJNA1211720
No runs found for PRJNA1010808
  50/389
No runs found for PRJNA1227685
No runs found for PRJNA1151847
No runs found for PRJNA1177368
  75/389
No runs found for PRJNA1185451
No runs found for PRJNA1185452
No runs found for PRJNA1185935
No runs found for PRJNA1186098
No runs found for PRJNA1186113
No runs found for PRJNA1186118
No runs found for PRJNA1186124
No runs found for PRJNA1186133
No runs found for PRJNA1186134
No runs found for PRJNA1186142
No runs found for PRJNA1186148
No runs found for PRJNA1186149
No runs found for PRJNA1186151
No runs found for PRJNA98774319
  100/389
No runs found for PRJNA98774335
No runs found for PRJNA1138003
No runs found for PRJNA1077584
No runs found for PRJNA1170951
No runs found for PRJNA983434
No runs found for PRJEB70999
No runs found for PRJEB45234
No runs found for PRJNA1028308
No runs found for PRJEB81441
  125/389
No runs found for PRJNA657473
No runs found for PRJEB43619
No runs found for PRJNA888994
No runs found for PRJNA1295778
No runs found for PRJNA1307007
  150/389
No runs found for PRJNA114561
No runs found for PRJNA114561729
No runs found for PRJNA1434117
No runs found for PRJEB1046
  175/389
No runs found for PRJEB674
No runs found for PRJNA1267279
No runs found for PRJEB45252
No runs found for PRJNA115895940
No runs found for PRJNA13205140
No runs found for PRJNA1289876
No runs found for PRJNA1263915
No runs found for PRJNA1108251
  200/389
No runs found for PRJNA687329
No runs found for PRJNA100222
No runs found for PRJNA1415316
No runs found for PRJNA1416997
No runs found for PRJNA1418170
No runs found for PRJNA1379261
No runs found for PRJNA1381256
No runs found for PRJNA482748
No runs found for PRJNA903559
No runs found for PRJNA1310243
  225/389
No runs found for PRJNA1224300
No runs found for PRJNA1225000
No runs found for PRJEB55374
No runs found for PRJEB55375
No runs found for PRJNA1277365
No runs found for PRJNA1049387
No runs found for PRJNA1049592
No runs found for PRJNA1358044
No runs found for PRJDB7102
No runs found for PRJNA1344668
No runs found for PRJNA1244039
No runs found for PRJNA1293921
  250/389
No runs found for PRJNA1190225
No runs found for PRJEB94130
No runs found for PRJNA1250387
No runs found for PRJNA1150362
No runs found for PRJNA1031405
No runs found for PRJNA1065120
No runs found for PRJNA1085270
  275/389
No runs found for PRJDB13917
No runs found for PRJNA1052115
  300/389
No runs found for PRJNA923293
No runs found for PRJNA923754
No runs found for PRJNA923757
No runs found for PRJNA923758
No runs found for PRJNA925792
No runs found for PRJNA925821
No runs found for PRJNA1022859
No runs found for PRJNA1024074
No runs found for PRJNA1024099
No runs found for PRJNA1024450
No runs found for PRJEB68160
No runs found for PRJNA1010509
  325/389
No runs found for PRJNA434628
No runs found for PRJNA864640
No runs found for PRJNA894235
No runs found for PRJEB47807
No runs found for PRJNA485481
  350/389
No runs found for PRJEB589
No runs found for PRJNA836733
No runs found for PRJNA908247
No runs found for PRJNA908248
  375/389
No runs found for PRJNA910333
No runs found for PRJNA20689
No runs found for PRJEB35945
No runs found for PRJNA240272
No runs found for PRJNA725502

Done. Fetched 389 total.
Studies with runs: 276

Library source breakdown:
  METAGENOMIC: 219
  GENOMIC: 32
  TRANSCRIPTOMIC: 14
  OTHER: 8
  METATRANSCRIPTOMIC: 3

In [34]:
import importlib
import src.classify_llm
importlib.reload(src.classify_llm)
from src.classify_llm import run

llm_out = run()

Studies to classify (had runs): 276
Classifying 276 studies with claude-haiku-4-5-20251001...

  0/276
  10/276
  20/276
  30/276
  40/276
  50/276
  60/276
  70/276
  80/276
  90/276
  100/276
  110/276
  120/276
  130/276
  140/276
  150/276
  160/276
  170/276
  180/276
  190/276
  200/276
  210/276
  220/276
  230/276
  240/276
  250/276
  260/276
  270/276

====================================================
LLM CLASSIFICATION — CONFIDENCE TIERS
====================================================
tier
EXCLUDED         136
CONFIRMED_GUT    121
REVIEW            19

Verdict x confidence:
confidence       high  low  medium
verdict
GUT_WGS            95    0      26
NOT_GUT             4    0       1
NOT_METAGENOMIC   131    0       0
UNCERTAIN           0   18       1

body_site_signal (how many were INFERRED vs stated):
body_site_signal
explicit       196
none            46
inferred        32
conflicting      1
mixed            1

CONFIRMED GUT (high/medium confidence): 121
LIKELY GUT — needs review (low conf/inferred): 0
UNCERTAIN — needs review: 19
EXCLUDED: 136

Saved -> ../results/llm_classified.tsv

In [ ]:
import pandas as pd
out = pd.read_csv("../results/llm_classified.tsv", sep="\t")

print("=== SAMPLE CONFIRMED_GUT FOR CONFIRMATION ===")
for _, r in out[out["tier"]=="CONFIRMED_GUT"].head(8).iterrows():
    print(f"\n{r['study_accession']} [{r['confidence']}, {r['body_site_signal']}]")
    print(f"  host: {r['host_species']}")
    print(f"  evidence: {r['evidence']}")
    print(f"  reasoning: {r['reasoning']}")

print("\n\n=== the 5 NOT_GUT — verify ===")
for _, r in out[out["verdict"]=="NOT_GUT"].iterrows():
    print(f"\n{r['study_accession']}: {r['evidence']} | {r['reasoning']}")

print("\n\n=== 6 NOT_METAGENOMIC — verify ===")
for _, r in out[out["verdict"]=="NOT_METAGENOMIC"].head(6).iterrows():
    print(f"\n{r['study_accession']}: {r['evidence']} | {r['reasoning']}")

=== SAMPLECONFIRMED_GUT FOR CONFIRMATION ===

PRJNA1211045 [high, explicit]
  host: Bulinus sp.
  evidence: Sample titles explicitly state 'feces metagenome' (e.g., 'Anisus feces metagenome Uk1'); library_strategy='WGS'; library_source='METAGENOMIC'; biome label='feces metagenome'.
  reasoning: Multiple explicit references to fecal samples combined with shotgun metagenomics methodology (WGS, metagenomic community DNA) from animal hosts (freshwater snails) confirm this is shotgun metagenomic analysis of an animal gut microbiome.

PRJNA1210771 [high, explicit]
  host: Euphausia superba
  evidence: Isolation source(s): 'gut sample 1; gut sample 13; gut sample 14; gut sample 15; gut sample 2; gut sample 3; gut sample 4; gut sample 5'; library_source: 'METAGENOMIC'; library_strategy: 'WGS'; Paper title: 'Metabolic potentials of the gut microbes in Antarctic krill (Euphausia superba)'
  reasoning: The isolation source explicitly states 'gut sample' for all eight samples, library_source is METAGENOMIC, library_strategy is WGS (shotgun), and the paper title confirms gut microbiota analysis, meeting all criteria for GUT_WGS classification.

PRJNA1084222 [high, explicit]
  host: Mauremys reevesii
  evidence: Paper title: 'Intestinal microbial dysbiosis under nitrite stress in juvenile three-keeled pond turtles'; ENA study title: 'Metagenome or environmental sample from gut metagenome'; Biome label: 'gut metagenome'; Isolation source: 'intestinal microbial'; library_source: 'METAGENOMIC'; Host organism: Mauremys reevesii (animal)
  reasoning: Multiple explicit statements confirm shotgun metagenomic sequencing (METAGENOMIC library source) of an animal's gut microbiome (intestinal/gut metagenome from a turtle).

PRJNA1148150 [high, explicit]
  host: Mus musculus
  evidence: Paper title: 'Dietary impact on the gut resistome: western diet independently increases the prevalence of antibiotic resistance genes within the gut microbiota.' ENA study title: 'MIMS Environmental/Metagenome sample from mouse metagenome.' library_source: METAGENOMIC. library_strategy: WGS. Host organism: Mus musculus.
  reasoning: Paper title explicitly states 'gut resistome' and 'gut microbiota,' combined with shotgun metagenomic sequencing (WGS + METAGENOMIC library source) of mouse samples, definitively identifying this as a gut WGS metagenomic study.

PRJEB89425 [high, inferred]
  host: nan
  evidence: Paper title: 'Bacterial transmission within social groups shapes the underexplored gut microbiome in the lemur Indri indri.' Library_source: METAGENOMIC. Library_strategy: WGS. Host organism: lemur (Indri indri).
  reasoning: The paper title explicitly states 'gut microbiome' and the host is an animal (lemur); library_source and library_strategy confirm shotgun metagenomic sequencing, meeting all GUT_WGS criteria, though body site is inferred from the title rather than explicitly stated in metadata fields.

PRJNA399458 [medium, inferred]
  host: Indri indri
  evidence: Paper title states 'gut microbiome in the lemur Indri indri'; library_source='GENOMIC' with library_strategy='WGS' indicates shotgun sequencing of community DNA; body site (gut) is stated in title but NOT in structured metadata fields (Host body site, Isolation source both empty).
  reasoning: The paper title explicitly mentions 'gut microbiome' and WGS of an animal, meeting criteria for GUT_WGS, but confidence is medium because body site is absent from structured ENA fields and only present in the paper title (inferred from context rather than explicitly recorded in sample metadata).

PRJNA1229795 [high, explicit]
  host: Mus musculus
  evidence: Isolation source(s): feces; Biome label(s): gut metagenome; library_strategy: WGS; library_source: METAGENOMIC; Host organism(s): Mus musculus
  reasoning: Fecal samples from mouse with shotgun metagenomic sequencing (WGS library strategy, METAGENOMIC library source) explicitly identifies this as a gut microbiome study.

PRJNA1244851 [medium, inferred]
  host: nan
  evidence: Paper title: 'Profiling Bile Acids in the Stools of Humans and Animal Models of Cystic Fibrosis'; library_source: METAGENOMIC; library_strategy: WGS
  reasoning: The paper title explicitly mentions 'Stools' (fecal material) as the sample source and indicates animal models are included, and WGS metagenomic sequencing is confirmed, but no host organism species is explicitly stated so body site must be inferred from 'Stools' mention in the title.


=== the 5 NOT_GUT — verify ===

PRJNA438286: Sample titles explicitly state 'Esophagus_1month_1', 'Esophagus_1month_2', 'Esophagus_1month_3', and 'Heart tissue isolated from a male of Elaphurus davidianus'; library_source='GENOMIC' indicates single-organism genomic DNA, not metagenomic community DNA. | While the paper title mentions gut microbiota and WGS strategy is shotgun-compatible, the explicit body site labels (esophagus, heart) are non-gut tissues, and the GENOMIC library source contradicts metagenomic classification (metagenomic studies require library_source=METAGENOMIC for community DNA).

PRJNA861709: Isolation source(s): Digestive tract; salivary gland | While digestive tract is mentioned, the primary focus is salivary gland bacteria from sand flies (Phlebotomus papatasi, an insect vector), not a vertebrate animal's gut microbiome, and the study explicitly examines bacteria in forced salivation/infectious inoculum rather than fecal/intestinal content.

PRJNA1023379: Biome label: 'bioreactor metagenome'; ENA study title: 'Metagenome or environmental sample from bioreactor metagenome'; Isolation source: 'Bioreactor enriched with Kyphosidae...' (all samples from bioreactor, not from animal); library_strategy: WGS; library_source: METAGENOMIC | Although the bioreactor was enriched with fish gut contents as source material, the actual sequenced samples are from bioreactor cultures (an in vitro enrichment system), not from the animal's gut itself, making this an environmental metagenomics study rather than a direct gut microbiome study.

PRJNA687506: Paper title: 'Characterization of the pig lower respiratory tract antibiotic resistome.' ENA study titles contain 'BAL' (bronchoalveolar lavage) and 'UA' (upper airway), both respiratory tract samples, not gut. | This is shotgun metagenomic data (WGS, GENOMIC library_source), but from respiratory tract samples (BAL, upper airway) of pigs, not from gut/intestinal/fecal sites.

PRJNA826725: Host organism: Gigantidas haimaensis (deep-sea mussel); Isolation source: 'cold seep 1; cold seep 2'; Sample title: 'Metagenome or environmental sample from mollusc metagenome'; Title states 'gut microbiomes of deep-sea cold seep mussels' BUT isolation source explicitly indicates cold seep environment, not gut tissue. | While the paper title mentions 'gut microbiomes,' the isolation source is explicitly 'cold seep' (environmental), and the study is of mussel-associated microbiomes from a deep-sea cold seep habitat rather than isolated gut samples, making this an environmental/host-associated metagenomics study, not a gut-derived metagenomics study.


=== 6 NOT_METAGENOMIC — verify ===

PRJNA1218022: library_strategy: AMPLICON | The study uses AMPLICON sequencing (16S), not shotgun/WGS metagenomic sequencing, despite the metagenomic biome label and gut isolation source.

PRJNA1218276: library_strategy: AMPLICON; Sample title explicitly states 'Gut amplicon 16S metagenome sample' | This is a 16S amplicon study, not shotgun/WGS metagenomics, as indicated by the AMPLICON library strategy despite the metagenomic source classification.

PRJNA1225640: library_strategy: AMPLICON | The library_strategy is explicitly AMPLICON, which indicates 16S/amplicon sequencing rather than shotgun metagenomic sequencing (WGS/METAGENOMIC), disqualifying this from the GUT_WGS category despite the explicit gut body site.

PRJNA1018811: library_source: TRANSCRIPTOMIC; library_strategy: RNA-Seq | The study is RNA-Seq transcriptomics (RNA from host and/or microbiota), not shotgun metagenomics of community DNA, regardless of the intestinal context mentioned in the paper title.

PRJNA1255302: library_strategy: AMPLICON | AMPLICON library strategy indicates 16S/targeted amplicon sequencing, not shotgun metagenomics, regardless of the METAGENOMIC library_source label.

PRJNA1192515: library_strategy: AMPLICON | AMPLICON sequencing (16S rRNA gene) is explicitly stated, which is not shotgun metagenomics regardless of body site or host organism.

In [37]:
import pandas as pd
import re
import glob

# load Alan's tool results for this batch
files = sorted(glob.glob("../results/batch*.csv"))
print(f"Loading: {files}")
mmc = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)
print(f"Papers: {len(mmc)}, with accessions: {mmc['accessions'].notna().sum()}")

# extract project accessions, carrying paper metadata
def extract_accessions(cell):
    if pd.isna(cell):
        return []
    return [a.strip() for a in str(cell).split(";")
            if re.match(r'PRJ[ENDB][A-Z]\d+', a.strip())]

acc_rows = []
for _, r in mmc[mmc["accessions"].notna()].iterrows():
    for acc in extract_accessions(r["accessions"]):
        acc_rows.append({
            "study_accession": acc,
            "pmid": r["pmid"],
            "paper_title": r["title"],
            "journal": r["journal"],
            "pub_year": r["pub_year"],
            "doi": r["doi"],
            "authors": r["authors"],
        })

acc_df = pd.DataFrame(acc_rows).drop_duplicates("study_accession")
print(f"Unique accessions in acc_df: {len(acc_df)}")

Loading: ['../results/batch1.csv', '../results/batch2.csv', '../results/batch3.csv']
Papers: 1500, with accessions: 655
Unique accessions in acc_df: 794

In [39]:
import pandas as pd, time
from src.ena_fetcher import fetch_runs_for_study, resolve_host_species, get_taxonomy

# ---- attach LLM provenance to a row ----
def add_provenance(row, llm_row):
    row["llm_confidence"]        = llm_row["confidence"]
    row["llm_body_site_signal"]  = llm_row["body_site_signal"]
    row["llm_evidence"]          = llm_row["evidence"]
    return row

# ---- confirmed studies from the classifier ----
llm = pd.read_csv("../results/llm_classified.tsv", sep="\t")
confirmed = llm[llm["tier"] == "CONFIRMED_GUT"].set_index("study_accession")
print(f"Confirmed to finalize: {len(confirmed)}")


paper_lookup = acc_df.set_index("study_accession").to_dict("index")

Confirmed to finalize: 121

In [40]:
rows = []
for i, acc in enumerate(confirmed.index):
    if i % 20 == 0: print(f"{i}/{len(confirmed)}")
    runs = fetch_runs_for_study(acc)
    if runs is None or len(runs) == 0:
        continue
    tax_id = runs["host_tax_id"].dropna().mode()
    tax_id = tax_id[0] if len(tax_id) else None
    tax = get_taxonomy(str(tax_id)) if tax_id else {}
    p = paper_lookup.get(acc, {})

    row = {
        "study_accession": acc,
        "host_species": resolve_host_species(runs),
        "host_tax_id": tax_id,
        "n_samples": runs["sample_accession"].nunique(),
        "library_strategy": runs["library_strategy"].dropna().mode()[0] if runs["library_strategy"].dropna().any() else None,
        "library_source": runs["library_source"].dropna().mode()[0] if runs["library_source"].dropna().any() else None,
        "body_site": runs["host_body_site"].dropna().mode()[0] if runs["host_body_site"].dropna().any() else "",
        "country": runs["country"].dropna().mode()[0] if runs["country"].dropna().any() else "",
        "data_source": "pubmed_metagenom_b1",
        "pmid": p.get("pmid"), "paper_title": p.get("paper_title"),
        "doi": p.get("doi"), "journal": p.get("journal"), "pub_year": p.get("pub_year"),
        "classification_final": "YES",
        "host_kingdom": tax.get("kingdom"), "host_phylum": tax.get("phylum"),
        "host_class": tax.get("class"), "host_order": tax.get("order"),
        "host_family": tax.get("family"), "host_genus": tax.get("genus"),
        "host_species_taxonomy": tax.get("species"),
    }
    row = add_provenance(row, confirmed.loc[acc])   # <-- the only new step
    rows.append(row)
    time.sleep(0.2)

new_rows = pd.DataFrame(rows)
print(f"Built {len(new_rows)} rows, host_class filled: {new_rows['host_class'].notna().sum()}")

0/121
20/121
40/121
60/121
80/121
Error fetching taxonomy for tax_id 7460: HTTP Error 400: Bad Request
100/121
120/121
Built 121 rows, host_class filled: 73

In [41]:
yes_catalog = pd.read_csv("../results/yes_catalog.tsv", sep="\t")
before = len(yes_catalog)
truly_new = new_rows[~new_rows["study_accession"].isin(set(yes_catalog["study_accession"]))]

merged = pd.concat([yes_catalog, truly_new], ignore_index=True).drop_duplicates("study_accession", keep="first")
merged.to_csv("../results/yes_catalog.tsv", sep="\t", index=False)
truly_new.to_csv("../results/added_pubmed_metagenom_b1.tsv", sep="\t", index=False)

print(f"Catalog: {before} -> {len(merged)} (+{len(merged)-before})")
print(f"New samples: {truly_new['n_samples'].sum():,} | Total: {merged['n_samples'].sum():,}")
print(f"\nNew studies by host class:")
print(truly_new["host_class"].value_counts().to_string())

Catalog: 867 -> 988 (+121)
New samples: 8,542 | Total: 105,414

New studies by host class:
host_class
Mammalia         44
Insecta          13
Aves              6
Lepidosauria      4
Actinopteri       2
Gastropoda        1
Malacostraca      1
Holothuroidea     1
Branchiopoda      1

In [42]:
import pandas as pd
import re
import time
import glob
from concurrent.futures import ThreadPoolExecutor
from src.ena_fetcher import fetch_runs_for_study, resolve_host_species, get_taxonomy


files = sorted(glob.glob("../results/batch[4-6].csv"))
mmc = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)
print(f"Papers processed: {len(mmc)}")
print(f"Papers with accessions: {mmc['accessions'].notna().sum()}")

# ---- extract project accessions (semicolon-separated) ----
def extract_accessions(cell):
    if pd.isna(cell):
        return []
    return [a.strip() for a in str(cell).split(";")
            if re.match(r'PRJ[ENDB][A-Z]\d+', a.strip())]

# build accession -> paper-metadata map (keep title/doi/authors for the catalog)
acc_rows = []
for _, r in mmc[mmc["accessions"].notna()].iterrows():
    for acc in extract_accessions(r["accessions"]):
        acc_rows.append({
            "study_accession": acc,
            "pmid": r["pmid"],
            "paper_title": r["title"],
            "journal": r["journal"],
            "pub_year": r["pub_year"],
            "doi": r["doi"],
            "authors": r["authors"],
        })
acc_df = pd.DataFrame(acc_rows).drop_duplicates("study_accession")
print(f"Unique project accessions: {len(acc_df)}")

# ---- dedupe against catalog (the clean accession-based dedupe) ----
yes_catalog = pd.read_csv("../results/yes_catalog.tsv", sep="\t")
existing = set(yes_catalog["study_accession"])

# also check against the full catalog if you have it, to skip already-classified NO/16S
try:
    final_catalog = pd.read_csv("../results/final_catalog.tsv", sep="\t")
    existing |= set(final_catalog["study_accession"])
except Exception:
    pass

new_acc = acc_df[~acc_df["study_accession"].isin(existing)].copy()
print(f"\nAlready in catalog: {len(acc_df) - len(new_acc)}")
print(f"NEW accessions to classify: {len(new_acc)}")

Papers processed: 1368
Papers with accessions: 491
Unique project accessions: 531

Already in catalog: 283
NEW accessions to classify: 248

In [43]:
yes_catalog = pd.read_csv("../results/yes_catalog.tsv", sep="\t")
print(f"Catalog size now: {len(yes_catalog)}")
print(f"Studies tagged batch 1: {(yes_catalog['data_source']=='pubmed_metagenom_b1').sum()}")

Catalog size now: 988
Studies tagged batch 1: 121

In [44]:
import glob
print("Files the extraction read:", sorted(glob.glob("../results/batch[4-6].csv")))

Files the extraction read: ['../results/batch4.csv', '../results/batch5.csv', '../results/batch6.csv']

In [45]:
import time, json, os
from src.ena_fetcher import fetch_runs_for_study, resolve_host_species

CHECKPOINT = "../results/pubmed_new_classified_b2.json"   # <-- b2, distinct from batch 1

done = {}
if os.path.exists(CHECKPOINT):
    with open(CHECKPOINT) as f:
        done = json.load(f)
    print(f"Resuming — {len(done)} already fetched")

to_do = [a for a in new_acc["study_accession"] if a not in done]
print(f"Fetching {len(to_do)} studies...")

for i, acc in enumerate(to_do):
    if i % 25 == 0:
        print(f"  {i}/{len(to_do)}")
        with open(CHECKPOINT, "w") as f:
            json.dump(done, f)
    try:
        runs = fetch_runs_for_study(acc)
        if runs is None or len(runs) == 0:
            done[acc] = {"status": "no_runs"}
            continue
        lib_source = runs["library_source"].dropna().mode()
        lib_strategy = runs["library_strategy"].dropna().mode()
        done[acc] = {
            "status": "ok",
            "host_species": resolve_host_species(runs),
            "host_tax_id": str(runs["host_tax_id"].dropna().mode()[0]) if runs["host_tax_id"].dropna().any() else None,
            "n_samples": int(runs["sample_accession"].nunique()),
            "library_source": lib_source[0] if len(lib_source) else None,
            "library_strategy": lib_strategy[0] if len(lib_strategy) else None,
            "body_site": runs["host_body_site"].dropna().mode()[0] if runs["host_body_site"].dropna().any() else "",
            "country": runs["country"].dropna().mode()[0] if runs["country"].dropna().any() else "",
        }
    except Exception as e:
        done[acc] = {"status": f"error: {e}"}
    time.sleep(0.25)

with open(CHECKPOINT, "w") as f:
    json.dump(done, f)

ok = {k: v for k, v in done.items() if v.get("status") == "ok"}
print(f"\nDone. {len(ok)}/{len(done)} returned runs")
src_counts = {}
for v in ok.values():
    src_counts[v["library_source"]] = src_counts.get(v["library_source"], 0) + 1
print("Library source:", src_counts)

Fetching 248 studies...
  0/248
No runs found for PRJEB14698
No runs found for PRJEB33885
No runs found for PRJEB35610
No runs found for PRJNA657473
No runs found for PRJNA826263
  25/248
No runs found for PRJNA95448
No runs found for PRJNA82536
No runs found for PRJEB45252
No runs found for PRJNA698776
No runs found for PRJNA810349
No runs found for PRJNA313047
  50/248
No runs found for PRJNA556087
No runs found for PRJNA839170
No runs found for PRJEB4309633
No runs found for PRJEB4309734
No runs found for PRJNA773059
No runs found for PRJNA792464
  75/248
No runs found for PRJNA55157132
No runs found for PRJNA648267
  100/248
No runs found for PRJNA662678
No runs found for PRJNA12624
No runs found for PRJNA608666
No runs found for PRJNA615701
No runs found for PRJNA530070
  125/248
No runs found for PRJNA546576
No runs found for PRJNA61338131
  150/248
No runs found for PRJEB35751
No runs found for PRJNA497967
No runs found for PRJEB11650
No runs found for PRJNA508548
  175/248
No runs found for PRJEB33256
No runs found for PRJNA476694
No runs found for PRJNA4766948
  200/248
No runs found for PRJNA237016
No runs found for PRJNA331139
No runs found for PRJEB21090
No runs found for PRJNA261082
No runs found for PRJNA454115
  225/248
No runs found for PRJNA283468
No runs found for PRJNA258166

Done. 208/248 returned runs
Library source: {'METAGENOMIC': 146, 'GENOMIC': 42, 'METATRANSCRIPTOMIC': 5, 'TRANSCRIPTOMIC': 6, 'OTHER': 9}

In [46]:
import os
os.makedirs("../results/batch1_done", exist_ok=True)
for f in ["batch1.csv", "batch2.csv", "batch3.csv"]:
    src = f"../results/{f}"
    if os.path.exists(src):
        os.rename(src, f"../results/batch1_done/{f}")
print("Batch 1 CSVs archived:", os.listdir("../results/batch1_done"))
print("Remaining batch CSVs:", sorted([f for f in os.listdir("../results") if f.startswith("batch") and f.endswith(".csv")]))

Batch 1 CSVs archived: ['batch1.csv', 'batch2.csv', 'batch3.csv']
Remaining batch CSVs: ['batch4.csv', 'batch5.csv', 'batch6.csv']

In [49]:
import src.classify_llm as cl
import importlib
importlib.reload(cl)

cl.FETCH_JSON = "../results/pubmed_new_classified_b2.json"
cl.CHECKPOINT = "../results/llm_verdicts_b2.json"
cl.OUT_PATH   = "../results/llm_classified_b2.tsv"

out_b2 = cl.run()

Studies to classify (had runs): 208
Resuming — 110 already classified
Classifying 98 studies with claude-haiku-4-5-20251001...

  0/98
  10/98
  20/98
  30/98
  40/98
  50/98
  60/98
  70/98
  80/98
  90/98

====================================================
LLM CLASSIFICATION — CONFIDENCE TIERS
====================================================
tier
EXCLUDED         138
CONFIRMED_GUT     56
REVIEW            14

Verdict x confidence:
confidence       high  low  medium
verdict
GUT_WGS            50    0       6
NOT_GUT             1    0       1
NOT_METAGENOMIC   136    0       0
UNCERTAIN           0   14       0

body_site_signal (how many were INFERRED vs stated):
body_site_signal
explicit    164
none         28
inferred     15
mixed         1

CONFIRMED GUT (high/medium confidence): 56
LIKELY GUT — needs review (low conf/inferred): 0
UNCERTAIN — needs review: 14
EXCLUDED: 138

Saved -> ../results/llm_classified_b2.tsv

In [48]:
import json
with open("../results/llm_verdicts_b2.json") as f:
    v = json.load(f)
print(f"Saved so far: {len(v)}")
from collections import Counter
print(Counter(x.get("verdict") for x in v.values()))

Saved so far: 110
Counter({'NOT_METAGENOMIC': 65, 'GUT_WGS': 36, 'UNCERTAIN': 9})

In [51]:
import pandas as pd, glob, re

b2 = pd.read_csv("../results/llm_classified_b2.tsv", sep="\t")

# pull paper titles straight from Alan's tool output (batch 4-6)
mmc = pd.concat([pd.read_csv(f) for f in sorted(glob.glob("../results/batch[4-6].csv"))],
                ignore_index=True)
title_map = {}
for _, r in mmc.iterrows():
    for acc in re.findall(r'PRJ[ENDB][A-Z]\d+', str(r.get("accessions",""))):
        title_map[acc] = str(r.get("title",""))

def show(subset, n, label):
    print(f"\n{'='*70}\n{label}\n{'='*70}")
    for _, r in subset.head(n).iterrows():
        acc = r["study_accession"]
        print(f"\n{acc}  ({r['library_source']}/{r['library_strategy']}) -> {r['verdict']} [{r['confidence']}]")
        print(f"  PAPER TITLE: {title_map.get(acc, '(no title found)')}")
        print(f"  evidence:    {r['evidence']}")
        print(f"  reasoning:   {r['reasoning']}")

show(b2[b2["verdict"]=="NOT_METAGENOMIC"], 10, "NOT_METAGENOMIC — do these titles look non-gut-WGS to you?")
show(b2[b2["tier"]=="CONFIRMED_GUT"], 6, "CONFIRMED_GUT — do these titles look like real gut shotgun?")

======================================================================
NOT_METAGENOMIC — do these titles look non-gut-WGS to you?
======================================================================

PRJNA909983  (METAGENOMIC/AMPLICON) -> NOT_METAGENOMIC [high]
  PAPER TITLE: Characterization of the Nero Siciliano Pig Fecal Microbiota after a Liquid Whey-Supplemented Diet.
  evidence:    library_strategy: AMPLICON
  reasoning:   The study uses AMPLICON sequencing strategy (16S), not shotgun/WGS metagenomics, despite the gut body site being explicitly stated in the title and biome labels.

PRJNA918387  (METAGENOMIC/AMPLICON) -> NOT_METAGENOMIC [high]
  PAPER TITLE: TRPV6 deficiency attenuates stress and corticosterone-mediated exacerbation of alcohol-induced gut barrier dysfunction and systemic inflammation.
  evidence:    library_strategy: AMPLICON
  reasoning:   Although the study targets gut microbiota (explicit fecal samples from mouse), the library_strategy is AMPLICON, not shotgun/WGS metagenomics, making this a 16S amplicon study rather than shotgun metagenomic study.

PRJNA894380  (METATRANSCRIPTOMIC/AMPLICON) -> NOT_METAGENOMIC [high]
  PAPER TITLE: Metagenomic analysis of gut microbiota and antibiotic-resistant genes in Anser erythropus wintering at Shengjin and Caizi Lakes in China.
  evidence:    library_strategy: AMPLICON; library_source: METATRANSCRIPTOMIC
  reasoning:   The study used AMPLICON sequencing strategy (not WGS/shotgun) and METATRANSCRIPTOMIC library source (RNA, not community DNA), making it ineligible as shotgun metagenomic despite explicit gut/fecal body site confirmation.

PRJNA904819  (METAGENOMIC/AMPLICON) -> NOT_METAGENOMIC [high]
  PAPER TITLE: Biotin Deficiency Induces Intestinal Dysbiosis Associated with an Inflammatory Bowel Disease-like Phenotype.
  evidence:    library_strategy: AMPLICON
  reasoning:   The library_strategy is explicitly AMPLICON, which indicates 16S/marker gene sequencing rather than shotgun metagenomics (WGS/METAGENOMIC), regardless of the gut body site being explicitly stated in the biome label and sample titles.

PRJNA923763  (METATRANSCRIPTOMIC/RNA-Seq) -> NOT_METAGENOMIC [high]
  PAPER TITLE: Metatranscriptomic Analyses Reveal Important Roles of the Gut Microbiome in Primate Dietary Adaptation.
  evidence:    library_source: METATRANSCRIPTOMIC; library_strategy: RNA-Seq
  reasoning:   This is a metatranscriptomic (RNA) study using RNA-Seq, not shotgun metagenomic DNA sequencing, so it does not qualify as a WGS metagenomic study despite the gut microbiome context being explicit.

PRJNA884174  (METAGENOMIC/AMPLICON) -> NOT_METAGENOMIC [high]
  PAPER TITLE: Anti-PD-L1 Antibody and/or 17β-Estradiol Treatment Induces Changes in the Gut Microbiome in MC38 Colon Tumor Model.
  evidence:    library_strategy: AMPLICON
  reasoning:   The library_strategy is AMPLICON, which indicates 16S rRNA gene sequencing rather than shotgun metagenomics (WGS), despite the metagenomic framing in the title and biome labels.

PRJNA866156  (GENOMIC/AMPLICON) -> NOT_METAGENOMIC [high]
  PAPER TITLE: Intake of slow-digesting carbohydrates is related to changes in the microbiome and its functional pathways in growing rats with obesity induced by diet.
  evidence:    library_strategy: AMPLICON
  reasoning:   AMPLICON sequencing (16S rRNA) is explicitly stated and is not shotgun metagenomic sequencing, regardless of the paper's focus on gut microbiome changes in rats.

PRJNA733698  (METAGENOMIC/AMPLICON) -> NOT_METAGENOMIC [high]
  PAPER TITLE: Polystyrene microplastics induce gut microbiome and metabolome changes in Javanese medaka fish (Oryzias javanicus Bleeker, 1854).
  evidence:    library_strategy: AMPLICON
  reasoning:   The library_strategy is explicitly marked as AMPLICON, which is 16S/targeted amplicon sequencing, not shotgun metagenomic sequencing (WGS/METAGENOMIC), despite the biome label and paper title suggesting gut microbiome content.

PRJEB40819  (GENOMIC/AMPLICON) -> NOT_METAGENOMIC [high]
  PAPER TITLE: Microbiome-mediated fructose depletion restricts murine gut colonization by vancomycin-resistant Enterococcus.
  evidence:    library_strategy: AMPLICON
  reasoning:   The library_strategy is explicitly AMPLICON, which is 16S/amplicon sequencing, not shotgun/WGS metagenomic sequencing required for GUT_WGS classification.

PRJEB40849  (GENOMIC/AMPLICON) -> NOT_METAGENOMIC [high]
  PAPER TITLE: Microbiome-mediated fructose depletion restricts murine gut colonization by vancomycin-resistant Enterococcus.
  evidence:    library_strategy: AMPLICON
  reasoning:   The study uses AMPLICON sequencing strategy (16S), not shotgun/WGS metagenomic sequencing, so it does not qualify as a shotgun metagenomic study despite targeting the mouse gut microbiome.

======================================================================
CONFIRMED_GUT — do these titles look like real gut shotgun?
======================================================================

PRJEB29346  (METAGENOMIC/OTHER) -> GUT_WGS [high]
  PAPER TITLE: Co-diversification of an intestinal Mycoplasma and its salmonid host.
  evidence:    Paper title: 'Co-diversification of an intestinal Mycoplasma and its salmonid host'; library_source: 'METAGENOMIC'; host organism: Gadus morhua (Atlantic cod, a salmonid fish)
  reasoning:   The paper title explicitly states 'intestinal Mycoplasma' indicating gut-associated microbiota, library_source is METAGENOMIC (shotgun community DNA), and the host is a salmonid fish (Atlantic cod), confirming this is a shotgun metagenomic study of fish gut microbiome.

PRJEB59886  (METAGENOMIC/WGS) -> GUT_WGS [medium]
  PAPER TITLE: Co-diversification of an intestinal Mycoplasma and its salmonid host.
  evidence:    Paper title: 'Co-diversification of an intestinal Mycoplasma and its salmonid host'; library_source: METAGENOMIC; library_strategy: WGS; host organism: Salmo salar (salmon)
  reasoning:   The paper title explicitly mentions 'intestinal Mycoplasma' indicating gut-associated microbiome study, combined with confirmed shotgun metagenomic method (WGS + METAGENOMIC source) on a salmonid host, but body site is not stated in metadata fields and must be inferred from title.

PRJNA822929  (METAGENOMIC/POOLCLONE) -> GUT_WGS [high]
  PAPER TITLE: Multi-omics analyses reveal that the gut microbiome and its metabolites promote milk fat synthesis in Zhongdian yak cows.
  evidence:    Biome label: 'bovine gut metagenome'; Paper title states 'gut microbiome'; library_source: 'METAGENOMIC'; library_strategy: 'POOLCLONE' (shotgun approach)
  reasoning:   The biome label explicitly identifies this as gut metagenome, the paper title explicitly mentions gut microbiome, the library source is metagenomic (community DNA), and the pooling strategy indicates shotgun sequencing of the microbial community.

PRJEB40866  (GENOMIC/WGS) -> GUT_WGS [high]
  PAPER TITLE: Microbiome-mediated fructose depletion restricts murine gut colonization by vancomycin-resistant Enterococcus.
  evidence:    Isolation source(s): mouse cecum; library_strategy: WGS; library_source: GENOMIC; Paper title explicitly mentions 'murine gut colonization'
  reasoning:   WGS metagenomic sequencing (shotgun) of mouse cecal samples, which is an explicit gut-proxy body site, classifies this as a shotgun metagenomics study of an animal gut microbiome.

PRJNA876956  (METAGENOMIC/WGS) -> GUT_WGS [high]
  PAPER TITLE: Host diet shapes functionally differentiated gut microbiomes in sympatric speciation of blind mole rats in Upper Galilee, Israel.
  evidence:    ENA study title: 'gut metagenome'; Biome label: 'gut metagenome'; Isolation source: 'Gut sample'; library_source: 'METAGENOMIC'; library_strategy: 'WGS'
  reasoning:   Multiple explicit statements confirm shotgun metagenomic sequencing (WGS + METAGENOMIC library source) of gut microbiome from animal host Nannospalax galili.

PRJNA734720  (METAGENOMIC/WGS) -> GUT_WGS [high]
  PAPER TITLE: Dynamics of the gut microbiota in rats after hypobaric hypoxia exposure.
  evidence:    Isolation source: 'feces'; library_source: 'METAGENOMIC'; library_strategy: 'WGS'; Paper title mentions 'gut microbiota in rats'
  reasoning:   The study explicitly reports fecal samples analyzed via shotgun metagenomic sequencing (WGS) from rats, and the paper title explicitly names the gut microbiota as the subject.

In [52]:
import pandas as pd, re, glob, time
from src.ena_fetcher import fetch_runs_for_study, resolve_host_species, get_taxonomy

# ---- rebuild acc_df from batch 2's CSVs (batch 4-6) ----
mmc = pd.concat([pd.read_csv(f) for f in sorted(glob.glob("../results/batch[4-6].csv"))],
                ignore_index=True)
acc_rows = []
for _, r in mmc[mmc["accessions"].notna()].iterrows():
    for acc in [a.strip() for a in str(r["accessions"]).split(";") if re.match(r'PRJ[ENDB][A-Z]\d+', a.strip())]:
        acc_rows.append({"study_accession": acc, "pmid": r["pmid"], "paper_title": r["title"],
                         "journal": r["journal"], "pub_year": r["pub_year"], "doi": r["doi"], "authors": r["authors"]})
acc_df = pd.DataFrame(acc_rows).drop_duplicates("study_accession")

# ---- confirmed studies + b2 fetch results ----
import json
llm = pd.read_csv("../results/llm_classified_b2.tsv", sep="\t")
confirmed = llm[llm["tier"] == "CONFIRMED_GUT"].set_index("study_accession")
with open("../results/pubmed_new_classified_b2.json") as f:
    fetched = json.load(f)
paper_lookup = acc_df.set_index("study_accession").to_dict("index")
print(f"Confirmed to finalize: {len(confirmed)}")

Confirmed to finalize: 56

In [53]:
rows = []
for i, acc in enumerate(confirmed.index):
    if i % 20 == 0: print(f"{i}/{len(confirmed)}")
    f = fetched.get(acc, {})
    tax_id = f.get("host_tax_id")
    tax = get_taxonomy(str(tax_id)) if tax_id else {}
    time.sleep(0.2)
    p = paper_lookup.get(acc, {})
    lr = confirmed.loc[acc]
    rows.append({
        "study_accession": acc, "host_species": f.get("host_species"), "host_tax_id": tax_id,
        "body_site": f.get("body_site",""), "country": f.get("country",""),
        "n_samples": f.get("n_samples"), "library_strategy": f.get("library_strategy"),
        "library_source": f.get("library_source"), "data_source": "pubmed_metagenom_b2",
        "pmid": p.get("pmid"), "paper_title": p.get("paper_title"), "doi": p.get("doi"),
        "journal": p.get("journal"), "pub_year": p.get("pub_year"),
        "first_author": str(p.get("authors")).split(";")[0].strip() if p.get("authors") else None,
        "last_author": str(p.get("authors")).split(";")[-1].strip() if p.get("authors") else None,
        "classification_final": "YES",
        "host_kingdom": tax.get("kingdom"), "host_phylum": tax.get("phylum"),
        "host_class": tax.get("class"), "host_order": tax.get("order"),
        "host_family": tax.get("family"), "host_genus": tax.get("genus"),
        "host_species_taxonomy": tax.get("species"),
        "llm_confidence": lr["confidence"], "llm_body_site_signal": lr["body_site_signal"], "llm_evidence": lr["evidence"],
    })
new_rows = pd.DataFrame(rows)
print(f"Built {len(new_rows)} rows, host_class filled: {new_rows['host_class'].notna().sum()}")

0/56
20/56
40/56
Built 56 rows, host_class filled: 29

In [54]:
yes_catalog = pd.read_csv("../results/yes_catalog.tsv", sep="\t")
before = len(yes_catalog)
truly_new = new_rows[~new_rows["study_accession"].isin(set(yes_catalog["study_accession"]))]
merged = pd.concat([yes_catalog, truly_new], ignore_index=True).drop_duplicates("study_accession", keep="first")
merged.to_csv("../results/yes_catalog.tsv", sep="\t", index=False)
truly_new.to_csv("../results/added_pubmed_metagenom_b2.tsv", sep="\t", index=False)
print(f"Catalog: {before} -> {len(merged)} (+{len(merged)-before})")
print(f"New samples: {truly_new['n_samples'].sum():,} | Total: {merged['n_samples'].sum():,}")
print(truly_new["host_class"].value_counts().to_string())

Catalog: 988 -> 1044 (+56)
New samples: 1,595 | Total: 107,009
host_class
Mammalia         21
Insecta           3
Aves              3
Malacostraca      1
Holothuroidea     1

In [55]:
import pandas as pd

cat = pd.read_csv("../results/yes_catalog.tsv", sep="\t")

def pct(n, d): return f"{100*n/d:.0f}%" if d else "—"

print("="*64)
print("ANIMAL GUT WGS METAGENOMICS CATALOG — FULL SUMMARY")
print("="*64)

# ---------- scale ----------
print(f"\n■ SCALE")
print(f"  Confirmed WGS gut studies : {len(cat):,}")
print(f"  Total samples             : {cat['n_samples'].sum():,}")
print(f"  Median samples / study    : {cat['n_samples'].median():.0f}")
print(f"  Largest study             : {cat['n_samples'].max():,} samples")

# ---------- provenance (how studies were found) ----------
print(f"\n■ HOW STUDIES WERE FOUND (data_source)")
print(cat['data_source'].value_counts().to_string())
# group the pubmed_metagenom batches for a cleaner headline
sweep = cat['data_source'].astype(str).str.startswith('sweep').sum()
metag = cat['data_source'].astype(str).str.startswith('pubmed_metagenom').sum()
print(f"\n  → via host-based sweep      : {sweep}")
print(f"  → via metagenom* expansion  : {metag}")
print(f"  → via original pipeline     : {len(cat) - sweep - metag}")

# ---------- literature coverage ----------
print(f"\n■ LITERATURE METADATA")
for col, label in [("abstract","with abstract"), ("pmid","with PMID"),
                   ("paper_title","with title"), ("doi","with DOI")]:
    if col in cat.columns:
        n = cat[col].notna().sum()
        print(f"  {label:18s}: {n:>4}  ({pct(n,len(cat))})")

# ---------- taxonomy coverage ----------
print(f"\n■ HOST TAXONOMY COVERAGE")
for rank in ["host_kingdom","host_phylum","host_class","host_order","host_family","host_genus","host_species_taxonomy"]:
    if rank in cat.columns:
        n = cat[rank].notna().sum()
        print(f"  {rank.replace('host_',''):18s}: {n:>4}  ({pct(n,len(cat))})")

# ---------- diversity ----------
print(f"\n■ TAXONOMIC BREADTH (distinct taxa represented)")
for rank in ["host_class","host_order","host_family","host_genus","host_species_taxonomy"]:
    if rank in cat.columns:
        print(f"  distinct {rank.replace('host_',''):16s}: {cat[rank].nunique()}")

# ---------- host class breakdown (with normalization note) ----------
print(f"\n■ HOST CLASS BREAKDOWN")
cls = cat['host_class'].value_counts()
print(cls.to_string())
# flag the known normalization issues so they're visible
issues = [c for c in cls.index if c in ("Actinopteri","Actinopterygii")]
if len(issues) > 1:
    print(f"  ⚠ note: {issues} are the same class (ray-finned fish) — needs merging")
if "Magnoliopsida" in cls.index:
    print(f"  ⚠ note: Magnoliopsida is a plant class — false positive to remove")

# ---------- geography ----------
if "country" in cat.columns:
    print(f"\n■ TOP COUNTRIES")
    # strip the messy 'missing: ...' values for a cleaner view
    clean = cat['country'].astype(str).str.split(':').str[0].str.strip()
    clean = clean[~clean.str.lower().isin(['missing','nan',''])]
    print(clean.value_counts().head(8).to_string())

# ---------- benchmark ----------
print(f"\n■ vs AnimalMetagenome DB (2022)")
print(f"  Their studies : 1,044        Yours : {len(cat):,}")
print(f"  Their samples : 10,672       Yours : {cat['n_samples'].sum():,}")
print(f"  Sample fold-difference       : {cat['n_samples'].sum()/10672:.1f}x")

# ---------- data quality flags ----------
print(f"\n■ KNOWN CLEANUP ITEMS")
print(f"  Studies missing host_class   : {cat['host_class'].isna().sum()}")
if "llm_confidence" in cat.columns:
    lowconf = (cat['llm_confidence']=='low').sum()
    print(f"  Low-confidence classifications: {lowconf}")
print(f"  (taxonomy backfill + class normalization pending)")

================================================================
ANIMAL GUT WGS METAGENOMICS CATALOG — FULL SUMMARY
================================================================

■ SCALE
  Confirmed WGS gut studies : 1,044
  Total samples             : 107,009
  Median samples / study    : 36
  Largest study             : 1,000 samples

■ HOW STUDIES WERE FOUND (data_source)
data_source
ena_only               483
pubmed                 313
pubmed_metagenom_b1    121
pubmed_postdoc          71
pubmed_metagenom_b2     56

  → via host-based sweep      : 0
  → via metagenom* expansion  : 177
  → via original pipeline     : 867

■ LITERATURE METADATA
  with abstract     :  384  (37%)
  with PMID         :  561  (54%)
  with title        :  316  (30%)
  with DOI          :  177  (17%)

■ HOST TAXONOMY COVERAGE
  kingdom           :  729  (70%)
  phylum            :  729  (70%)
  class             :  728  (70%)
  order             :  725  (69%)
  family            :  726  (70%)
  genus             :  712  (68%)
  species_taxonomy  :  719  (69%)

■ TAXONOMIC BREADTH (distinct taxa represented)
  distinct class           : 14
  distinct order           : 50
  distinct family          : 95
  distinct genus           : 132
  distinct species_taxonomy: 179

■ HOST CLASS BREAKDOWN
host_class
Mammalia          543
Aves               86
Insecta            40
Actinopteri        34
Lepidosauria        5
Actinopterygii      4
Malacostraca        3
Chondrichthyes      3
Holothuroidea       3
Magnoliopsida       2
Gastropoda          2
Amphibia            1
Arachnida           1
Branchiopoda        1
  ⚠ note: ['Actinopteri', 'Actinopterygii'] are the same class (ray-finned fish) — needs merging
  ⚠ note: Magnoliopsida is a plant class — false positive to remove

■ TOP COUNTRIES
country
China             311
USA               143
Japan              49
United Kingdom     28
Spain              27
Germany            26
Denmark            23
Canada             20

■ vs AnimalMetagenome DB (2022)
  Their studies : 1,044        Yours : 1,044
  Their samples : 10,672       Yours : 107,009
  Sample fold-difference       : 10.0x

■ KNOWN CLEANUP ITEMS
  Studies missing host_class   : 316
  Low-confidence classifications: 0
  (taxonomy backfill + class normalization pending)

In [56]:
import pandas as pd
cat = pd.read_csv("../results/yes_catalog.tsv", sep="\t")

# underrepresented = everything that isn't the dominant Mammalia/Aves
common = ["Mammalia", "Aves"]
underrep = cat[~cat["host_class"].isin(common) & cat["host_class"].notna()].copy()

print(f"Underrepresented-class studies already in catalog: {len(underrep)}\n")
print("By class:")
print(underrep["host_class"].value_counts().to_string())

print("\n" + "="*60)
print("TITLES BY CLASS:")
print("="*60)
for cls in underrep["host_class"].value_counts().index:
    print(f"\n--- {cls} ---")
    for _, r in underrep[underrep["host_class"]==cls].iterrows():
        sp = r.get("host_species_taxonomy") or r.get("host_species") or "?"
        title = r.get("paper_title")
        title = title if pd.notna(title) else "(ENA data-only, no paper title)"
        print(f"  {r['study_accession']}  [{sp}]")
        print(f"    {title}")

Underrepresented-class studies already in catalog: 99

By class:
host_class
Insecta           40
Actinopteri       34
Lepidosauria       5
Actinopterygii     4
Malacostraca       3
Chondrichthyes     3
Holothuroidea      3
Magnoliopsida      2
Gastropoda         2
Amphibia           1
Arachnida          1
Branchiopoda       1

============================================================
TITLES BY CLASS:
============================================================

--- Insecta ---
  PRJNA599288  [cerana]
    Genetic divergence and functional convergence of gut bacteria between the Eastern honey bee Apis cerana and the Western honey bee Apis mellifera.
  PRJNA598094  [Apis cerana]
    Vast Differences in Strain-Level Diversity in the Gut Microbiota of Two Closely Related Honey Bee Species.
  PRJNA1428229  [japonica]
    Habitat-driven variation in gut microbiome composition and function of the pygmy grasshopper (Tetrix japonica) across diverse ecosystems in China.
  PRJNA599289  [nan]
    Genetic divergence and functional convergence of gut bacteria between the Eastern honey bee Apis cerana and the Western honey bee Apis mellifera.
  PRJEB66261  [Pycnoscelus surinamensis]
    (ENA data-only, no paper title)
  PRJNA1232403  [Apis mellifera]
    (ENA data-only, no paper title)
  PRJDB38794  [Apis cerana]
    (ENA data-only, no paper title)
  PRJNA1302757  [occipitalis]
    Gut Microbiome Differences Across Mixed-Sex and Female-Only Social Rearing Regimes in Female Field Crickets Teleogryllus occipitalis (Orthoptera: Gryllidae).
  PRJNA475948  [Cortaritermes fulviceps]
    Neotropical termite microbiomes as sources of novel plant cell wall degrading enzymes.
  PRJNA744378  [Rhodnius prolixus]
    Exposure to Trypanosoma parasites induces changes in the microbiome of the Chagas disease vector Rhodnius prolixus.
  PRJNA1066198  [Bombus impatiens]
    Changes in bumblebee queen gut microbiotas during and after overwintering diapause.
  PRJNA1067415  [Cotesia vestalis]
    Characterization of larval gut microbiota of two endoparasitoid wasps associated with their common host, Plutella xylostella (Linnaeus) (Lepidoptera: Plutellidae).
  PRJDB20286  [Locusta migratoria]
    Behavioural phase transitions in the migratory locust, Locusta migratoria, are related to changes in the gut bacterial composition.
  PRJNA1234694  [abbreviatus]
    Gut microbial community structure of the adult citrus root weevil Diaprepes abbreviatus.
  PRJNA1006316  [Apis mellifera]
    Neonicotinoid-induced signature dysbiosis identified via metagenomic sequencing of the honey bee gut microbiome.
  PRJNA1297587  [Diaprepes abbreviatus]
    Gut microbial community structure of the adult citrus root weevil Diaprepes abbreviatus.
  PRJNA509211  [Cryptotermes secundus]
    Ecological specificity of the metagenome in a set of lower termite species supports contribution of the microbiome to adaptation of the host.
  PRJNA751718  [Vespa mandarinia]
    Shotgun metagenomics reveals the gut microbial diversity and functions in Vespa mandarinia (Hymenoptera: Vespidae) at multiple life stages.
  PRJNA1067380  [Cotesia vestalis]
    Characterization of larval gut microbiota of two endoparasitoid wasps associated with their common host, Plutella xylostella (Linnaeus) (Lepidoptera: Plutellidae).
  PRJNA1026073  [Plutella xylostella]
    Whole-genome sequence of Enterobacter hormaechei, isolate jjbc recovered from the gut of Plutella xylostella feeding on cabbage.
  PRJNA645015  [Apis mellifera]
    Honey bee genetics shape the strain-level structure of gut microbiota in social transmission.
  PRJDB20287  [Locusta migratoria]
    Behavioural phase transitions in the migratory locust, Locusta migratoria, are related to changes in the gut bacterial composition.
  PRJNA977416  [Apis mellifera]
    The Response of the Honey Bee Gut Microbiota to Nosema ceranae Is Modulated by the Probiotic Pediococcus acidilactici and the Neonicotinoid Thiamethoxam.
  PRJNA1157353  [Apis cerana]
    Evolution of gut microbiota across honeybee species revealed by comparative metagenomics.
  PRJNA1044797  [Bombus impatiens]
    Bumble bee gut microbial community structure differs between species and commercial suppliers, but metabolic potential remains largely consistent.
  PRJNA1033630  [Apis mellifera]
    Gut microbiome metagenomic sequences of honey bees (Apis mellifera) exposed to crops.
  PRJNA1124990  [Apis mellifera]
    Gut microbiome metagenomic sequences of honey bees (Apis mellifera) exposed to crops.
  PRJNA999720  [Apis mellifera]
    Gut microbiome metagenomic sequences of honey bees (Apis mellifera) exposed to crops.
  PRJNA560329  [Labiotermes labralis]
    Unveiling lignocellulolytic potential: a genomic exploration of bacterial lineages within the termite gut.
  PRJNA732531  [Glyptotermes sp.]
    Unveiling lignocellulolytic potential: a genomic exploration of bacterial lineages within the termite gut.
  PRJNA1097789  [Drosophila melanogaster]
    A diverse gut virome in natural populations of Drosophila melanogaster.
  PRJNA1264687  [Protaetia brevitarsis]
    Characterization of DNA Viruses in Hindgut Contents of Protaetia brevitarsis Larvae.
  PRJNA805352  [Cnaphalocrocis medinalis]
    Metagenomic Analyses Reveal Gut Microbial Profiles of Cnaphalocrocis medinalis Driven by the Infection of Baculovirus CnmeGV.
  PRJNA1043846  [Clanis bilineata]
    Enterococcus casseliflavus regulates amino acid metabolism in edible insect Clanis bilineata tsingtauica: a functional metagenomics study.
  PRJNA685398  [Apis mellifera]
    Apis mellifera filamentous virus from a honey bee gut microbiome survey in Hungary.
  PRJNA987703  [Bathycoelia distincta]
    Pantoea bathycoeliae sp. nov and Sodalis sp. are core gut microbiome symbionts of the two-spotted stink bug.
  PRJNA635664  [Labiotermes labralis]
    A holobiont approach towards polysaccharide degradation by the highly compartmentalised gut system of the soil-feeding higher termite Labiotermes labralis.
  PRJNA801070  [Zophobas morio]
    Insights into plastic biodegradation: community composition and functional capabilities of the superworm (Zophobas morio) microbiome in styrofoam feeding trials.
  PRJNA699677  [Bombus terrestris]
    Gut microbiome drives individual memory variation in bumblebees.
  PRJNA193472  [Macrotermes natalensis]
    Fungiculture in Termites Is Associated with a Mycolytic Gut Bacterial Community.

--- Actinopteri ---
  PRJEB41657  [Salmo salar]
    (ENA data-only, no paper title)
  PRJNA782061  [Ctenopharyngodon idella]
    (ENA data-only, no paper title)
  PRJNA695396  [Hypophthalmichthys nobilis]
    (ENA data-only, no paper title)
  PRJNA1011357  [Cyprinus carpio]
    (ENA data-only, no paper title)
  PRJNA935053  [Chanodichthys erythropterus]
    (ENA data-only, no paper title)
  PRJEB40990  [Salmo salar]
    (ENA data-only, no paper title)
  PRJNA806371  [Danio rerio]
    (ENA data-only, no paper title)
  PRJNA825732  [Anguilla anguilla]
    (ENA data-only, no paper title)
  PRJNA1171181  [Siniperca chuatsi]
    (ENA data-only, no paper title)
  PRJNA597688  [Siganus canaliculatus]
    (ENA data-only, no paper title)
  PRJNA913689  [Larimichthys polyactis]
    (ENA data-only, no paper title)
  PRJEB52754  [Gasterosteus aculeatus]
    (ENA data-only, no paper title)
  PRJNA974094  [Danio rerio]
    (ENA data-only, no paper title)
  PRJNA1175391  [Micropterus salmoides]
    (ENA data-only, no paper title)
  PRJNA945347  [Ctenopharyngodon idella]
    (ENA data-only, no paper title)
  PRJNA947914  [Salmo salar]
    (ENA data-only, no paper title)
  PRJEB51815  [Salmo salar]
    (ENA data-only, no paper title)
  PRJNA1110616  [Larimichthys crocea]
    (ENA data-only, no paper title)
  PRJNA482836  [Piaractus mesopotamicus]
    (ENA data-only, no paper title)
  PRJNA1029302  [Kyphosus sydneyanus]
    (ENA data-only, no paper title)
  PRJNA1393111  [Ictalurus punctatus]
    (ENA data-only, no paper title)
  PRJNA434147  [Hypomesus transpacificus]
    (ENA data-only, no paper title)
  PRJNA656314  [Danio rerio]
    (ENA data-only, no paper title)
  PRJNA1147314  [Danio rerio]
    (ENA data-only, no paper title)
  PRJNA1254096  [Diptychus maculatus]
    Shotgun metagenomics analysis of gut microbiota of three indigenous fish species from the Kizil River, Xinjiang.
  PRJNA948893  [Acrossocheilus fasciatus]
    (ENA data-only, no paper title)
  PRJNA433811  [Salmo salar]
    (ENA data-only, no paper title)
  PRJNA804100  [Micropterus salmoides]
    (ENA data-only, no paper title)
  PRJEB42464  [Oncorhynchus mykiss]
    (ENA data-only, no paper title)
  PRJNA945365  [Micropterus salmoides]
    (ENA data-only, no paper title)
  PRJEB27498  [Gadus morhua]
    Closely-related Photobacterium strains comprise the majority of bacteria in the gut of migrating Atlantic cod (Gadus morhua).
  PRJNA1141435  [Perca flavescens]
    (ENA data-only, no paper title)
  PRJNA1054761  [Danio rerio]
    Magnolia Officinalis Alcohol Extract Alleviates the Intestinal Injury Induced by Polygala Tenuifolia Through Regulating the PI3K/AKT/NF-κB Signaling Pathway and Intestinal Flora.
  PRJNA916642  [Hippocampus abdominalis]
    Edwardsiella piscicida infection reshapes the intestinal microbiome and metabolome of big-belly seahorses: mechanistic insights of synergistic actions of virulence factors.

--- Lepidosauria ---
  PRJEB76898  [Podarcis muralis]
    Grass supplementation to a pellet-based diet fails to enrich gut microbiomes with wild-like functions in captive-bred hares.
  PRJNA1108898  [Trimeresurus stejnegeri]
    Differences in Gut Microbial Composition and Characteristics Among Three Populations of the Bamboo Pitviper (Viridovipera stejnegeri).
  PRJNA1108923  [Trimeresurus stejnegeri]
    Differences in Gut Microbial Composition and Characteristics Among Three Populations of the Bamboo Pitviper (Viridovipera stejnegeri).
  PRJNA1108955  [Lycodon rufozonatus]
    How Host Phylogeny, Diet, and Habitat Affect Gut Microbial Diversity in Wild Snakes.
  PRJNA1088789  [Pareas formosensis]
    The Influence of Diet on the Composition and Function of Gut Microbiota in Four Snake Species.

--- Actinopterygii ---
  PRJEB30661  [putitora]
    Gut microbiome of endangered Tor putitora (Ham.) as a reservoir of antibiotic resistance genes and pathogens associated with fish health.
  PRJNA1064611  [rhombeus]
    The piranha gut microbiome provides a selective lens into river water biodiversity.
  PRJEB64334  [salar]
    (ENA data-only, no paper title)
  PRJEB59225  [morhua]
    The Microbiota of the Outer Gut Mucus Layer of the Migrating Northeast Arctic Cod (Gadus morhua) as Determined by Shotgun DNA Sequencing.

--- Malacostraca ---
  PRJNA865396  [Eriocheir sinensis]
    (ENA data-only, no paper title)
  PRJNA1210771  [Euphausia superba]
    Metabolic potentials of the gut microbes in Antarctic krill (Euphausia superba).
  PRJNA862309  [Penaeus vannamei]
    Integration of metagenomic and metabolomic insights into the effects of microcystin-LR on intestinal microbiota of Litopenaeus vannamei.

--- Chondrichthyes ---
  PRJNA311136  [Pristis pectinata]
    (ENA data-only, no paper title)
  PRJNA492361  [Pristis pectinata]
    (ENA data-only, no paper title)
  PRJDB14449  [Chimaeridae]
    (ENA data-only, no paper title)

--- Holothuroidea ---
  PRJNA1061805  [Holothuria glaberrima]
    Sea cucumber (Holothuria glaberrima) intestinal microbiome dataset from Puerto Rico, generated by shotgun sequencing.
  PRJNA1233886  [Holothuria glaberrima]
    Intestinal microbiome profile of the brown rock sea cucumber (Holothuria glaberrima) using ITS and 16S rDNA amplicons from direct mechanical, enzymatic, and chemical metagenomic extraction.
  PRJNA518164  [Apostichopus japonicus]
    Genomic and Metagenomic Insights Into the Microbial Community in the Regenerating Intestine of the Sea Cucumber Apostichopus japonicus.

--- Magnoliopsida ---
  PRJNA358755  [Panda]
    Comparative Study of Gut Microbiota in Wild and Captive Giant Pandas (Ailuropoda melanoleuca).
  PRJNA723631  [Raphanus sativus]
    (ENA data-only, no paper title)

--- Gastropoda ---
  PRJEB21599  [ater]
    Metagenomic Analysis of the Gut Microbiome of the Common Black Slug Arion ater in Search of Novel Lignocellulose Degrading Enzymes.
  PRJNA1211045  [Bulinus sp.]
    Freshwater snail faecal metagenomes reveal environmental reservoirs of antimicrobial resistance genes across two continents.

--- Amphibia ---
  PRJNA601807  [Microhyla fissipes]
    (ENA data-only, no paper title)

--- Arachnida ---
  PRJNA750644  [Pardosa agraria]
    Diversity and Function of Wolf Spider Gut Microbiota Revealed by Shotgun Metagenomics.

--- Branchiopoda ---
  PRJNA906625  [Daphnia magna]
    The hologenome of Daphnia magna reveals possible DNA methylation and microbiome-mediated evolution of the host genome.

In [57]:
import pandas as pd
sweep = pd.read_csv("../results/sweep_enriched.tsv", sep="\t")
print("Columns:", sweep.columns.tolist())
print(f"\nTotal sweep studies: {len(sweep)}")
print(f"\nCurrent verdict breakdown:")
print(sweep["gut_verdict_final"].value_counts().to_string())
print(f"\nSample row:")
print(sweep[["study_accession","clade","host","biome_labels","paper_title"]].head(3).to_string())

Columns: ['study_accession', 'gut_verdict', 'clade', 'host', 'n_runs', 'n_gut_samples', 'n_notgut_samples', 'n_ambiguous_samples', 'biome_labels', 'body_sites', 'is_multihost_survey', 'paper_title', 'abstract', 'pmid', 'gut_verdict_final']

Total sweep studies: 64

Current verdict breakdown:
gut_verdict_final
KEEP             37
DROP             15
MANUAL_REVIEW    12

Sample row:
  study_accession                  clade                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             host                                                                                                                                                                                                                                                  biome_labels                                                                    paper_title
0      PRJEB17686                Lizards  Aloeides pallida; Aloeides thyra; Anthene sp.;Anthene; Chilades pandava;Luthrodes pandava; Chrysoritis chrysantas; Chrysoritis thysbe; Crudaria wykehami; Durbania amakosa; Eooxylides tharis; Eumaeus sp.;Eumaeus; Feniseca tarquinius; Flos sp.;Flos; Jalmenus daemeli; Jalmenus evagoras; Lachnocnema bibulus; Logania marmorata; Luthrodes pandava; Lycaena; Lycaenidae sp.;Papilionoidea;Lycaenidae; Maculinea alcon alcon;Phengaris alcon;Phengaris alcon alcon; Miletus biggsii; Rapala iarbus; Spalgis epius; Strymon melinus; Surendra vivarna; Thestor yildizae; Trimenia argyroplaga                                                                                                                                                                                                                                         insect gut metagenome  Microbial communities of lycaenid butterflies do not correlate with host diet
1      PRJEB25617  Turtles and tortoises                                                                                                                                                                                                                                                                                                                                                                                                                                                                Canis lupus familiaris; Cebus; Eunectes; Felis catus; Folivora; Gallus gallus; Homo sapiens; Platyrrhini; Psittacidae; Testudines                                          gut metagenome; human gut metagenome; human nasopharyngeal metagenome; human oral metagenome; human skin metagenome; indoor metagenome; metagenome; oral metagenome; oral-nasopharyngeal metagenome; skin metagenome                    Home chemical and microbial transitions across urbanization
2      PRJEB11419  Turtles and tortoises                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Canis lupus familiaris; Felis catus; Homo sapiens; Not applicable; Testudines; metagenome  feces metagenome; food metagenome; gut metagenome; human blood metagenome; human eye metagenome; human gut metagenome; human metagenome; human nasopharyngeal metagenome; human oral metagenome; human skin metagenome; human vaginal metagenome; metagenome                                                           American Gut Project

In [58]:
import importlib
import src.classify_sweep_llm
importlib.reload(src.classify_sweep_llm)
from src.classify_sweep_llm import run 

host_sweep_llm = run()

Sweep studies to re-classify: 64
Classifying 64...

  0/64
  10/64
  20/64
  30/64
  40/64
  50/64
  60/64

====================================================
SWEEP RE-CLASSIFICATION (LLM)
====================================================
tier
EXCLUDED         37
CONFIRMED_GUT    23
REVIEW            4

verdict x confidence:
confidence       high  low  medium
verdict
GUT_WGS            16    0       7
NOT_GUT            14    0       1
NOT_METAGENOMIC    14    0       0
NOT_TARGET          8    0       0
UNCERTAIN           0    4       0

OLD verdict -> NEW tier (did the LLM change calls?):
tier           CONFIRMED_GUT  EXCLUDED  REVIEW
old_verdict
DROP                       4         9       2
KEEP                      18        17       2
MANUAL_REVIEW              1        11       0

CONFIRMED GUT after LLM: 23
clade
Penguins                   12
Bats                        4
Annelids                    3
Amphibians (all)            1
Ray-finned fish (broad)     1
Beetles                     1
Sirenians                   1

Newly EXCLUDED that old logic had KEPT (caught mislabels):
  PRJEB17686 [Lizards] -> NOT_TARGET: The tagged animal (lizards) is not present in this study; the study is entirely about butterfly gut microbiomes, making lizards incidental (absent) rather than a genuine subject.
  PRJEB25617 [Turtles and tortoises] -> NOT_TARGET: This is a broad urbanization-focused multi-host microbiome survey where Testudines represent an incidental minor host among primarily human and domestic animal subjects, making it not a targeted gut study of the tagged clade.
  PRJEB11419 [Turtles and tortoises] -> NOT_TARGET: This is a global ocean microbiome study where the turtle samples are incidental to the primary focus on marine microbial biosynthetic potential, making Testudines a trace host rather than a genuine target.
  PRJNA312520 [Gastropods (beyond current)] -> NOT_TARGET: While this is genuinely a gut WGS metagenomic study, gastropods are not the primary subject—lizards are—making gastropods an incidental host in a multi-host survey.
  PRJNA1252374 [Nematodes] -> NOT_METAGENOMIC: The study uses 16S amplicon-based methods rather than shotgun or whole-genome sequencing approaches, which disqualifies it from the WGS metagenomic classification despite the gut microbiome subject matter.
  PRJEB36857 [Cetaceans] -> NOT_TARGET: This is a human microbiome study where the tagged cetacean clade appears incidental or erroneous in the host list; the study is not primarily about cetacean gut microbiomes.
  PRJNA325503 [Bats] -> NOT_METAGENOMIC: This study uses amplicon sequencing (minibarcoding) rather than shotgun WGS metagenomics, making it ineligible despite the gut origin of samples (guano).
  PRJNA84289 [Bats] -> NOT_METAGENOMIC: This is a 16S rRNA amplicon study, not shotgun or whole-genome sequencing metagenomic study.
  PRJNA464362 [Bats] -> NOT_TARGET: This is a large multi-host survey where bats are one of many incidental organisms sampled in an Amazonian biodiversity metabarcoding study, not a dedicated gut microbiome study of bats.
  PRJNA464356 [Bats] -> NOT_METAGENOMIC: This is a cultivar genomic profiling study of individual bacterial taxa, not a shotgun metagenomic survey of any animal's microbiome.
  PRJNA768434 [Mosquitoes] -> NOT_METAGENOMIC: This is an amplicon-based study, not a shotgun/WGS metagenomic study, so it does not meet the inclusion criteria regardless of the gut body site.
  PRJNA750668 [Butterflies and moths] -> NOT_TARGET: While the study includes gut metagenomics and some insect hosts, it is primarily a plant microbiota study with insects as incidental samples, making Lepidoptera (the tagged clade) a trace host rather than a genuine study subject.
  PRJNA810306 [Sirenians] -> NOT_METAGENOMIC: This is a 16S rRNA amplicon study, not a shotgun/WGS metagenomic study, despite being labeled as gut metagenome in the biome field.
  PRJNA887424 [Sirenians] -> NOT_TARGET: This is a multi-host herbivorous microbiome study where sirenians are not among the sampled hosts, making the tagged clade incidental/absent rather than a genuine study subject.
  PRJNA1200941 [Penguins] -> NOT_METAGENOMIC: This is a 16S rRNA amplicon study, not a shotgun/WGS metagenomic study, despite being a multi-host gut microbiome survey.
  PRJNA555609 [Penguins] -> NOT_GUT: This is a viral metagenomic study focused on virus discovery in penguins, not a shotgun/WGS study of gut microbiota composition and function; body site is unspecified and likely non-gut.
  PRJNA422502 [Termites and cockroaches] -> NOT_METAGENOMIC: While this is a genuine gut microbiota study of termites, the methodology is 16S rRNA amplicon sequencing rather than whole-genome shotgun (WGS) metagenomic sequencing.

Saved -> ../results/sweep_llm_classified.tsv

In [60]:
import pandas as pd

s = pd.read_csv("../results/sweep_llm_classified.tsv", sep="\t")
sweep = pd.read_csv("../results/sweep_enriched.tsv", sep="\t")

review = s[s["tier"] == "REVIEW"].merge(
    sweep[["study_accession", "host", "biome_labels", "body_sites"]],
    on="study_accession", how="left"
)

for _, r in review.iterrows():
    print(f"\n{'='*60}")
    print(f"{r['study_accession']}  [{r['clade']}]  — {r['verdict']} ({r['confidence']})")
    print(f"  title:    {r['paper_title']}")
    print(f"  host:     {str(r['host'])[:200]}")
    print(f"  biome:    {str(r['biome_labels'])[:200]}")
    print(f"  body:     {r['body_sites']}")
    print(f"  evidence: {r['evidence']}")
    print(f"  reasoning: {r['reasoning']}")

============================================================
PRJNA244498  [Gastropods (beyond current)]  — UNCERTAIN (low)
  title:    Intestinal nematodes identification
  host:     nan
  biome:    Caenorhabditis elegans; Crenosoma vulpis; Heligmonoides; Mastophorus; Mastophorus muris; Nematoda; Nippostrongylus; Parascaris equorum; Strongyloidea; Syphacia; Toxocara cati; Trichinella nativa; Tric
  body:     nan
  evidence: Title mentions 'Intestinal nematodes identification' suggesting gut-associated parasites, but biome labels list primarily nematode taxa (Caenorhabditis elegans, Crenosoma vulpis, etc.) rather than microbiome organisms. No host organism, body site, or methodology information provided. No abstract available.
  reasoning: Insufficient metadata to determine if this is a shotgun/WGS metagenomic study of animal gut microbiota versus a parasitology or taxonomic identification study of intestinal nematodes themselves.

============================================================
PRJNA525109  [Bats]  — UNCERTAIN (low)
  title:    Bat community identification: comparing genetic efficacy vs traditional survey techniques.
  host:     Chiroptera
  biome:    gut metagenome
  body:     nan
  evidence: Biome label lists 'gut metagenome' but paper title focuses on 'community identification: comparing genetic efficacy vs traditional survey techniques' with no explicit mention of gut microbiome analysis. No abstract provided. Host is Chiroptera (bats), which matches the tagged clade.
  reasoning: The gut metagenome label suggests this may be a gut study, but the title emphasizes taxonomic identification methodology rather than microbiome characterization, and lack of abstract makes it impossible to confirm the study is genuinely about bat gut microbiome versus potentially using gut samples only as a specimen source for species identification.

============================================================
PRJNA802710  [Mosquitoes]  — UNCERTAIN (low)
  title:    nan
  host:     Culicidae
  biome:    Cell fusing agent virus; Phasivirus phasiense; Tesano Aedes virus
  body:     nan
  evidence: Host organism is Culicidae (mosquitoes); biome labels list only viral species (Cell fusing agent virus, Phasivirus phasiense, Tesano Aedes virus) with no body site information provided; no paper title, abstract, or body site metadata available to confirm whether this is a gut study or what the primary focus is.
  reasoning: Without title, abstract, or explicit body site information, and with only viral biome labels present, it is impossible to determine whether this is a shotgun metagenomic study of mosquito gut microbiota versus some other mosquito-associated virome study.

============================================================
PRJNA901878  [Bats]  — UNCERTAIN (low)
  title:    nan
  host:     Ailurus fulgens; Anourosorex squamipes; Aonyx cinereus; Apodemus agrarius; Apodemus draco; Apodemus nigrus; Apodemus peninsulae; Aselliscus stoliczkanus; Caracal caracal; Ceratotherium simum; Cercopit
  biome:    viral metagenome
  body:     nan
  evidence: Study lists 40+ diverse mammalian hosts (bats, rodents, carnivores, primates, ungulates) with biome label 'viral metagenome'; no paper title, abstract, or explicit body site information provided; flagged as multi-host survey.
  reasoning: Without title, abstract, or body site metadata, cannot determine if this is a gut microbiome study or a multi-host viral surveillance project where bats are incidental.

In [61]:
import pandas as pd, re

# --- keep-set ---
gmtol = pd.read_csv("../data/GMTOL_MAG_STUDY_list_ananaya.tsv", sep="\t", dtype=str)
keeps = gmtol[gmtol["status"] == "keep"].copy()

def prj(cell):
    return re.findall(r'PRJ[A-Z]{2}\d+', str(cell))
keeps["prj"] = keeps["accessions"].apply(prj)
keep_prj = set(a for lst in keeps["prj"] for a in lst)

# --- your catalog ---
cat = pd.read_csv("../results/yes_catalog.tsv", sep="\t")
my_accs = set(cat["study_accession"].dropna())

# --- coverage ---
have = keep_prj & my_accs
missing = keep_prj - my_accs

print(f"His curated keep studies (with ENA project accession): {len(keep_prj)}")
print(f"  You HAVE:    {len(have)}  ({100*len(have)/len(keep_prj):.0f}%)")
print(f"  You're MISSING: {len(missing)}")

print(f"\n--- Studies you HAVE (overlap) ---")
for acc in sorted(have):
    print(f"  {acc}")

print(f"\n--- Studies you're MISSING ---")
for acc in sorted(missing):
    row = keeps[keeps["prj"].apply(lambda l: acc in l)].iloc[0]
    host = row.get("host_common_name") or row.get("host_species") or "?"
    print(f"  {acc}  [{host}] — {str(row.get('title'))[:65]}")

His curated keep studies (with ENA project accession): 42
  You HAVE:    19  (45%)
  You're MISSING: 23

--- Studies you HAVE (overlap) ---
  PRJEB27498
  PRJEB38343
  PRJEB41657
  PRJEB43192
  PRJEB76898
  PRJEB7774
  PRJNA1029302
  PRJNA1123873
  PRJNA1211045
  PRJNA1302757
  PRJNA436633
  PRJNA598094
  PRJNA599289
  PRJNA645015
  PRJNA732531
  PRJNA744378
  PRJNA801070
  PRJNA806371
  PRJNA987703

--- Studies you're MISSING ---
  PRJCA023520  [golden snub-nosed monkey] — Plasticity of the gut microbiome of golden snub-nosed monkeys (Rh
  PRJDB4366  [Japanese sea cucumber] — nan
  PRJEB37575  [black soldier fly] — Plastics shape the black soldier fly larvae gut microbiome and se
  PRJEB38078  [nan] — nan
  PRJEB40672  [nan] — nan
  PRJEB45685  [black soldier fly] — Plastics shape the black soldier fly larvae gut microbiome and se
  PRJEB71469  [zebrafish] — Sampling fish gut microbiota - A genome-resolved metagenomic appr
  PRJEB81711  [nan] — Metagenome-based identification of functional traits of the black
  PRJNA1023379  [nan] — Enrichable consortia of microbial symbionts degrade macroalgal po
  PRJNA1112800  [nan] — Fish guts microbiome Metagenome (reef fish: yellow tang, triggerf
  PRJNA1188364  [nan] — Phylogenetic and functional diversity among Drosophila-associated
  PRJNA1293113  [grass carp] — Dietary macroalgae enhances amino acid metabolism via intestinal
  PRJNA288027  [human] — Rhodobacteraceae are Prevalent and Ecologically Crucial Bacterial
  PRJNA438833  [domestic cattle] — Gut microbiome variations in Rhinopithecus roxellanae caused by c
  PRJNA473901  [nan] — Honey bees harbor a diverse gut virome engaging in nested strain-
  PRJNA522654  [human] — Rhodobacteraceae are Prevalent and Ecologically Crucial Bacterial
  PRJNA658576  [nan] — Microbiome Analysis Reveals Diversity and Function of Mollicutes
  PRJNA735411  [South American sea lion] — Fecal Metagenomes and Metagenome-Assembled Genomes from the South
  PRJNA876378  [Indian medaka] — Short-term exposure to enrofloxacin causes hepatic metabolism dis
  PRJNA931729  [nan] — Genomic evidence for the first symbiotic Deferribacterota, a nove
  PRJNA947971  [Old World monkeys] — Human Disturbance Increases Health Risks to Golden Snub-Nosed Mon
  PRJNA948469  [nan] — Functional similarity, despite taxonomical divergence in the mill
  PRJNA961367  [nan] — Gut microbiomes of cycad-feeding insects tolerant to β-methylamin

In [63]:
import re, pandas as pd

def norm_title(t):
    if not isinstance(t, str): return ""
    t = re.sub(r'[^a-z0-9 ]', ' ', t.lower())
    return re.sub(r'\s+', ' ', t).strip()

def first_author_last(a):
    """crude last-name of first author, for matching across his/your formats"""
    if not isinstance(a, str) or not a.strip(): return ""
    first = re.split(r'[;,]', a.strip())[0].strip()      # first author token
    return first.split()[0].lower() if first else ""      # their surname (his format: 'Aizpurua O')

# ---- build lookup signals from YOUR catalog ----
cat["_ntitle"] = cat["paper_title"].apply(norm_title)
cat["_doi"]    = cat["doi"].astype(str).str.lower() if "doi" in cat.columns else ""
# your catalog stores first_author (from Alan's tool) — get its surname
cat["_auth"]   = cat["first_author"].apply(first_author_last) if "first_author" in cat.columns else ""
cat["_year"]   = cat["pub_year"].astype(str).str[:4] if "pub_year" in cat.columns else ""

my_titles = {t: a for t, a in zip(cat["_ntitle"], cat["study_accession"]) if t}
my_dois   = {d: a for d, a in zip(cat["_doi"], cat["study_accession"]) if d and d != "nan"}
my_authyr = {}
for a, y, acc in zip(cat["_auth"], cat["_year"], cat["study_accession"]):
    if a and y and y != "nan":
        my_authyr.setdefault((a, y), []).append(acc)

# ---- check each missing study against all three signals ----
missing_rows = keeps[keeps["prj"].apply(lambda l: any(x in missing for x in l))].copy()
missing_rows["_ntitle"] = missing_rows["title"].apply(norm_title)
missing_rows["_doi"]    = missing_rows["doi"].astype(str).str.lower()
missing_rows["_auth"]   = missing_rows["first_author"].apply(first_author_last)
missing_rows["_year"]   = missing_rows["year"].astype(str).str[:4]

real_gaps, recovered = [], []
print("MISSING STUDIES — matched by DOI / title / author+year:\n")
for _, r in missing_rows.iterrows():
    his_accs = [a for a in r["prj"] if a in missing]
    signals = []
    if r["_doi"] in my_dois:                         signals.append(f"DOI→{my_dois[r['_doi']]}")
    if r["_ntitle"] and r["_ntitle"] in my_titles:   signals.append(f"title→{my_titles[r['_ntitle']]}")
    if (r["_auth"], r["_year"]) in my_authyr:         signals.append(f"auth+yr→{my_authyr[(r['_auth'], r['_year'])]}")

    if signals:
        recovered.append(his_accs)
        print(f"  ✓ HAVE IT: {his_accs}  via {', '.join(signals)}")
        print(f"      {str(r['title'])[:65]}")
    else:
        real_gaps.append((his_accs, r.get("host_common_name") or r.get("host_species"), r["title"]))

print(f"\n{'='*55}")
print(f"Recovered (you have it under another accession): {len(recovered)}")
print(f"GENUINE gaps remaining: {len(real_gaps)}")
print(f"{'='*55}")
for accs, host, title in real_gaps:
    print(f"  {accs}  [{host}] — {str(title)[:60]}")

MISSING STUDIES — matched by DOI / title / author+year:

  ✓ HAVE IT: ['PRJEB38078']  via DOI→PRJNA316570, title→PRJNA316570, auth+yr→['PRJEB23642', 'PRJNA316560', 'PRJNA316570']
      Large-Scale Metagenome Assembly Reveals Novel Animal-Associated M

=======================================================
Recovered (you have it under another accession): 1
GENUINE gaps remaining: 21
=======================================================
  ['PRJEB38078', 'PRJEB40672']  [nan] — nan
  ['PRJNA947971']  [Old World monkeys] — Human Disturbance Increases Health Risks to Golden Snub-Nose
  ['PRJNA1023379']  [nan] — Enrichable consortia of microbial symbionts degrade macroalg
  ['PRJNA1293113']  [grass carp] — Dietary macroalgae enhances amino acid metabolism via intest
  ['PRJEB71469']  [zebrafish] — Sampling fish gut microbiota - A genome-resolved metagenomic
  ['PRJNA876378']  [Indian medaka] — Short-term exposure to enrofloxacin causes hepatic metabolis
  ['PRJNA1112800']  [nan] — Fish guts microbiome Metagenome (reef fish: yellow tang, tri
  ['PRJNA658576']  [nan] — Microbiome Analysis Reveals Diversity and Function of Mollic
  ['PRJNA948469']  [nan] — Functional similarity, despite taxonomical divergence in the
  ['PRJDB4366']  [Japanese sea cucumber] — nan
  ['PRJNA473901']  [nan] — Honey bees harbor a diverse gut virome engaging in nested st
  ['PRJNA1188364']  [nan] — Phylogenetic and functional diversity among Drosophila-assoc
  ['PRJNA961367']  [nan] — Gut microbiomes of cycad-feeding insects tolerant to β-methy
  ['PRJEB81711']  [nan] — Metagenome-based identification of functional traits of the
  ['PRJEB38078', 'PRJEB40672']  [nan] — Diversity and taxonomic revision of methanogens and other ar
  ['PRJEB37575', 'PRJEB45685']  [black soldier fly] — Plastics shape the black soldier fly larvae gut microbiome a
  ['PRJNA931729']  [nan] — Genomic evidence for the first symbiotic Deferribacterota, a
  ['PRJNA438833']  [domestic cattle] — Gut microbiome variations in Rhinopithecus roxellanae caused
  ['PRJNA288027', 'PRJNA522654']  [human] — Rhodobacteraceae are Prevalent and Ecologically Crucial Bact
  ['PRJNA735411']  [South American sea lion] — Fecal Metagenomes and Metagenome-Assembled Genomes from the
  ['PRJCA023520']  [golden snub-nosed monkey] — Plasticity of the gut microbiome of golden snub-nosed monkey

In [64]:
cat = pd.read_csv("../results/yes_catalog.tsv", sep="\t")

# any human hosts?
human_mask = (
    cat["host_species"].astype(str).str.contains("Homo sapiens|human", case=False, na=False) |
    cat["host_species_taxonomy"].astype(str).str.contains("Homo sapiens", case=False, na=False) |
    cat["host_genus"].astype(str).str.contains("Homo", case=False, na=False)
)
human = cat[human_mask]
print(f"Human studies in catalog: {len(human)}")
if len(human):
    print(human[["study_accession","host_species","host_species_taxonomy","data_source","paper_title"]].to_string(index=False))

Human studies in catalog: 177
study_accession                                                                              host_species    host_species_taxonomy         data_source                                                                                                                                                                                                       paper_title
    PRJNA475246                                                                              Homo sapiens                  sapiens              pubmed                                                                                                                                                                                                               NaN
    PRJNA389927                                                                              Homo sapiens             Homo sapiens              pubmed                                                                                                                                                                                                               NaN
     PRJDB16260                                                                              Homo sapiens                      NaN            ena_only                                                                                                                                                                                                               NaN
    PRJNA398089                                                                              Homo sapiens             Homo sapiens              pubmed                                                                                                                                                                                                               NaN
    PRJNA660443                                                                              Homo sapiens             Homo sapiens              pubmed                                                                                                                                                                                                               NaN
    PRJNA788972                                                                              Homo sapiens             Homo sapiens              pubmed                                                                                                                                                                                                               NaN
    PRJNA909453                                                                              Homo sapiens             Homo sapiens            ena_only                                                                                                                                                                                                               NaN
      PRJDB6503                                                                              Homo sapiens             Homo sapiens            ena_only                                                                                                                                                                                                               NaN
      PRJEB7774                                                                                       NaN                  sapiens              pubmed                                                                                                                                                                                                               NaN
    PRJNA574033                                                                              Homo sapiens Hexaprotodon liberiensis              pubmed                                                                                                                                                                                                               NaN
     PRJEB55711                                                                                       NaN                  sapiens              pubmed                                                                                                                                                                                                               NaN
    PRJNA915251                                                                              Homo sapiens             Homo sapiens            ena_only                                                                                                                                                                                                               NaN
      PRJEB5224                                                                                       NaN                  sapiens              pubmed                                                                                                                                                                                                               NaN
   PRJNA1211300                                                                              Homo sapiens             Homo sapiens              pubmed                                                                                                                                                                                                               NaN
    PRJNA773596                                                                              Homo sapiens             Homo sapiens            ena_only                                                                                                                                                                                                               NaN
   PRJNA1135945                                                                              Homo sapiens             Homo sapiens              pubmed                                                                                                                                                                                                               NaN
     PRJEB14215                                                                                       NaN                  sapiens              pubmed                                                                                                                   Iron status influences non-alcoholic fatty liver disease in obesity through the gut microbiome.
     PRJEB12449                                                                                       NaN                  sapiens              pubmed                                                                                                                                                                                                               NaN
     PRJDB36905                                                                              Homo sapiens                      NaN            ena_only                                                                                                                                                                                                               NaN
    PRJNA397112                                                                              Homo sapiens             Homo sapiens              pubmed                                                                                                                                                                                                               NaN
    PRJNA770101                                                                              Homo sapiens             Homo sapiens            ena_only                                                                                                                                                                                                               NaN
    PRJNA913183                                                                              Homo sapiens             Homo sapiens            ena_only                                                                                                                                                                                                               NaN
    PRJNA847183                                                                              Homo sapiens             Homo sapiens            ena_only                                                                                                                                                                                                               NaN
    PRJNA400072                                                                              Homo sapiens             Homo sapiens              pubmed                                                                                                                                                                                                               NaN
      PRJDB7630                                                                              Homo sapiens             Homo sapiens            ena_only                                                                                                                                                                                                               NaN
    PRJNA663646                                                                              Homo sapiens             Homo sapiens            ena_only                                                                                                                                                                                                               NaN
     PRJEB34992                                                                                       NaN                  sapiens              pubmed                                                                                                                                                                                                               NaN
   PRJNA1225188                                                                              Homo sapiens                      NaN            ena_only                                                                                                                                                                                                               NaN
      PRJDB4525                                                                              Homo sapiens             Homo sapiens            ena_only                                                                                                                                                                                                               NaN
   PRJNA1090271                                                                                   missing                  sapiens              pubmed                                                                                                                                                                                                               NaN
    PRJNA852373                                                                              Homo sapiens                      NaN            ena_only                                                                                                                                                                                                               NaN
    PRJNA401977                                                                                       NaN                  sapiens              pubmed                                                                                                                                                                                                               NaN
     PRJEB66719                                                                                       NaN                  sapiens              pubmed                                                                                                                                                                                                               NaN
    PRJNA431482                                                                              Homo sapiens             Homo sapiens              pubmed                                                                                                                                                                                                               NaN
    PRJNA678871                                                                              Homo sapiens            Gallus gallus              pubmed                                                                                                                                                                                                               NaN
    PRJNA294605                                                                              Homo sapiens                  sapiens              pubmed                                                                                                                                                                                                               NaN
    PRJNA699146                                                                              Homo sapiens             Homo sapiens            ena_only                                                                                                                                                                                                               NaN
   PRJNA1298367                                                                              Homo sapiens             Homo sapiens              pubmed                                                    Reduced fibre-fermenting capacity of gut microbes in multiple sclerosis may result in prebiotic dietary fibre β-fructan promoting inflammation and CNS damage.
     PRJDB16790                                                                              Homo sapiens             Homo sapiens            ena_only                                                                                                                                                                                                               NaN
    PRJNA494824                                                                              Homo sapiens             Homo sapiens              pubmed                                                                                                                                                                                                               NaN
    PRJNA763692                                                                              Homo sapiens               Sus scrofa              pubmed                                                                                                                                                                                                               NaN
    PRJNA624223                                                                              Homo sapiens             Homo sapiens              pubmed                                                                                                                                                                                                               NaN
    PRJNA919082                                                                              Homo sapiens                      NaN            ena_only                                                                                                                                                                                                               NaN
      PRJDB7378                                                                              Homo sapiens             Homo sapiens            ena_only                                                                                                                                                                                                               NaN
      PRJEB6070                                                                              Homo sapiens                  sapiens              pubmed                                                                                                                                                                                                               NaN
   PRJNA1078999                                                                              Homo sapiens             Homo sapiens            ena_only                                                                                                                                                                                                               NaN
     PRJEB27928                                                                                       NaN                  sapiens              pubmed                                                                                                                                                                                                               NaN
    PRJNA496479                                                                              Homo sapiens             Homo sapiens              pubmed                                                                                                                                                                                                               NaN
    PRJNA741822                                                                              Homo sapiens             Homo sapiens            ena_only                                                                                                                                                                                                               NaN
    PRJNA613834                                                                              Homo sapiens             Homo sapiens            ena_only                                                                                                                                                                                                               NaN
    PRJNA384716                                                                              Homo sapiens             Homo sapiens              pubmed                                                                                                                                                                                                               NaN
     PRJDB16312                                                                              Homo sapiens             Homo sapiens            ena_only                                                                                                                                                                                                               NaN
      PRJDB4176                                                                              Homo sapiens             Homo sapiens            ena_only                                                                                                                                                                                                               NaN
     PRJDB33192                                                                              Homo sapiens             Homo sapiens            ena_only                                                                                                                                                                                                               NaN

In [65]:
human = cat[human_mask]
print("Human studies by data_source:")
print(human["data_source"].value_counts().to_string())
print(f"\nHuman studies by classification (if column exists):")
if "classification_final" in human.columns:
    print(human["classification_final"].value_counts().to_string())
print(f"\nSample of human studies:")
print(human[["study_accession","host_species","data_source","paper_title"]].head(15).to_string(index=False))

Human studies by data_source:
data_source
pubmed                 89
ena_only               78
pubmed_metagenom_b1     6
pubmed_postdoc          3
pubmed_metagenom_b2     1

Human studies by classification (if column exists):
classification_final
YES    177

Sample of human studies:
study_accession host_species data_source paper_title
    PRJNA475246 Homo sapiens      pubmed         NaN
    PRJNA389927 Homo sapiens      pubmed         NaN
     PRJDB16260 Homo sapiens    ena_only         NaN
    PRJNA398089 Homo sapiens      pubmed         NaN
    PRJNA660443 Homo sapiens      pubmed         NaN
    PRJNA788972 Homo sapiens      pubmed         NaN
    PRJNA909453 Homo sapiens    ena_only         NaN
      PRJDB6503 Homo sapiens    ena_only         NaN
      PRJEB7774          NaN      pubmed         NaN
    PRJNA574033 Homo sapiens      pubmed         NaN
     PRJEB55711          NaN      pubmed         NaN
    PRJNA915251 Homo sapiens    ena_only         NaN
      PRJEB5224          NaN      pubmed         NaN
   PRJNA1211300 Homo sapiens      pubmed         NaN
    PRJNA773596 Homo sapiens    ena_only         NaN

In [66]:
cat = pd.read_csv("../results/yes_catalog.tsv", sep="\t")
link_cols = [c for c in cat.columns if c.lower() in
             ("doi","pmid","paper_title","journal","pub_year","fulltext_link","url","first_author","last_author")]
print("Link-related columns present:", link_cols)
for c in link_cols:
    print(f"  {c:15s}: {cat[c].notna().sum():>4}/{len(cat)} filled ({100*cat[c].notna().sum()/len(cat):.0f}%)")

Link-related columns present: ['pmid', 'paper_title', 'first_author', 'last_author', 'pub_year', 'journal', 'doi']
  pmid           :  561/1044 filled (54%)
  paper_title    :  316/1044 filled (30%)
  first_author   :  195/1044 filled (19%)
  last_author    :  194/1044 filled (19%)
  pub_year       :  177/1044 filled (17%)
  journal        :  316/1044 filled (30%)
  doi            :  177/1044 filled (17%)

In [68]:
import pandas as pd, re
gmtol = pd.read_csv("../data/GMTOL_MAG_STUDY_list_ananaya.tsv", sep="\t", dtype=str)
cat = pd.read_csv("../results/yes_catalog.tsv", sep="\t")

keeps = gmtol[gmtol["status"] == "keep"].copy()
def prj(cell): return re.findall(r'PRJ[A-Z]{2}\d+', str(cell))
keeps["prj"] = keeps["accessions"].apply(prj)
my_accs = set(cat["study_accession"].dropna())

# a keep-row is "missed" if NONE of its accessions are in your catalog (raw, no recovery)
keeps["missed"] = keeps["prj"].apply(lambda l: len(l) > 0 and not any(a in my_accs for a in l))
missed_rows = keeps[keeps["missed"]].copy()

report = pd.DataFrame({
    "accessions":       missed_rows["accessions"],
    "title":            missed_rows["title"],
    "library_strategy": missed_rows["library_strategy_mix"],
    "host_class":       missed_rows["host_class"],
    "host_common_name": missed_rows["host_common_name"],
    "n_shotgun_gut_samples": missed_rows["n_shotgun_gut_samples"],
    "doi":              missed_rows["doi"],
    "manual_note":      missed_rows["manual_note"],
})
report.to_csv("../results/gmtol_missed_accessions.tsv", sep="\t", index=False)

print(f"TOTAL MISSED (raw accession match): {len(report)} studies")
print(f"(overestimate — some may exist under alternate accessions)\n")
pd.set_option("display.max_colwidth", 60)
print(report[["accessions","title","library_strategy","host_class"]].to_string(index=False))
print(f"\nSaved -> gmtol_missed_accessions.tsv")

TOTAL MISSED (raw accession match): 20 studies
(overestimate — some may exist under alternate accessions)

            accessions                                                                                                                                                                             title              library_strategy     host_class
PRJEB38078; PRJEB40672                                                                                                                                                                               NaN         WGS:289; AMPLICON:185            NaN
           PRJNA947971 Human Disturbance Increases Health Risks to Golden Snub-Nosed Monkeys and the Transfer Risk of Pathogenic Antibiotic-Resistant Bacteria from Golden Snub-Nosed Monkeys to Humans.                  AMPLICON:151            NaN
          PRJNA1023379                                                                                  Enrichable consortia of microbial symbionts degrade macroalgal polysaccharides in Kyphosus fish.          AMPLICON:151; WGS:26 Actinopterygii
          PRJNA1293113                                                              Dietary macroalgae enhances amino acid metabolism via intestinal Shewanella in grass carp (Ctenopharyngodon idella).         AMPLICON:1045; WGS:20 Actinopterygii
            PRJEB71469                                                                                                            Sampling fish gut microbiota - A genome-resolved metagenomic approach.           AMPLICON:16; WGS:15 Actinopterygii
           PRJNA876378                    Short-term exposure to enrofloxacin causes hepatic metabolism disorder associated with intestinal flora dysbiosis in adult marine medaka (Oryzias melastigma).                         WGS:4 Actinopterygii
          PRJNA1112800                                                                                                   Fish guts microbiome Metagenome (reef fish: yellow tang, triggerfish, hawkfish)                    AMPLICON:3 Actinopterygii
           PRJNA658576                                                       Microbiome Analysis Reveals Diversity and Function of Mollicutes Associated with the Eastern Oyster, Crassostrea virginica.          AMPLICON:236; WGS:13       Bivalvia
           PRJNA948469                                                       Functional similarity, despite taxonomical divergence in the millipede gut microbiota, points to a common trophic strategy. AMPLICON:50; WGS:2; RNA-Seq:2      Diplopoda
             PRJDB4366                                                                                                                                                                               NaN            AMPLICON:21; WGS:2  Holothuroidea
          PRJNA1188364                                                                                   Phylogenetic and functional diversity among Drosophila-associated metagenome-assembled genomes.                        WGS:37        Insecta
           PRJNA961367                                                         Gut microbiomes of cycad-feeding insects tolerant to β-methylamino-L-alanine (BMAA) are rich in siderophore biosynthesis.                         WGS:5        Insecta
            PRJEB81711                                                  Metagenome-based identification of functional traits of the black soldier fly gut microbiome associated with larval performance.          AMPLICON:120; WGS:12        Insecta
PRJEB38078; PRJEB40672                                                              Diversity and taxonomic revision of methanogens and other archaea in the intestinal tract of terrestrial arthropods.         WGS:289; AMPLICON:185        Insecta
PRJEB37575; PRJEB45685                                                                                 Plastics shape the black soldier fly larvae gut microbiome and select for biodegrading functions.             WGS:15; RNA-Seq:6        Insecta
           PRJNA931729                                      Genomic evidence for the first symbiotic Deferribacterota, a novel gut symbiont from the deep-sea hydrothermal vent shrimp Rimicaris kairei.                         WGS:4   Malacostraca
            PRJEB38078                                       Large-Scale Metagenome Assembly Reveals Novel Animal-Associated Microbial Genomes, Biosynthetic Gene Clusters, and Other Genetic Diversity.          WGS:305; RNA-Seq:182       Mammalia
           PRJNA438833                                                                                       Gut microbiome variations in Rhinopithecus roxellanae caused by changes in the environment.          AMPLICON:764; WGS:22       Mammalia
           PRJNA735411                                   Fecal Metagenomes and Metagenome-Assembled Genomes from the South American Sea Lion (Otaria flavescens) from the Comau Fjord (42°S), Patagonia.                        WGS:30       Mammalia
CRA023365; PRJCA023520                                                Plasticity of the gut microbiome of golden snub-nosed monkeys (Rhinopithecus roxellana) in response to seasonal variation in diet.                        WGS:85       Mammalia

Saved -> gmtol_missed_accessions.tsv

In [69]:
import pandas as pd
cat = pd.read_csv("../results/yes_catalog.tsv", sep="\t")

# human subset (for the scope-aware count)
human = cat[
    cat["host_species"].astype(str).str.contains("Homo sapiens|human", case=False, na=False) |
    cat["host_species_taxonomy"].astype(str).str.contains("Homo sapiens", case=False, na=False)
]

print("="*50)
print("CATALOG SUMMARY")
print("="*50)
print(f"Total studies        : {len(cat):,}")
print(f"Total samples        : {cat['n_samples'].sum():,}")
print(f"  Human studies      : {len(human):,}  ({human['n_samples'].sum():,} samples)")
print(f"  Animal-only        : {len(cat)-len(human):,}  ({cat['n_samples'].sum()-human['n_samples'].sum():,} samples)")

print(f"\nHow found (data_source):")
print(cat['data_source'].value_counts().to_string())

print(f"\nHost taxonomy coverage:")
print(f"  host_class filled  : {cat['host_class'].notna().sum():,}/{len(cat)} ({100*cat['host_class'].notna().sum()/len(cat):.0f}%)")

print(f"\nTop host classes:")
print(cat['host_class'].value_counts().head(8).to_string())

print(f"\nNot yet merged: 23 host-sweep studies (in sweep_llm_classified.tsv)")

==================================================
CATALOG SUMMARY
==================================================
Total studies        : 1,044
Total samples        : 107,009
  Human studies      : 147  (23,219 samples)
  Animal-only        : 897  (83,790 samples)

How found (data_source):
data_source
ena_only               483
pubmed                 313
pubmed_metagenom_b1    121
pubmed_postdoc          71
pubmed_metagenom_b2     56

Host taxonomy coverage:
  host_class filled  : 728/1044 (70%)

Top host classes:
host_class
Mammalia          543
Aves               86
Insecta            40
Actinopteri        34
Lepidosauria        5
Actinopterygii      4
Malacostraca        3
Chondrichthyes      3

Not yet merged: 23 host-sweep studies (in sweep_llm_classified.tsv)

In [1]:
import pandas as pd, re

gmtol = pd.read_csv("../data/GMTOL_MAG_STUDY_list_ananaya.tsv", sep="\t", dtype=str)
cat = pd.read_csv("../results/yes_catalog.tsv", sep="\t")

# --- his approved set: anything starting with "Yes" (inclusive of caveated) ---
gmtol["_approve"] = gmtol["Sam_approve"].astype(str).str.strip().str.lower()
his = gmtol[gmtol["_approve"].str.startswith("yes")].copy()
print(f"Sam-approved studies (Yes*): {len(his)}")

def prj(cell): return re.findall(r'PRJ[A-Z]{2}\d+', str(cell))
his["prj"] = his["accessions"].apply(prj)
his_accs = set(a for lst in his["prj"] for a in lst)
my_accs  = set(cat["study_accession"].dropna())

# --- recover alternate-accession matches via normalized title ---
def norm(t):
    if not isinstance(t,str): return ""
    return re.sub(r'\s+',' ',re.sub(r'[^a-z0-9 ]',' ',t.lower())).strip()
my_titles = {norm(t) for t in cat["paper_title"].dropna()}
his["_nt"] = his["title"].apply(norm)

# a his-study is "in common" if any accession matches OR its title matches one of yours
def in_mine(row):
    if any(a in my_accs for a in row["prj"]): return True
    if row["_nt"] and row["_nt"] in my_titles: return True
    return False
his["in_mine"] = his.apply(in_mine, axis=1)

common_his = his[his["in_mine"]]
his_only   = his[~his["in_mine"]]

# yours-only = your studies whose accession isn't in ANY of his rows (approved or not)
all_his_accs = set(a for cell in gmtol["accessions"].dropna() for a in prj(cell))
yours_only = cat[~cat["study_accession"].isin(all_his_accs)]

print(f"\n{'='*50}")
print("THREE-WAY COMPARISON (vs Sam-approved set)")
print(f"{'='*50}")
print(f"In common:   {len(common_his)}")
print(f"His only (approved, not in mine): {len(his_only)}")
print(f"Mine only:   {len(yours_only)}")

# --- host taxonomy breakdown per group (class level, both have it reliably) ---
def classes(df, col="host_class"):
    return df[col].fillna("(unknown)").value_counts()

print(f"\n--- HOST CLASS: in common (his labels) ---")
print(classes(common_his).to_string())
print(f"\n--- HOST CLASS: his only ---")
print(classes(his_only).to_string())
print(f"\n--- HOST CLASS: mine only ---")
print(classes(yours_only).to_string())

# --- which classes are shared vs unique to each side ---
his_classes  = set(his["host_class"].dropna())
mine_classes = set(cat["host_class"].dropna())
print(f"\n{'='*50}")
print("HOST CLASS OVERLAP")
print(f"{'='*50}")
print(f"Classes in BOTH:      {sorted(his_classes & mine_classes)}")
print(f"Classes ONLY in his:  {sorted(his_classes - mine_classes)}")
print(f"Classes ONLY in mine: {sorted(mine_classes - his_classes)}")

Sam-approved studies (Yes*): 84

==================================================
THREE-WAY COMPARISON (vs Sam-approved set)
==================================================
In common:   39
His only (approved, not in mine): 45
Mine only:   1003

--- HOST CLASS: in common (his labels) ---
host_class
Insecta           13
(unknown)         11
Actinopterygii     9
Amphibia           1
Gastropoda         1
Mammalia           1
Aves               1
Malacostraca       1
Reptilia           1

--- HOST CLASS: his only ---
host_class
(unknown)         19
Insecta            9
Actinopterygii     7
Amphibia           2
Reptilia           2
Bivalvia           1
Diplopoda          1
Holothuroidea      1
Malacostraca       1
Mammalia           1
Clitellata         1

--- HOST CLASS: mine only ---
host_class
Mammalia          533
(unknown)         312
Aves               84
Actinopteri        28
Insecta            28
Lepidosauria        4
Chondrichthyes      3
Holothuroidea       3
Malacostraca        2
Magnoliopsida       2
Amphibia            1
Actinopterygii      1
Arachnida           1
Branchiopoda        1

==================================================
HOST CLASS OVERLAP
==================================================
Classes in BOTH:      ['Actinopterygii', 'Amphibia', 'Aves', 'Gastropoda', 'Holothuroidea', 'Insecta', 'Malacostraca', 'Mammalia']
Classes ONLY in his:  ['Bivalvia', 'Clitellata', 'Diplopoda', 'Reptilia']
Classes ONLY in mine: ['Actinopteri', 'Arachnida', 'Branchiopoda', 'Chondrichthyes', 'Lepidosauria', 'Magnoliopsida']

In [2]:
# normalize both sides to a common class scheme
synonyms = {
    "Actinopteri": "Actinopterygii",      # ray-finned fish — same class
    "Lepidosauria": "Reptilia",            # collapse your finer rank to his coarser one
    "Squamata": "Reptilia",
}
def norm_class(c):
    return synonyms.get(c, c)

his_classes  = set(his["host_class"].dropna().map(norm_class))
mine_classes = set(cat["host_class"].dropna().map(norm_class))
# drop known false positive
mine_classes.discard("Magnoliopsida")

print("After normalizing naming schemes:")
print(f"  In BOTH:      {sorted(his_classes & mine_classes)}")
print(f"  ONLY his:     {sorted(his_classes - mine_classes)}")
print(f"  ONLY mine:    {sorted(mine_classes - his_classes)}")

After normalizing naming schemes:
  In BOTH:      ['Actinopterygii', 'Amphibia', 'Aves', 'Gastropoda', 'Holothuroidea', 'Insecta', 'Malacostraca', 'Mammalia', 'Reptilia']
  ONLY his:     ['Bivalvia', 'Clitellata', 'Diplopoda']
  ONLY mine:    ['Arachnida', 'Branchiopoda', 'Chondrichthyes']

In [6]:
import sys, os
sys.path.insert(0, os.path.abspath(".."))

import importlib, src.enrich_catalog_from_ena
importlib.reload(src.enrich_catalog_from_ena)
from src.enrich_catalog_from_ena import run as enrich
enrich()

Resuming — 725 already enriched
Enriching 319 studies from ENA...
  0/319
  25/319
  50/319
  75/319
  100/319
  125/319
  150/319
  175/319
  200/319
  225/319
  250/319
  275/319
  300/319

====================================================
ENRICHMENT COMPLETE
====================================================
Studies enriched: 1044
With library_strategy_mix: 863
With host_species_list:    489
With body_sites:           37

Multi-host studies (n_host_species > 1): 62
  ...of which >5 hosts (likely surveys):  10

Studies with 0 WGS samples (all-amplicon?): 234
Saved -> ../results/yes_catalog.tsv

,study_accession,host_species,host_tax_id,body_site,country,n_samples,library_strategy,data_source,pmid,pmid_str,...,llm_evidence,library_strategy_mix,n_wgs_samples,n_host_species,host_species_list,body_sites,biome_labels,isolation_sources,sample_titles_cache,n_total_samples
0,PRJNA379709,Mus musculus,10090.0,NaN,USA: Arizona,8,WGS,pubmed,28951889.0,28951889.0,...,NaN,WGS:4; RNA-Seq:4,4,1,Mus musculus,,mouse gut metagenome,,Mouse 129 Strain SMAD3+/+ Cecal DNA content; M...,8.0
1,PRJNA806482,RAT,NaN,NaN,South Korea,18,WGS,ena_only,NaN,NaN,...,NaN,WGS:18,18,0,,,feces metagenome,feces,110000421; 110000441; 110001011; 120000301; 12...,18.0
2,PRJNA873123,Gallus gallus,9031.0,NaN,"China: Hebei,Zhuozhou",32,WGS,ena_only,NaN,NaN,...,NaN,WGS:32,32,1,Gallus gallus,,chicken gut metagenome,,AOS1; AOS10; AOS11; AOS12; AOS13,32.0
3,PRJDB9383,Mus musculus,10090.0,NaN,Japan:Tokyo,8,WGS,ena_only,NaN,NaN,...,NaN,WGS:7; WGA:1,7,1,Mus musculus,,mouse gut metagenome,,16S rRNA isolated from mice fecal in HFPg1; 16...,8.0
4,PRJNA947387,C57BL/6J,NaN,NaN,missing,27,WGS,ena_only,NaN,NaN,...,NaN,WGS:27,27,0,,,feces metagenome,missing,control1; control2; control3; control4; control5,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039,PRJNA419985,Rat,NaN,NaN,China,16,WGS,pubmed_metagenom_b2,29903041.0,NaN,...,Biome label: 'rat gut metagenome'; Isolation s...,WGS:16,16,0,,,rat gut metagenome,stool,MS1-PD56; MS2-PD56; MS3-PD56; MS4-PD56; MS5-PD56,16.0
1040,PRJNA381379,Strigops habroptila,2489341.0,NaN,New Zealand: Codfish Island,3,WGS,pubmed_metagenom_b2,29802288.0,NaN,...,Paper title explicitly states 'faecal microbio...,WGS:3,3,1,Strigops habroptila,,Escherichia fergusonii; Streptococcus gallolyt...,multiple bacterial isolates cultured from kaka...,Cultured bacterial isolates from kakapo feces ...,3.0
1041,PRJNA415003,Desmodus rotundus,9430.0,NaN,Australia: Pilbarra,50,WGS,pubmed_metagenom_b2,29459707.0,NaN,...,Isolation source(s): feces; library_source: ME...,WGS:50,50,4,Desmodus rotundus; Macroderma gigas; Rhinoloph...,,bat metagenome,feces,Metagenome or environmental sample from bat me...,50.0
1042,PRJNA269993,Cow,NaN,NaN,USA: Virginia,1,WGS,pubmed_metagenom_b2,26258869.0,NaN,...,Paper title: 'Metagenomic Analysis of Antibiot...,WGS:1,1,0,,,bovine gut metagenome,,Bacterial metagenome isolated from cow feces,1.0
1043,PRJNA158313,Rhinopithecus bieti,NaN,NaN,NaN,2,WGS,pubmed_metagenom_b2,23251564.0,NaN,...,Sample titles: 'feccal sample of Rhinopithecus...,WGS:2,2,1,Rhinopithecus bieti,,Xanthonycticebus pygmaeus; gut metagenome,,feccal sample of Rhinopithecus bieti; feccal s...,2.0

In [7]:
cat = pd.read_csv("../results/yes_catalog.tsv", sep="\t")
zero_wgs = cat[cat["n_wgs_samples"] == 0]
print(f"Zero-WGS studies: {len(zero_wgs)}")
print(f"\nTheir library_strategy_mix values (what strategies DO they have?):")
print(zero_wgs["library_strategy_mix"].value_counts().head(20).to_string())
print(f"\nHow many have NO mix at all (empty = fetch failed / no strategy field)?")
print(f"  empty mix: {(zero_wgs['library_strategy_mix'].astype(str).str.strip()=='').sum()}")

Zero-WGS studies: 234

Their library_strategy_mix values (what strategies DO they have?):
library_strategy_mix
OTHER:12        4
Hi-C:1          3
WGA:2           2
WGA:24          2
OTHER:18        2
WGA:36          2
WGA:78          1
OTHER:34        1
OTHER:13        1
WXS:29          1
OTHER:27        1
Hi-C:3          1
OTHER:312       1
OTHER:8         1
Tn-Seq:61       1
OTHER:6         1
OTHER:60        1
POOLCLONE:12    1
OTHER:28        1
OTHER:57        1

How many have NO mix at all (empty = fetch failed / no strategy field)?
  empty mix: 0

In [8]:
# for the zero-WGS studies, what does library_source say?
zero_wgs = cat[cat["n_wgs_samples"] == 0]
print("library_source for the 234 zero-WGS studies:")
print(zero_wgs["library_source"].value_counts(dropna=False).to_string())

# the ones that are METAGENOMIC source but non-WGS strategy = likely real, mislabeled
likely_real = zero_wgs[zero_wgs["library_source"] == "METAGENOMIC"]
print(f"\nZero-WGS but library_source=METAGENOMIC (likely real, keep): {len(likely_real)}")
print(f"Zero-WGS and NOT metagenomic source (likely real exclusions): {len(zero_wgs) - len(likely_real)}")

library_source for the 234 zero-WGS studies:
library_source
METAGENOMIC    227
GENOMIC          4
OTHER            3

Zero-WGS but library_source=METAGENOMIC (likely real, keep): 227
Zero-WGS and NOT metagenomic source (likely real exclusions): 7

In [9]:
import sys, os
sys.path.insert(0, os.path.abspath(".."))
from src.fetcher import configure_entrez
configure_entrez()

import importlib, src.backfill_pmid_metadata
importlib.reload(src.backfill_pmid_metadata)
from src.backfill_pmid_metadata import run as backfill
backfill()

Entrez configured with email: akharya@ucsd.edu
Studies with PMID but missing doi/title: 384
Unique PMIDs to resolve: 315
Fetching 315...

  0/315
  25/315
  50/315
  75/315
  100/315
  125/315
  150/315
  175/315
  200/315
  225/315
  250/315
  275/315
  300/315

==================================================
PMID BACKFILL COMPLETE
==================================================
  doi            :  561/1044 (54%)
  paper_title    :  561/1044 (54%)
  pub_year       :  561/1044 (54%)
  journal        :  561/1044 (54%)
  first_author   :  440/1044 (42%)
  fulltext_link  :  561/1044 (54%)
Saved -> ../results/yes_catalog.tsv

,study_accession,host_species,host_tax_id,body_site,country,n_samples,library_strategy,data_source,pmid,pmid_str,...,library_strategy_mix,n_wgs_samples,n_host_species,host_species_list,body_sites,biome_labels,isolation_sources,sample_titles_cache,n_total_samples,fulltext_link
0,PRJNA379709,Mus musculus,10090.0,NaN,USA: Arizona,8,WGS,pubmed,28951889.0,28951889.0,...,WGS:4; RNA-Seq:4,4,1,Mus musculus,NaN,mouse gut metagenome,NaN,Mouse 129 Strain SMAD3+/+ Cecal DNA content; M...,8.0,https://doi.org/10.1128/mSystems.00065-17
1,PRJNA806482,RAT,NaN,NaN,South Korea,18,WGS,ena_only,NaN,NaN,...,WGS:18,18,0,NaN,NaN,feces metagenome,feces,110000421; 110000441; 110001011; 120000301; 12...,18.0,None
2,PRJNA873123,Gallus gallus,9031.0,NaN,"China: Hebei,Zhuozhou",32,WGS,ena_only,NaN,NaN,...,WGS:32,32,1,Gallus gallus,NaN,chicken gut metagenome,NaN,AOS1; AOS10; AOS11; AOS12; AOS13,32.0,None
3,PRJDB9383,Mus musculus,10090.0,NaN,Japan:Tokyo,8,WGS,ena_only,NaN,NaN,...,WGS:7; WGA:1,7,1,Mus musculus,NaN,mouse gut metagenome,NaN,16S rRNA isolated from mice fecal in HFPg1; 16...,8.0,None
4,PRJNA947387,C57BL/6J,NaN,NaN,missing,27,WGS,ena_only,NaN,NaN,...,WGS:27,27,0,NaN,NaN,feces metagenome,missing,control1; control2; control3; control4; control5,27.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039,PRJNA419985,Rat,NaN,NaN,China,16,WGS,pubmed_metagenom_b2,29903041.0,NaN,...,WGS:16,16,0,NaN,NaN,rat gut metagenome,stool,MS1-PD56; MS2-PD56; MS3-PD56; MS4-PD56; MS5-PD56,16.0,https://doi.org/10.1186/s40168-018-0492-6
1040,PRJNA381379,Strigops habroptila,2489341.0,NaN,New Zealand: Codfish Island,3,WGS,pubmed_metagenom_b2,29802288.0,NaN,...,WGS:3,3,1,Strigops habroptila,NaN,Escherichia fergusonii; Streptococcus gallolyt...,multiple bacterial isolates cultured from kaka...,Cultured bacterial isolates from kakapo feces ...,3.0,https://doi.org/10.1038/s41598-018-26484-4
1041,PRJNA415003,Desmodus rotundus,9430.0,NaN,Australia: Pilbarra,50,WGS,pubmed_metagenom_b2,29459707.0,NaN,...,WGS:50,50,4,Desmodus rotundus; Macroderma gigas; Rhinoloph...,NaN,bat metagenome,feces,Metagenome or environmental sample from bat me...,50.0,https://doi.org/10.1038/s41559-018-0476-8
1042,PRJNA269993,Cow,NaN,NaN,USA: Virginia,1,WGS,pubmed_metagenom_b2,26258869.0,NaN,...,WGS:1,1,0,NaN,NaN,bovine gut metagenome,NaN,Bacterial metagenome isolated from cow feces,1.0,https://doi.org/10.1371/journal.pone.0133764
1043,PRJNA158313,Rhinopithecus bieti,NaN,NaN,NaN,2,WGS,pubmed_metagenom_b2,23251564.0,NaN,...,WGS:2,2,1,Rhinopithecus bieti,NaN,Xanthonycticebus pygmaeus; gut metagenome,NaN,feccal sample of Rhinopithecus bieti; feccal s...,2.0,https://doi.org/10.1371/journal.pone.0051521

In [13]:
import sys, os
sys.path.insert(0, os.path.abspath(".."))
import importlib, src.audit_catalog
importlib.reload(src.audit_catalog)
src.audit_catalog.LIMIT = 30
from src.audit_catalog import run as audit
sample = audit()

** VALIDATION RUN — first 30 **
Auditing 30 studies with claude-haiku-4-5-20251001...

  0/30
  10/30
  20/30

====================================================
AUDIT COMPLETE
====================================================
Keep decision:
keep
KEEP       23
REVIEW      4
EXCLUDE     3

Criterion 1 gut:
gut
yes          25
no            3
uncertain     2

Criterion 2 body_site:
body_site
gut_explicit    29
gut_inferred     1

Criterion 3 host:
host_verdict
single_clear    23
multi_host       3
unclear          3
genus_only       1

method agreement:
method_note
agree       19
unclear      7
mismatch     4

Flagged human: 4
EXCLUDE or REVIEW: 7
Saved -> ../results/catalog_audit.tsv

In [14]:
import pandas as pd
a = pd.read_csv("../results/catalog_audit.tsv", sep="\t")

print("="*60, "\nEXCLUDE — do you agree these should be out?\n", "="*60)
for _, r in a[a["keep"]=="EXCLUDE"].iterrows():
    print(f"\n{r['study_accession']}  gut={r['gut']} site={r['body_site']} host={r['host_verdict']} wgs={r['n_wgs_samples']}")
    print(f"  rationale: {r['rationale']}")
    print(f"  gut ev:  {r['gut_evidence']}")

print("\n", "="*60, "\nREVIEW — why undecided?\n", "="*60)
for _, r in a[a["keep"]=="REVIEW"].iterrows():
    print(f"\n{r['study_accession']}  gut={r['gut']}({r['gut_conf']}) site={r['body_site']} host={r['host_verdict']}")
    print(f"  rationale: {r['rationale']}")

print("\n", "="*60, "\n6 KEEP — spot check the confident ones\n", "="*60)
for _, r in a[a["keep"]=="KEEP"].head(6).iterrows():
    print(f"\n{r['study_accession']}  host={r['host']}")
    print(f"  gut ev:  {r['gut_evidence']}")
    print(f"  site ev: {r['site_evidence']}")

print("\n", "="*60, "\n4 flagged HUMAN\n", "="*60)
for _, r in a[a["is_human"].astype(str).str.lower()=="true"].iterrows():
    print(f"  {r['study_accession']}  host={r['host']}  keep={r['keep']}")

============================================================
EXCLUDE — do you agree these should be out?
 ============================================================

PRJNA475246  gut=no site=gut_explicit host=multi_host wgs=286
  rationale: This is a human infant gut microbiome study, not an animal gut study. The host is clearly stated as Homo sapiens, and the project investigates how infant age correlates with gut resistance genes and microbial metabolism during early life using shotgun metagenomics.
  gut ev:  Host field explicitly states 'Homo sapiens'. Paper title and abstract focus on 'infant age' and 'early life' modifications in human gut microbiota, not animal gut microbiota. This is a human infant study, not an animal study.

PRJNA398089  gut=no site=gut_explicit host=single_clear wgs=2041
  rationale: This is a HUMAN inflammatory bowel disease microbiome study, not an animal gut study. It is a legitimate gut microbiome investigation with clear human intestinal sampling sites and a single host species (Homo sapiens). Audit flagged: the mixed sequencing strategy (WGS + 16S + RNA-Seq) requires clarification, but the core study design is sound for its stated purpose.
  gut ev:  Host field states 'Homo sapiens'; paper title explicitly addresses 'inflammatory bowel disease patients' (human disease); isolation sources are human intestinal sites (colon, cecum, ileum, rectum, sigmoid). This is a HUMAN study, not an animal study.

PRJEB50555  gut=no site=gut_explicit host=unclear wgs=537
  rationale: This is a human gut metagenomics study (PRJEB50555), not an animal gut study, and therefore falls outside the scope of this animal gut metagenomics audit. The study uses valid WGS shotgun metagenomics on 537 samples, but host metadata and study context are absent from provided evidence.
  gut ev:  Biome label explicitly states 'human gut metagenome'. Host is human, not animal. Per instructions, human gut studies are excluded from animal gut audit scope.

 ============================================================
REVIEW — why undecided?
 ============================================================

PRJNA820553  gut=yes(high) site=gut_explicit host=multi_host
  rationale: This is a genuine multi-host ancient gut microbiome study (feces from Equus asinus donkeys, birds, and other herbivores from Chehrabad salt mine), with shotgun metagenomics applied. The primary host is donkey (Equus asinus), but the collection includes samples from other animal origins, making this a mixed-host survey.

PRJEB58441  gut=uncertain(low) site=gut_explicit host=unclear
  rationale: This is a metagenomic fecal study with unambiguous gut sampling (587 WGS samples). However, the complete absence of host species identification, paper title, and abstract prevents confirmation that it is a genuine animal (vs. human) gut study or resolution of potential multi-host issues. Recommend obtaining host metadata before final curation.

PRJDB16260  gut=yes(high) site=gut_explicit host=multi_host
  rationale: This is a genuine multi-patient human gut microbiome study using shotgun metagenomics (WGS) on fecal samples from Japanese individuals. The study design, sequencing strategy, and sampling site are all clearly aligned with human gut metagenomics research.

PRJEB77930  gut=uncertain(low) site=gut_explicit host=unclear
  rationale: This project is labeled as a gut metagenome with shotgun WGS data, but critical metadata—host identity, paper title, sample descriptions—are entirely absent. Cannot audit whether this is a genuine animal gut study or confirm the host is not human without additional evidence.

 ============================================================
6 KEEP — spot check the confident ones
 ============================================================

PRJNA379709  host=Mus musculus
  gut ev:  Paper title explicitly states 'Gut Microbiome' and studies functional changes in gut microbiome in colon cancer model. Biome label confirms 'mouse gut metagenome'. Sample titles reference 'Cecal DNA content' and 'Cecal RNA content'—cecum is part of the gut.
  site ev: Sample titles explicitly name 'Cecal' samples (cecum is a gut compartment). Biome label states 'mouse gut metagenome'. Paper title and abstract context (colon cancer, gut microbiome) confirm intestinal sampling.

PRJNA806482  host=Rattus (rat genus)
  gut ev:  Biome label 'feces metagenome' and isolation_source 'feces' explicitly indicate gut-derived samples. ENA library_source is METAGENOMIC (community DNA), consistent with microbiome study. Host field states RAT.
  site ev: Isolation source explicitly states 'feces' and biome is labeled 'feces metagenome'. Feces is unambiguously a gut sample.

PRJNA873123  host=Gallus gallus
  gut ev:  Biome label explicitly states 'chicken gut metagenome'; host field is Gallus gallus (chicken); library_source is METAGENOMIC (community DNA); 32 WGS samples present.
  site ev: Biome label 'chicken gut metagenome' explicitly designates the gut as the body site sampled.

PRJDB9383  host=Mus musculus
  gut ev:  Biome label explicitly states 'mouse gut metagenome'; sample titles consistently reference 'mice fecal' samples; library_source is METAGENOMIC (community DNA, not single organism genomic)
  site ev: Biome label 'mouse gut metagenome'; all sample titles specify 'fecal' origin (e.g., '16S rRNA isolated from mice fecal in HFPg1')

PRJNA947387  host=C57BL/6J (laboratory mouse)
  gut ev:  Biome label explicitly states 'feces metagenome'; 27 WGS samples with METAGENOMIC library_source; feces is unambiguously gut-derived material.
  site ev: Biome label: 'feces metagenome' – feces is the canonical gut microbiome sampling source.

PRJNA1211805  host=Sus scrofa (pig)
  gut ev:  Title explicitly states 'porcine faecal microbiome'; abstract states 'gut microbiome' and 'faecal microbiomes at four production stages were examined in 18 farms, using shotgun sequencing.' This is a genuine primary study of animal gut microbiota.
  site ev: Abstract explicitly mentions 'faecal microbiomes'; isolation_source lists 'feces'; biome labels include 'gut metagenome'; paper title specifies 'faecal microbiome.' Fecal samples are the standard proxy for gut microbiota.

 ============================================================
4 flagged HUMAN
 ============================================================
  PRJNA475246  host=Homo sapiens (infant)  keep=EXCLUDE
  PRJNA389927  host=Homo sapiens  keep=KEEP
  PRJDB16260  host=Homo sapiens  keep=REVIEW
  PRJNA398089  host=Homo sapiens  keep=EXCLUDE

In [15]:
import os
os.remove("../results/audit_verdicts.json")   # clear old verdicts

import importlib, src.audit_catalog_v3
importlib.reload(src.audit_catalog_v3)
src.audit_catalog_v3.LIMIT = 30
from src.audit_catalog_v3 import run as audit
sample = audit()

** VALIDATION RUN — first 30 **
Auditing 30 studies...

  0/30
  10/30
  20/30

====================================================
AUDIT COMPLETE
====================================================
Keep decision:
keep
KEEP       23
REVIEW      4
EXCLUDE     3

Criterion 1 gut:
gut
yes          24
no            3
uncertain     2
              1

Criterion 2 body_site:
body_site
gut_explicit    28
                 1
gut_inferred     1

Criterion 3 host:
host_verdict
single_clear    24
multi_host       3
unclear          2
                 1

method agreement:
method_note
agree       27
mismatch     2
             1

Flagged human (kept, for scope decision): 5
EXCLUDE: 3  REVIEW: 4  KEEP: 23
Saved -> ../results/catalog_audit.tsv

In [16]:
import pandas as pd
a = pd.read_csv("../results/catalog_audit.tsv", sep="\t")

print("=== EXCLUDE (should be ONLY genuine not-gut / no-WGS / incidental) ===")
for _, r in a[a["keep"]=="EXCLUDE"].iterrows():
    print(f"\n{r['study_accession']}  gut={r['gut']} site={r['body_site']} host={r['host_verdict']} human={r['is_human']} wgs={r['n_wgs_samples']} src={r['library_source']}")
    print(f"  {r['llm_notes'][:200]}")

print("\n\n=== the 4 flagged HUMAN — where did they land? ===")
for _, r in a[a["is_human"]==True].iterrows():
    print(f"  {r['study_accession']}  keep={r['keep']}  gut={r['gut']} site={r['body_site']}")

print("\n\n=== REVIEW ===")
for _, r in a[a["keep"]=="REVIEW"].iterrows():
    print(f"  {r['study_accession']}  keep={r['keep']} gut={r['gut']}({r['gut_conf']}) host={r['host_verdict']} method={r['method_note']}")

=== EXCLUDE (should be ONLY genuine not-gut / no-WGS / incidental) ===

PRJNA475246  gut=no site=gut_inferred host=single_clear human=True wgs=286 src=METAGENOMIC
  GUT: no (high) — Host field explicitly states 'Homo sapiens' and sample titles reference 'Child' at various ages (Birth, 14 days, 1 month, 2 months, 3 months). This is a human infant study, not an ani

PRJNA398089  gut=no site=gut_explicit host=single_clear human=True wgs=2041 src=METAGENOMIC
  GUT: no (high) — Host field explicitly states 'Homo sapiens' (human). While this is a gut microbiome study, the criterion 'true_animal_gut' conventionally excludes human subjects. The study is human-f

PRJEB50555  gut=no site=gut_explicit host=single_clear human=True wgs=537 src=METAGENOMIC
  GUT: no (high) — Biome label explicitly states 'human gut metagenome'; host field is empty/none, and no animal host species are identified in samples (0 distinct). This is a human gut study, not an an


=== the 4 flagged HUMAN — where did they land? ===
  PRJNA475246  keep=EXCLUDE  gut=no site=gut_inferred
  PRJNA389927  keep=KEEP  gut=yes site=gut_explicit
  PRJDB16260  keep=KEEP  gut=yes site=gut_explicit
  PRJNA398089  keep=EXCLUDE  gut=no site=gut_explicit
  PRJEB50555  keep=EXCLUDE  gut=no site=gut_explicit


=== REVIEW ===
  PRJDB9383  keep=REVIEW gut=yes(high) host=single_clear method=mismatch
  PRJEB58441  keep=REVIEW gut=uncertain(low) host=unclear method=agree
  PRJEB77930  keep=REVIEW gut=uncertain(low) host=unclear method=agree
  PRJNA631951  keep=REVIEW gut=yes(high) host=single_clear method=mismatch

In [17]:
import os
os.remove("../results/audit_verdicts.json")

import importlib, src.audit_catalog_v3
importlib.reload(src.audit_catalog_v3)
src.audit_catalog_v3.LIMIT = 30
from src.audit_catalog_v3 import run as audit
sample = audit()

** VALIDATION RUN — first 30 **
Auditing 30 studies...

  0/30
  10/30
  20/30

====================================================
AUDIT COMPLETE
====================================================
Keep decision:
keep
KEEP      26
REVIEW     4

Criterion 1 gut:
gut
yes          29
uncertain     1

Criterion 2 body_site:
body_site
gut_explicit    29
gut_inferred     1

Criterion 3 host:
host_verdict
single_clear    25
multi_host       3
unclear          2

method agreement:
method_note
agree       27
mismatch     3

Flagged human (kept, for scope decision): 5
EXCLUDE: 0  REVIEW: 4  KEEP: 26
Saved -> ../results/catalog_audit.tsv

In [19]:
import pandas as pd
a = pd.read_csv("../results/catalog_audit.tsv", sep="\t")
print("=== 3 method=mismatch REVIEWs — real contradiction or label quirk? ===")
for _, r in a[a["method_note"]=="mismatch"].iterrows():
    print(f"\n{r['study_accession']}  gut={r['gut']} n_wgs={r['n_wgs_samples']} src={r['library_source']}")
    print(f"  {r['llm_notes']}")

=== 3 method=mismatch REVIEWs — real contradiction or label quirk? ===

PRJDB9383  gut=yes n_wgs=7 src=METAGENOMIC
  GUT: yes (high) — Biome label explicitly states 'mouse gut metagenome'; sample titles consistently reference 'mice fecal' samples; library_source is METAGENOMIC indicating community DNA from microbiome, not host genome. || BODY_SITE: gut_explicit — Biome label states 'mouse gut metagenome'; all sample titles reference 'fecal' samples from mice, which is explicit gut sampling. || HOST: Mus musculus [single_clear] — Host field and host species in samples both uniformly state 'Mus musculus' (1 distinct species); sample titles all reference 'mice', confirming single host species. || METHOD: mismatch — Sample titles consistently state '16S rRNA isolated from mice fecal', indicating 16S rRNA gene sequencing (marker gene approach), but ENA library_strategy_mix reports WGS:7 and WGA:1. WGS/shotgun is whole-genome sequencing, not 16S amplicon sequencing. Stated methodology (16S rRNA) contradicts ENA classification (WGS/WGA). || SUMMARY: This is a genuine mouse gut microbiome study with clear, consistent sampling from fecal material. However, a critical discrepancy exists between the sample titles (which describe 16S rRNA sequencing) and the ENA metadata (which classifies samples as WGS/WGA shotgun sequencing)—suggesting either mislabeling of samples or incorrect ENA categorization.

PRJNA1211805  gut=yes n_wgs=0 src=METAGENOMIC
  GUT: yes (high) — Title: 'Cross-sectional study characterizing the porcine faecal microbiome in commercial farms.' Abstract: 'The faecal microbiomes at four production stages were examined in 18 farms, using shotgun sequencing.' Isolation source explicitly lists 'feces'. This is a genuine animal gut microbiome study using WGS methods. || BODY_SITE: gut_explicit — Title explicitly states 'porcine faecal microbiome'. Abstract: 'faecal microbiomes...examined'. Biome labels include 'gut metagenome'. Isolation source: 'feces'. Body site is explicitly gut/fecal. || HOST: Sus scrofa [single_clear] — Host species in samples shows 1 distinct species: Sus scrofa (domestic pig). Title specifies 'porcine' (pig). This is a single-host study across 18 farms at multiple production stages, not a multi-host comparative survey. || METHOD: mismatch — Abstract states 'shotgun sequencing' (WGS). However, ENA fields show: WGS/shotgun sample count = 0; library_strategy_mix lists only 'WGA:78' (whole genome amplification, not shotgun); library_source = METAGENOMIC (correct for metagenomics but does not resolve the WGS count discrepancy). The stated shotgun sequencing method contradicts ENA's reporting of 0 WGS samples and 78 WGA samples. || SUMMARY: This is a legitimate porcine fecal microbiome study using shotgun sequencing across commercial farms. However, there is a notable discrepancy: the abstract claims shotgun sequencing was used, but ENA metadata records zero shotgun/WGS samples and 78 WGA (whole genome amplification) samples instead, which may indicate preprocessing or data handling differences.

PRJNA631951  gut=yes n_wgs=0 src=METAGENOMIC
  GUT: yes (high) — Paper title explicitly states 'ruminant gut archaeome'; isolation source lists 'rumen'; sample titles specify 'cattle rumen'. Rumen is the foregut of ruminants, a primary digestive compartment. This is a genuine animal gut microbiome study. || BODY_SITE: gut_explicit — Isolation source field states 'rumen'; sample titles explicitly mention 'cattle rumen'; paper title references 'gut archaeome'. Rumen is unambiguously part of the gastrointestinal tract. || HOST: Bos [single_clear] — Host field: Bos (genus of cattle); host species in samples: 1 distinct (Bos); sample titles refer to 'cattle rumen'. Single host genus, clearly identified, non-human. || METHOD: mismatch — ENA library_strategy_mix shows WGA (whole genome amplification):24 samples with 0 WGS/shotgun samples. Paper title and biome labels indicate metagenomic study (METAGENOMIC library_source). WGA is typically applied to low-biomass or amplification-based approaches, not shotgun sequencing. The study appears to be whole-genome amplification metagenomics, not standard shotgun WGS as commonly expected for gut microbiome surveys. || SUMMARY: This is a legitimate single-host (Bos/cattle) gut microbiome study explicitly targeting the rumen archaeome. However, the sequencing method employed (WGA) rather than standard shotgun WGS represents a methodological note for curation purposes.

In [20]:
import os
os.remove("../results/audit_verdicts.json")
import importlib, src.audit_catalog_v3
importlib.reload(src.audit_catalog_v3)
src.audit_catalog_v3.LIMIT = None
from src.audit_catalog_v3 import run as audit
full = audit()

Auditing 1044 studies...

  0/1044
  10/1044
  20/1044
  30/1044
  40/1044
  50/1044
  60/1044
  70/1044
  80/1044
  90/1044
  100/1044
  110/1044
  120/1044
  130/1044
  140/1044
  150/1044
  160/1044
  170/1044
  180/1044
  190/1044
  200/1044
  210/1044
  220/1044
  230/1044
  240/1044
  250/1044
  260/1044
  270/1044
  280/1044
  290/1044
  300/1044
  310/1044
  320/1044
  330/1044
  340/1044
  350/1044
  360/1044
  370/1044
  380/1044
  390/1044
  400/1044
  410/1044
  420/1044
  430/1044
  440/1044
  450/1044
  460/1044
  470/1044
  480/1044
  490/1044
  500/1044
  510/1044
  520/1044
  530/1044
  540/1044
  550/1044
  560/1044
  570/1044
  580/1044
  590/1044
  600/1044
  610/1044
  620/1044
  630/1044
  640/1044
  650/1044
  660/1044
  670/1044
  680/1044
  690/1044
  700/1044
  710/1044
  720/1044
  730/1044
  740/1044
  750/1044
  760/1044
  770/1044
  780/1044
  790/1044
  800/1044
  810/1044
  820/1044
  830/1044
  840/1044
  850/1044
  860/1044
  870/1044
  880/1044
  890/1044
  900/1044
  910/1044
  920/1044
  930/1044
  940/1044
  950/1044
  960/1044
  970/1044
  980/1044
  990/1044
  1000/1044
  1010/1044
  1020/1044
  1030/1044
  1040/1044

====================================================
AUDIT COMPLETE
====================================================
Keep decision:
keep
KEEP       764
REVIEW     252
EXCLUDE     28

Criterion 1 gut:
gut
yes          824
uncertain    168
              30
no            22

Criterion 2 body_site:
body_site
gut_explicit    818
ambiguous       107
gut_inferred     70
                 30
non_gut          19

Criterion 3 host:
host_verdict
single_clear        786
multi_host          127
unclear              78
                     30
genus_only           18
incidental            4
mismatch_flagged      1

method agreement:
method_note
agree       744
mismatch    151
unclear     119
             30

Flagged human (kept, for scope decision): 207
EXCLUDE: 28  REVIEW: 252  KEEP: 764
Saved -> ../results/catalog_audit.tsv

In [21]:
import pandas as pd, json
a = pd.read_csv("../results/catalog_audit.tsv", sep="\t")

# find the errored/blank ones
blank = a[a["gut"].isna() | (a["gut"].astype(str).str.strip()=="")]
print(f"Blank/errored studies: {len(blank)}")
print(blank["study_accession"].tolist())

# check the checkpoint to see what they returned
with open("../results/audit_verdicts.json") as f:
    v = json.load(f)
for acc in blank["study_accession"].head(5):
    print(f"\n{acc}: {v.get(acc)}")

Blank/errored studies: 30
['PRJNA880353', 'PRJEB76898', 'PRJEB32644', 'PRJNA1116530', 'PRJNA356809', 'PRJNA772288', 'PRJNA376580', 'PRJNA593263', 'PRJNA843963', 'PRJNA1123238', 'PRJNA1029302', 'PRJEB33577', 'PRJNA1393111', 'PRJEB6997', 'PRJEB7759', 'PRJEB66224', 'PRJNA671703', 'PRJNA932553', 'PRJDB20286', 'PRJNA753312', 'PRJDB20379', 'PRJNA1243555', 'PRJEB60852', 'PRJNA1134918', 'PRJNA1167890', 'PRJNA876316', 'PRJEB29346', 'PRJNA671745', 'PRJNA559386', 'PRJNA555120']

PRJNA880353: {'rationale': 'PARSE_ERROR'}

PRJEB76898: {'rationale': 'PARSE_ERROR'}

PRJEB32644: {'rationale': 'PARSE_ERROR'}

PRJNA1116530: {'rationale': 'PARSE_ERROR'}

PRJNA356809: {'rationale': 'PARSE_ERROR'}

In [22]:
with open("../results/audit_verdicts.json") as f:
    v = json.load(f)
# remove the errored ones so the audit re-does them
for acc in blank["study_accession"]:
    v.pop(acc, None)
with open("../results/audit_verdicts.json", "w") as f:
    json.dump(v, f)
# re-run — it resumes and fills only the 30 gaps
import importlib, src.audit_catalog_v3
importlib.reload(src.audit_catalog_v3)
src.audit_catalog_v3.LIMIT = None
from src.audit_catalog_v3 import run as audit
audit()

Resuming — 1014 done
Auditing 30 studies...

  0/30
  10/30
  20/30

====================================================
AUDIT COMPLETE
====================================================
Keep decision:
keep
KEEP       750
REVIEW     264
EXCLUDE     30

Criterion 1 gut:
gut
yes          833
uncertain    175
no            25
              11

Criterion 2 body_site:
body_site
gut_explicit    833
ambiguous       108
gut_inferred     71
non_gut          21
                 11

Criterion 3 host:
host_verdict
single_clear        797
multi_host          131
unclear              80
genus_only           19
                     11
incidental            5
mismatch_flagged      1

method agreement:
method_note
agree       750
mismatch    163
unclear     120
             11

Flagged human (kept, for scope decision): 210
EXCLUDE: 30  REVIEW: 264  KEEP: 750
Saved -> ../results/catalog_audit.tsv

,study_accession,keep,gut,gut_conf,body_site,host_verdict,host,is_human,method_note,n_wgs_samples,library_source,llm_notes
0,PRJNA379709,KEEP,yes,high,gut_explicit,single_clear,Mus musculus,False,agree,4,METAGENOMIC,GUT: yes (high) — Paper title explicitly state...
1,PRJNA806482,KEEP,yes,high,gut_explicit,single_clear,rat,False,agree,18,METAGENOMIC,GUT: yes (high) — Biome label 'feces metagenom...
2,PRJNA873123,KEEP,yes,high,gut_explicit,single_clear,Gallus gallus,False,agree,32,METAGENOMIC,GUT: yes (high) — Biome label explicitly state...
3,PRJDB9383,REVIEW,yes,high,gut_explicit,single_clear,Mus musculus,False,mismatch,7,METAGENOMIC,GUT: yes (high) — Biome label explicitly state...
4,PRJNA947387,KEEP,yes,high,gut_explicit,single_clear,C57BL/6J,False,agree,27,METAGENOMIC,GUT: yes (high) — Biome label explicitly state...
...,...,...,...,...,...,...,...,...,...,...,...,...
1039,PRJNA876316,REVIEW,uncertain,low,gut_explicit,unclear,rat (inferred from title; genus unknown),False,mismatch,1,METAGENOMIC,GUT: uncertain (low) — Paper title states 'rat...
1040,PRJEB29346,REVIEW,uncertain,low,gut_inferred,single_clear,Gadus morhua,False,mismatch,0,METAGENOMIC,GUT: uncertain (low) — Paper title explicitly ...
1041,PRJNA671745,REVIEW,yes,high,gut_explicit,single_clear,Procambarus clarkii (red swamp crayfish),False,mismatch,44,METAGENOMIC,GUT: yes (high) — Paper title explicitly state...
1042,PRJNA559386,EXCLUDE,no,high,gut_explicit,single_clear,Mus musculus,False,mismatch,0,GENOMIC,GUT: no (high) — Title explicitly states focus...
1043,PRJNA555120,REVIEW,yes,high,gut_explicit,single_clear,Macaca mulatta,False,mismatch,0,METAGENOMIC,GUT: yes (high) — Paper title explicitly state...

In [23]:
import pandas as pd
a = pd.read_csv("../results/catalog_audit.tsv", sep="\t")

# the 30 that were previously blank
prev_blank = ['PRJNA880353','PRJEB76898','PRJEB32644','PRJNA1116530','PRJNA356809',
'PRJNA772288','PRJNA376580','PRJNA593263','PRJNA843963','PRJNA1123238','PRJNA1029302',
'PRJEB33577','PRJNA1393111','PRJEB6997','PRJEB7759','PRJEB66224','PRJNA671703','PRJNA932553',
'PRJDB20286','PRJNA753312','PRJDB20379','PRJNA1243555','PRJEB60852','PRJNA1134918',
'PRJNA1167890','PRJNA876316','PRJEB29346','PRJNA671745','PRJNA559386','PRJNA555120']

redone = a[a["study_accession"].isin(prev_blank)]
print("Where the 30 re-runs landed:")
print(redone["keep"].value_counts().to_string())

print("\n--- any that are still blank/errored? ---")
still_blank = redone[redone["gut"].isna() | (redone["gut"].astype(str).str.strip()=="")]
print(f"Still blank: {len(still_blank)}")

print("\n--- the EXCLUDE ones among the 30 — are they genuine? ---")
for _, r in redone[redone["keep"]=="EXCLUDE"].iterrows():
    print(f"\n{r['study_accession']}  gut={r['gut']} site={r['body_site']} host={r['host_verdict']} n_wgs={r['n_wgs_samples']} src={r['library_source']}")
    print(f"  {str(r['llm_notes'])[:250]}")

Where the 30 re-runs landed:
keep
KEEP       14
REVIEW     12
EXCLUDE     4

--- any that are still blank/errored? ---
Still blank: 11

--- the EXCLUDE ones among the 30 — are they genuine? ---

PRJNA376580  gut=no site=non_gut host=incidental n_wgs=24 src=METAGENOMIC
  GUT: no (high) — Paper title and abstract describe infant gut microbiome and carbohydrate metabolism, but isolation source explicitly states 'Magee Womens Hospital, Pittsburgh, Pennsylvania, USA; hospital NICU surfaces and sink samples' — these are N

PRJNA671703  gut=no site=non_gut host=genus_only n_wgs=229 src=METAGENOMIC
  GUT: no (high) — Study explicitly sampled 'fresh manure, manure from pits, and field soil' – the biome labels are 'manure metagenome; soil metagenome', not gut microbiome. Host field is 'manure metagenome'. While the abstract mentions that 'storage o

PRJEB60852  gut=nan site=nan host=nan n_wgs=0 src=GENOMIC
  GUT:  () —  || BODY_SITE:  —  || HOST:  [] —  || METHOD:  —  || SUMMARY: PARSE_ERROR

PRJNA559386  gut=no site=gut_explicit host=single_clear n_wgs=0 src=GENOMIC
  GUT: no (high) — Title explicitly states focus is 'DNA methylation from bacteria and microbiome using nanopore sequencing'—a methodological study about sequencing technology, NOT a microbiome compositional or functional study. WGS/shotgun sample coun

In [24]:
import pandas as pd, json
a = pd.read_csv("../results/catalog_audit.tsv", sep="\t")

# still-blank ones
still_blank = a[a["gut"].isna() | (a["gut"].astype(str).str.strip()=="") | (a["gut"].astype(str)=="nan")]
redo = still_blank["study_accession"].tolist()
print(f"Still-blank studies: {len(redo)}")
print(redo)

# remove them from checkpoint so they re-run
with open("../results/audit_verdicts.json") as f:
    v = json.load(f)
for acc in redo:
    v.pop(acc, None)
with open("../results/audit_verdicts.json", "w") as f:
    json.dump(v, f)
print("Cleared from checkpoint — re-run the audit to retry these")

Still-blank studies: 11
['PRJEB76898', 'PRJEB32644', 'PRJNA356809', 'PRJNA772288', 'PRJNA843963', 'PRJNA1123238', 'PRJNA932553', 'PRJDB20379', 'PRJEB60852', 'PRJNA1134918', 'PRJNA1167890']
Cleared from checkpoint — re-run the audit to retry these

In [25]:
import importlib, src.audit_catalog_v3
importlib.reload(src.audit_catalog_v3)
src.audit_catalog_v3.LIMIT = None
from src.audit_catalog_v3 import run as audit
audit()

Resuming — 1033 done
Auditing 11 studies...

  0/11
  10/11

====================================================
AUDIT COMPLETE
====================================================
Keep decision:
keep
KEEP       749
REVIEW     264
EXCLUDE     31

Criterion 1 gut:
gut
yes          834
uncertain    175
no            27
               8

Criterion 2 body_site:
body_site
gut_explicit    834
ambiguous       109
gut_inferred     71
non_gut          22
                  8

Criterion 3 host:
host_verdict
single_clear        798
multi_host          133
unclear              80
genus_only           19
                      8
incidental            5
mismatch_flagged      1

method agreement:
method_note
agree       752
mismatch    164
unclear     120
              8

Flagged human (kept, for scope decision): 211
EXCLUDE: 31  REVIEW: 264  KEEP: 749
Saved -> ../results/catalog_audit.tsv

,study_accession,keep,gut,gut_conf,body_site,host_verdict,host,is_human,method_note,n_wgs_samples,library_source,llm_notes
0,PRJNA379709,KEEP,yes,high,gut_explicit,single_clear,Mus musculus,False,agree,4,METAGENOMIC,GUT: yes (high) — Paper title explicitly state...
1,PRJNA806482,KEEP,yes,high,gut_explicit,single_clear,rat,False,agree,18,METAGENOMIC,GUT: yes (high) — Biome label 'feces metagenom...
2,PRJNA873123,KEEP,yes,high,gut_explicit,single_clear,Gallus gallus,False,agree,32,METAGENOMIC,GUT: yes (high) — Biome label explicitly state...
3,PRJDB9383,REVIEW,yes,high,gut_explicit,single_clear,Mus musculus,False,mismatch,7,METAGENOMIC,GUT: yes (high) — Biome label explicitly state...
4,PRJNA947387,KEEP,yes,high,gut_explicit,single_clear,C57BL/6J,False,agree,27,METAGENOMIC,GUT: yes (high) — Biome label explicitly state...
...,...,...,...,...,...,...,...,...,...,...,...,...
1039,PRJNA932553,KEEP,,,,,,False,,48,METAGENOMIC,GUT: () — || BODY_SITE: — || HOST: [] — ...
1040,PRJDB20379,KEEP,,,,,,False,,63,METAGENOMIC,GUT: () — || BODY_SITE: — || HOST: [] — ...
1041,PRJEB60852,EXCLUDE,no,high,ambiguous,single_clear,Rangifer tarandus platyrhynchus,False,mismatch,0,GENOMIC,GUT: no (high) — library_strategy_mix shows 'H...
1042,PRJNA1134918,KEEP,,,,,,False,,12,METAGENOMIC,GUT: () — || BODY_SITE: — || HOST: [] — ...
1043,PRJNA1167890,KEEP,,,,,,False,,0,METAGENOMIC,GUT: () — || BODY_SITE: — || HOST: [] — ...

In [26]:
import pandas as pd
a = pd.read_csv("../results/catalog_audit.tsv", sep="\t")


still = a[a["gut"].isna() | (a["gut"].astype(str).str.strip()=="") | (a["gut"].astype(str)=="nan")]
print(f"Still blank/errored: {len(still)}")
if len(still):
    print(still["study_accession"].tolist())
    
    import json
    with open("../results/audit_verdicts.json") as f:
        v = json.load(f)
    for acc in still["study_accession"]:
        print(f"  {acc}: {v.get(acc, {}).get('rationale', '?')}")

Still blank/errored: 8
['PRJEB76898', 'PRJEB32644', 'PRJNA356809', 'PRJNA772288', 'PRJNA932553', 'PRJDB20379', 'PRJNA1134918', 'PRJNA1167890']
  PRJEB76898: PARSE_ERROR
  PRJEB32644: PARSE_ERROR
  PRJNA356809: PARSE_ERROR
  PRJNA772288: PARSE_ERROR
  PRJNA932553: PARSE_ERROR
  PRJDB20379: PARSE_ERROR
  PRJNA1134918: PARSE_ERROR
  PRJNA1167890: PARSE_ERROR

In [28]:
import importlib, src.audit_catalog_v3
importlib.reload(src.audit_catalog_v3)
src.audit_catalog_v3.LIMIT = None
from src.audit_catalog_v3 import run as audit
full = audit()

Resuming — 1044 done
Auditing 0 studies...


====================================================
AUDIT COMPLETE
====================================================
Keep decision:
keep
KEEP       741
REVIEW     272
EXCLUDE     31

Criterion 1 gut:
gut
yes          834
uncertain    175
no            27
               8

Criterion 2 body_site:
body_site
gut_explicit    834
ambiguous       109
gut_inferred     71
non_gut          22
                  8

Criterion 3 host:
host_verdict
single_clear        798
multi_host          133
unclear              80
genus_only           19
                      8
incidental            5
mismatch_flagged      1

method agreement:
method_note
agree       752
mismatch    164
unclear     120
              8

Flagged human (kept, for scope decision): 211
EXCLUDE: 31  REVIEW: 272  KEEP: 741
Saved -> ../results/catalog_audit.tsv

In [29]:
import pandas as pd
a = pd.read_csv("../results/catalog_audit.tsv", sep="\t")

# are the known parse-error studies now in REVIEW?
parse_errors = ['PRJEB76898','PRJEB32644','PRJNA356809','PRJNA772288','PRJNA932553',
                'PRJDB20379','PRJNA1134918','PRJNA1167890','PRJEB60852']
print("Where the parse-error studies landed:")
print(a[a["study_accession"].isin(parse_errors)][["study_accession","keep","gut"]].to_string(index=False))

# what's actually in EXCLUDE now?
print(f"\nEXCLUDE count: {(a['keep']=='EXCLUDE').sum()}")
print("Blank-gut studies still in EXCLUDE:")
exc = a[a["keep"]=="EXCLUDE"]
blank_in_exc = exc[exc["gut"].isna() | (exc["gut"].astype(str).str.strip().isin(["","nan"]))]
print(f"  {len(blank_in_exc)}: {blank_in_exc['study_accession'].tolist()}")

Where the parse-error studies landed:
study_accession    keep gut
     PRJEB76898  REVIEW NaN
     PRJEB32644  REVIEW NaN
    PRJNA356809  REVIEW NaN
    PRJNA772288  REVIEW NaN
    PRJNA932553  REVIEW NaN
     PRJDB20379  REVIEW NaN
     PRJEB60852 EXCLUDE  no
   PRJNA1134918  REVIEW NaN
   PRJNA1167890  REVIEW NaN

EXCLUDE count: 31
Blank-gut studies still in EXCLUDE:
  0: []

In [31]:
import sys
!{sys.executable} -m pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [35]:
import importlib, src.build_comparison_xlsx
importlib.reload(src.build_comparison_xlsx)
from src.build_comparison_xlsx import build
build()

KeyError: "['body_site'] not in index"

In [36]:
import pandas as pd
audit = pd.read_csv("../results/catalog_audit.tsv", sep="\t")
print("Columns in catalog_audit.tsv:")
print(audit.columns.tolist())

Columns in catalog_audit.tsv:
['study_accession', 'keep', 'gut', 'gut_conf', 'body_site', 'host_verdict', 'host', 'is_human', 'method_note', 'n_wgs_samples', 'library_source', 'llm_notes']

In [37]:
import pandas as pd
cat = pd.read_csv("../results/yes_catalog.tsv", sep="\t")
audit = pd.read_csv("../results/catalog_audit.tsv", sep="\t")

AUDIT_COLS = ["keep", "is_human", "gut", "body_site", "host_verdict", "method_note", "llm_notes"]
merged = cat.merge(audit[["study_accession"] + AUDIT_COLS], on="study_accession", how="left")

print("body_site in merged?", "body_site" in merged.columns)
# check for suffix collisions
print("cols with body:", [c for c in merged.columns if "body" in c.lower()])
print("cols with _x or _y suffix:", [c for c in merged.columns if c.endswith("_x") or c.endswith("_y")])

body_site in merged? False
cols with body: ['body_site_x', 'llm_body_site_signal', 'body_sites', 'body_site_y']
cols with _x or _y suffix: ['body_site_x', 'body_site_y']

In [38]:
import importlib, src.build_comparison_xlsx
importlib.reload(src.build_comparison_xlsx)
from src.build_comparison_xlsx import build
build()

KeyError: "['body_site'] not in index"

In [39]:
import pandas as pd
cat = pd.read_csv("../results/yes_catalog.tsv", sep="\t")
audit = pd.read_csv("../results/catalog_audit.tsv", sep="\t")

AUDIT_COLS = ["keep", "is_human", "gut", "body_site", "host_verdict", "method_note", "llm_notes"]

# what overlaps?
overlap = [c for c in AUDIT_COLS if c in cat.columns]
print("Overlap to drop:", overlap)

cat2 = cat.drop(columns=overlap)
merged = cat2.merge(audit[["study_accession"] + AUDIT_COLS], on="study_accession", how="left")
print("body_site in merged now?", "body_site" in merged.columns)
print("body cols:", [c for c in merged.columns if "body" in c.lower()])

Overlap to drop: ['body_site']
body_site in merged now? True
body cols: ['llm_body_site_signal', 'body_sites', 'body_site']

In [42]:
with open("../src/build_comparison_xlsx.py") as f:
    content = f.read()
print("Has the fix?", "overlap = [c for c in AUDIT_COLS if c in cat.columns" in content)

Has the fix? False

In [47]:
# 1. confirm the fix is actually on disk this time
with open("../src/build_comparison_xlsx.py") as f:
    print("Has the fix?", "overlap = [c for c in AUDIT_COLS if c in cat.columns" in f.read())

# 2. force-fresh import and build
import sys
if "src.build_comparison_xlsx" in sys.modules:
    del sys.modules["src.build_comparison_xlsx"]
from src.build_comparison_xlsx import build
build()

Has the fix? True
In common with GMTOL: 40
Only Ananya's catalog (KEEP+REVIEW): 973
  KEEP: 712  REVIEW: 261
  flagged human in mine-only: 205

Saved -> ../results/catalog_vs_gmtol_comparison.xlsx